import type { ResearchPost } from './fleet-content';

const nist=['NIST SSDF','https://csrc.nist.gov/Projects/ssdf'] as const;
const owasp=['OWASP ASVS','https://owasp.org/www-project-application-security-verification-standard/'] as const;
const github=['GitHub review documentation','https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'] as const;
const dora=['DORA research program','https://dora.dev/research/'] as const;
const google=['Google Engineering Practices','https://google.github.io/eng-practices/'] as const;
const cisa=['CISA Secure by Design','https://www.cisa.gov/securebydesign'] as const;
const wcag=['W3C WCAG 2.2','https://www.w3.org/TR/WCAG22/'] as const;
const privacy=['NIST Privacy Framework','https://www.nist.gov/privacy-framework'] as const;
const paragraph=(a:readonly string[],i:number)=>`Research on ${a[2].toLowerCase()} should use ${a[3]} rather than a title, a one-time impression, or an unbounded promise. ${a[4]} provide useful principles, but the local product determines the actual observation. The study should define the affected cohort, period, owner, expected behavior, and evidence that would change the decision. In outsourced programming, that precision matters because a contributor works inside constraints created by another organization.`;
const bodyFor=(a:readonly string[]):readonly string[]=>Array.from({length:15},(_,i)=>i===0?paragraph(a,i):`The evidence for ${a[2].toLowerCase()} begins with a bounded task and named outcome. ${a[5]}. Record inputs, assumptions, expected result, checks, unresolved risks, and authority boundary. A reviewer should distinguish implementation from waiting, missing context, scope change, and owner-controlled decisions. The contributor explains observations; the company owner decides acceptance, sensitive access, customer impact, and release authority. Preserve what was not tested, report denominator and period, inspect failure and recovery states, and state limitations. ${a[6]}`);
export const august14ResearchBatch:ReadonlyArray<ResearchPost>=[
  {slug:"outsourced-developer-capability-evidence-study",title:"Evidence for assessing outsourced developer capability",excerpt:"Evidence for assessing outsourced developer capability. An evidence-led research note for software teams.",topic:"Capability evidence",published:'2026-08-14',body:bodyFor(["outsourced-developer-capability-evidence-study","Evidence for assessing outsourced developer capability","Capability evidence","a representative work sample","NIST SSDF and GitHub review records","score comprehension, implementation, verification, communication, and security judgment separately","a sample predicts similar work, not an entire career"]),sources:[nist,github,google,cisa]},
  {slug:"outsourced-programmer-code-ownership-study",title:"Code ownership boundaries in outsourced programming teams",excerpt:"Code ownership boundaries in outsourced programming teams. An evidence-led research note for software teams.",topic:"Code ownership",published:'2026-08-14',body:bodyFor(["outsourced-programmer-code-ownership-study","Code ownership boundaries in outsourced programming teams","Code ownership","a subsystem and consequential decision","NIST SSDF and GitHub review records","test bug, schema, security, and documentation scenarios against named roles","ownership maps become stale and cannot replace incident conversation"]),sources:[nist,github,google,cisa]},
  {slug:"outsourced-api-contract-evidence-study",title:"API contract evidence for outsourced application work",excerpt:"API contract evidence for outsourced application work. An evidence-led research note for software teams.",topic:"API contracts",published:'2026-08-14',body:bodyFor(["outsourced-api-contract-evidence-study","API contract evidence for outsourced application work","API contracts","a consumer version paired with normal and unauthorized requests","OWASP ASVS and CISA Secure by Design","compare before and after contracts with safe fixtures and compatibility promises","dormant clients and staging gaps can hide integrations"]),sources:[owasp,nist,cisa,github]},
  {slug:"outsourced-programmer-documentation-accuracy-study",title:"Measuring documentation accuracy in outsourced programming work",excerpt:"Measuring documentation accuracy in outsourced programming work. An evidence-led research note for software teams.",topic:"Documentation accuracy",published:'2026-08-14',body:bodyFor(["outsourced-programmer-documentation-accuracy-study","Measuring documentation accuracy in outsourced programming work","Documentation accuracy","a complete task performed by an independent reader","Google Engineering Practices and NIST SSDF","record prerequisites, actions, results, deviations, owner, environment, and date","a reader may not represent every audience"]),sources:[google,nist,github,cisa]},
  {slug:"outsourced-programmer-access-lifecycle-study",title:"Access lifecycle evidence for outsourced programmers",excerpt:"Access lifecycle evidence for outsourced programmers. An evidence-led research note for software teams.",topic:"Access lifecycle",published:'2026-08-14',body:bodyFor(["outsourced-programmer-access-lifecycle-study","Access lifecycle evidence for outsourced programmers","Access lifecycle","a named identity, task purpose, privilege, trigger, and removal event","NIST account guidance and OWASP ASVS","compare approved purpose with effective access after lifecycle events","inventories may be incomplete and emergency access reconstructed later"]),sources:[privacy,owasp,nist,cisa]},
  {slug:"outsourced-programmer-estimation-uncertainty-study",title:"Estimating uncertainty in outsourced programming work",excerpt:"Estimating uncertainty in outsourced programming work. An evidence-led research note for software teams.",topic:"Estimation uncertainty",published:'2026-08-14',body:bodyFor(["outsourced-programmer-estimation-uncertainty-study","Estimating uncertainty in outsourced programming work","Estimation uncertainty","a bounded work unit with assumptions, range, and checkpoint","DORA research and Google Engineering Practices","separate discovery, implementation, review, waiting, and scope change","small samples and new codebases make ranges noisy"]),sources:[dora,google,github,nist]},
  {slug:"outsourced-programmer-accessibility-evidence-study",title:"Accessibility evidence in outsourced web development",excerpt:"Accessibility evidence in outsourced web development. An evidence-led research note for software teams.",topic:"Accessibility evidence",published:'2026-08-14',body:bodyFor(["outsourced-programmer-accessibility-evidence-study","Accessibility evidence in outsourced web development","Accessibility evidence","a supported journey tested through keyboard and assistive states","WCAG 2.2 and CISA Secure by Design","record route, action, focus, announcement, result, recovery, and exclusions","browser, content, and assistive-technology variation limits samples"]),sources:[wcag,google,cisa,nist]},
  {slug:"outsourced-programmer-data-minimization-study",title:"Data minimization for outsourced programming assignments",excerpt:"Data minimization for outsourced programming assignments. An evidence-led research note for software teams.",topic:"Data minimization",published:'2026-08-14',body:bodyFor(["outsourced-programmer-data-minimization-study","Data minimization for outsourced programming assignments","Data minimization","a behaviorally representative fixture with retention and owner approval","NIST Privacy Framework and OWASP ASVS","compare synthetic and sensitive fixtures for edge-case preservation and deletion","masking, hidden copies, vendor logs, and jurisdiction complicate proof"]),sources:[privacy,owasp,nist,cisa]},
  {slug:"outsourced-programmer-technical-debt-evidence-study",title:"Evidence for prioritizing technical debt with outsourced programmers",excerpt:"Evidence for prioritizing technical debt with outsourced programmers. An evidence-led research note for software teams.",topic:"Technical debt evidence",published:'2026-08-14',body:bodyFor(["outsourced-programmer-technical-debt-evidence-study","Evidence for prioritizing technical debt with outsourced programmers","Technical debt evidence","a measurable friction, cohort, intervention, and success signal","DORA research and NIST SSDF","compare defects, review rework, recovery, dependency risk, and documentation before and after","causes are diffuse and product changes confound results"]),sources:[dora,google,nist,owasp]},
  {slug:"outsourced-programmer-handoff-completeness-study",title:"Handoff completeness in distributed programming work",excerpt:"Handoff completeness in distributed programming work. An evidence-led research note for software teams.",topic:"Handoff completeness",published:'2026-08-14',body:bodyFor(["outsourced-programmer-handoff-completeness-study","Handoff completeness in distributed programming work","Handoff completeness","a state transition with outcome, checks, risks, and next owner","Google Engineering Practices and GitHub review records","ask an independent reader to summarize state, reproduce a check, and name the decision","some decisions require live discussion and readers vary in familiarity"]),sources:[google,github,nist,dora]},
];
