import type { ResearchPost } from './fleet-content';

const sources = {
  dora: ['DORA research', 'https://dora.dev/research/'] as const,
  nist: ['NIST Secure Software Development Framework', 'https://csrc.nist.gov/Projects/ssdf'] as const,
  owasp: ['OWASP API Security', 'https://owasp.org/API-Security/'] as const,
  wcag: ['W3C Web Content Accessibility Guidelines', 'https://www.w3.org/TR/WCAG22/'] as const,
  github: ['GitHub pull request reviews', 'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'] as const,
  otel: ['OpenTelemetry documentation', 'https://opentelemetry.io/docs/'] as const,
  cisa: ['CISA Secure by Design', 'https://www.cisa.gov/securebydesign'] as const,
  google: ['Google Engineering Practices', 'https://google.github.io/eng-practices/'] as const,
};

const common = 'This research is a bounded planning aid for Outsourced Programmers. It does not establish a universal performance target, legal conclusion, security certification, or promise about any particular project. The company technical owner retains authority over production access, merges, releases, customer data, and policy decisions.';

export const august20ResearchBatch: ReadonlyArray<ResearchPost> = [
  { slug: 'outsourced-release-rollback-observability-study', title: 'What evidence shows an outsourced software release can be rolled back safely?', excerpt: 'A research study of recovery evidence, irreversible changes, and decision boundaries in distributed programming work.', topic: 'Rollback observability', published: '2026-08-20', hero: '/research-heroes/2026-08-20/outsourced-release-rollback-observability-study.png', body: [
    'Research question: what evidence shows that a software release prepared by an outsourced programmer can be rolled back safely, rather than merely described as reversible? The question matters because a release can contain database changes, configuration assumptions, queued work, or external side effects that survive a code revert. A useful study therefore examines the recovery unit, the prior known-good state, the trigger for reversal, and the checks that prove the service returned to an acceptable condition.',
    'The evidence scope is a bounded sample of release records from one application or work lane. It should include ordinary releases, changes with migrations, feature-flagged changes, and at least one intentionally rejected rehearsal. The unit of analysis is the release record, not the individual programmer. This distinction keeps a recovery control focused on system design and decision quality instead of turning sparse operational evidence into a personnel judgment.',
    'Methodology begins by extracting the artifact identity, source revision, configuration version, migration status, dependency assumptions, and owner-approved recovery boundary. Reviewers then compare the stated rollback procedure with a controlled rehearsal in an approved non-production environment. They record the time to restore the prior behavior, failed checks, data reconciliation needs, and any step that required undocumented knowledge. A rehearsal that succeeds only because an expert intervenes silently is incomplete evidence.',
    'DORA research treats reliable delivery as a property of the delivery system, while the NIST Secure Software Development Framework emphasizes protected releases and response readiness. Those sources do not prescribe one rollback command. They support a narrower inference: recovery should be designed, protected, rehearsed, and observable. For an outsourced programming lane, the programmer may prepare scripts, fixtures, migration notes, and rehearsal results, while the company keeps approval for release execution and production recovery.',
    'The strongest finding is usually not a single recovery time. It is a map of boundaries. Code-only changes may have a tested reversal, whereas a destructive data transformation may require a forward repair or restore procedure. A third-party callback may create an external side effect that cannot be undone. A queued job may need idempotency or cancellation evidence. Classifying these cases prevents the phrase “rollback ready” from hiding materially different risks.',
    'Measurement should separate preparation from outcome. Useful fields include the share of releases with a named prior state, the share with a tested verification query, rehearsal failures by cause, unresolved irreversible steps, and time spent waiting for an owner decision. Median and upper-quartile recovery times are more informative than a single average, but none proves that an untested release will behave the same way under production load.',
    'Analysis must also account for false confidence. A green health check can miss stale data, broken permissions, delayed workers, or a user journey that was not included in the rehearsal. Conversely, a failed rehearsal may expose a valuable control gap before customers are affected. The interpretation should state which routes, data shapes, integrations, and environments were included, and which were outside scope.',
    'Limitations are substantial. A staging rehearsal may not reproduce production traffic, provider timing, data volume, secrets, or operational staffing. Recovery objectives may be contractual or business decisions that technical evidence cannot set. A release sample from one codebase cannot establish a benchmark for all outsourced work. Legal, privacy, security, and continuity reviewers may require additional controls.',
    'Conclusion: an outsourced release is rollback-observable when its artifact, prior state, irreversible boundaries, authorized operator, rehearsal evidence, and post-recovery checks are explicit. The evidence-led next step is a small release class with a controlled rehearsal and a written decision record. That creates a safer basis for owner approval without transferring production authority or treating recovery speed as a programmer quota.', common
  ], sources: [sources.dora, sources.nist, sources.github, sources.otel], related: ['outsourced-release-rollback-readiness-study'] },
  { slug: 'outsourced-api-contract-drift-evidence-study', title: 'How should outsourced teams study API contract drift?', excerpt: 'Research on compatibility evidence across API consumers, versions, and delegated programming handoffs.', topic: 'API contract drift', published: '2026-08-20', hero: '/research-heroes/2026-08-20/outsourced-api-contract-drift-evidence-study.png', body: [
    'Research question: how can a distributed programming team distinguish harmless API evolution from contract drift that will break an authorized consumer? The answer cannot come from comparing endpoint names alone. A contract includes required fields, types, status behavior, authorization assumptions, error shapes, pagination, ordering, and timing expectations. Outsourced work needs a method that makes those assumptions visible to the reviewer who owns compatibility and release decisions.',
    'The evidence scope should name the API surface, consumer versions, environment, fixture set, and observation period. Include a browser or application client, a background worker where relevant, and a documented external integration only when it is authorized for testing. The study should not use live customer tokens or infer compatibility from a successful request with one ideal payload. A passing happy path is one observation, not proof of contract stability.',
    'Methodology combines a versioned contract comparison with representative request and response fixtures. Reviewers classify differences as additive, tightening, semantic, authorization-related, or operational. Each difference is linked to a consumer and an acceptance decision. Negative cases matter: missing fields, unknown enum values, expired credentials, duplicate submissions, rate limits, and partial outages show whether error handling remains inside the agreed boundary.',
    'OWASP API Security guidance focuses attention on authorization, object access, and input handling, while GitHub review records provide a durable place to connect a change to its evidence. The sources support a practical inference: contract review should join behavioral checks with identity and permission checks. It should not assume that a schema diff captures a change in authorization or business meaning.',
    'A useful outsourced programming record names the old and new contract identities, affected consumers, fixture provenance, checks run, differences found, and decision owner. The programmer can generate comparison output, update tests, and document migration options. The company owner decides whether to preserve backward compatibility, coordinate a consumer release, accept a breaking change, or postpone the work.',
    'Measurements should describe the system rather than reward volume. Track contract differences by severity, consumers covered, failures found before merge, consumer versions still on the old contract, and time spent waiting for a compatibility decision. Report denominators and fixture limitations. A lower count of detected differences can mean a stable API, weak coverage, or an incomplete inventory.',
    'Analysis should distinguish technical drift from intended change. A new optional field may be safe for one consumer but unsafe if a strict decoder rejects unknown values. A renamed error may be harmless to a human but break a machine retry rule. A response that remains schema-valid may still change ordering, precision, or authorization semantics. These distinctions make the research useful for real software decisions.',
    'Limitations include undocumented consumers, provider behavior outside the test environment, delayed mobile releases, and fixtures that omit sensitive or high-volume cases. A compatibility study cannot certify an API under every network condition. Contract policy, privacy review, and release sequencing remain company decisions.',
    'Conclusion: API contract drift becomes reviewable when each difference is tied to a named consumer, observable behavior, representative and negative fixtures, and an explicit compatibility decision. For an outsourced programming lane, the strongest next step is a small version pair with a consumer inventory and evidence package. That supports careful delegation while keeping architecture, policy, and release authority with the client.', common
  ], sources: [sources.owasp, sources.github, sources.nist, sources.google], related: ['outsourced-mobile-api-versioning-study'] },
  { slug: 'outsourced-accessibility-focus-evidence-study', title: 'What proves keyboard focus behavior in outsourced web work?', excerpt: 'A research method for evaluating focus movement, errors, dialogs, and route changes beyond automated scores.', topic: 'Focus accessibility', published: '2026-08-20', hero: '/research-heroes/2026-08-20/outsourced-accessibility-focus-evidence-study.png', body: [
    'Research question: what evidence proves that keyboard focus behavior in an outsourced web change remains usable across dialogs, validation errors, and route transitions? An automated accessibility score can identify some structural issues, but it cannot by itself establish that a keyboard user knows where the interface moved or how to recover. The study therefore treats focus as an observable interaction contract tied to a named journey.',
    'The evidence scope should define the route, browser and assistive technology assumptions, keyboard path, viewport, content state, and affected component. Include normal completion, an error, an empty state, a denied action, and a return from a modal or route change where applicable. The study must use synthetic or approved data and record exactly what was observed, not what the implementation appears intended to do.',
    'Methodology begins with a journey map that marks each expected focus transition. A reviewer performs the path using only the keyboard, records the focused control after each action, and checks whether a visible indicator remains perceivable. A second pass tests recovery: where focus lands after a rejected form, whether a closed dialog returns to its opener, and whether a route update announces or exposes the new context. Screenshots alone are insufficient for keyboard order.',
    'WCAG 2.2 provides success criteria for keyboard operability, focus visibility, and predictable interaction. Google technical-writing guidance adds a useful evidence principle: instructions and observations should be clear to the person who must act on them. Together they support a bounded inference that accessibility review needs repeatable user journeys and explicit observations, not only a tool-generated score or a claim that a component is standard.',
    'For Outsourced Programmers, a programmer can prepare the route, reproduce the issue, add tests, and record browser-specific observations. The client or designated product owner retains decisions about supported experiences, legal exposure, design trade-offs, and release acceptance. A finding should include route, action, expected focus, observed focus, impact, reproduction, and the smallest proposed correction.',
    'Measurements should avoid reducing accessibility to a percentage. Track journeys covered, focus transitions with an explicit expectation, failures by pattern, regression cases retained, and findings reproduced by an independent reviewer. A route with fewer failures may simply have fewer tested states. Severity and user impact require contextual judgment and should not be inferred from automated counts alone.',
    'The analysis should distinguish focus visibility from focus order and from announcement behavior. A visible ring can be present while focus moves to an unexpected region. A correct DOM order can still leave a dialog without a meaningful return point. A screen-reader announcement can be technically present but confusing if the new context lacks a useful title. Naming the specific evidence prevents a broad accessibility label from hiding a fixable interaction defect.',
    'Limitations include differences among browsers, assistive technologies, custom components, localization, zoom, input devices, and dynamic content. A small route sample cannot establish conformance for the entire site. Automated tools and manual review each miss some classes of issue. Legal or accessibility specialists may be needed for formal compliance decisions.',
    'Conclusion: focus behavior is evidence-led when a named journey, expected transition, keyboard observation, visible indicator, error recovery, and limitation are recorded together. The next step for an outsourced programming lane is a representative route with normal and failure states, reviewed by an authorized owner. That produces actionable evidence without overstating what a single test or score proves.', common
  ], sources: [sources.wcag, sources.google, sources.github, sources.nist], related: ['outsourced-accessibility-focus-management-study'] },
  { slug: 'outsourced-webhook-replay-resistance-study', title: 'How can outsourced webhook work prove replay resistance?', excerpt: 'Research on signatures, timestamps, idempotency, and retry evidence for delegated integration work.', topic: 'Webhook security', published: '2026-08-20', hero: '/research-heroes/2026-08-20/outsourced-webhook-replay-resistance-study.png', body: [
    'Research question: what evidence shows that a webhook receiver will reject a replay without also rejecting a legitimate delayed delivery? This is a narrower question than whether a signature exists. A receiver may verify the wrong bytes, accept an old timestamp, process a duplicate side effect, or retry ambiguously. Outsourced integration work needs an evidence model that separates authenticity, freshness, idempotency, and operational recovery.',
    'The evidence scope should specify provider format, signing algorithm, canonical payload, timestamp tolerance, event identifier, receiver endpoint, and side effect under test. Use synthetic events in an isolated environment. Include a valid first delivery, a byte-modified payload, an old timestamp, a repeated event, an out-of-order event, and a delivery that times out after the receiver has accepted it. No live customer event or production secret belongs in the study.',
    'Methodology records the raw fixture identity, signature calculation inputs, clock assumptions, response status, persistence result, and downstream effect count. The repeated event must be tested after a successful first delivery and after an ambiguous timeout. Reviewers then compare the observed behavior with the intended idempotency key and retention window. A response that says “already processed” is useful only if the side effect is demonstrably not repeated.',
    'OWASP API Security guidance emphasizes authentication and authorization risks at API boundaries, while the NIST SSDF supports protecting software and verifying behavior. Those sources do not define a provider-specific replay policy. They support the inference that a webhook study should test the complete boundary: signature verification, freshness, authorization, duplicate handling, logging, and safe retry behavior.',
    'A programmer can prepare fixtures, verification tests, failure classifications, and a proposed repair. The company technical owner keeps secrets, provider configuration, production queues, data retention, and release authority. The evidence should avoid exposing payloads that contain personal or commercial information. Record only the fields needed to reproduce the security decision, with redaction documented where it affects interpretation.',
    'Measurements can include acceptance of valid events, rejection of altered or stale events, duplicate side-effect rate, ambiguous-timeout recovery, and diagnostic completeness. Report the denominator for each case and the configured clock window. Do not interpret a zero duplicate count from one event as proof of idempotency under concurrency or a provider retry storm.',
    'Analysis should distinguish replay from legitimate redelivery. A provider can resend because it did not observe a response, while an attacker can resend a previously valid message. The receiver therefore needs a stable event identity and a policy for retaining processed identities. Clock skew, queue delay, and multiple worker instances may change the result. These are design variables, not reasons to ignore failed cases.',
    'Limitations include provider-specific signing behavior, clock synchronization, storage consistency, concurrency, and downstream systems that have their own retry semantics. A staging queue cannot prove production behavior at every volume. Security review may require threat modeling, secret rotation testing, or specialist assessment beyond this documentary method.',
    'Conclusion: replay resistance is supported when the evidence covers canonical verification, freshness, event identity, duplicate side effects, ambiguous delivery, and bounded diagnostics. A small synthetic event matrix gives the client a better decision basis than a signature-only check. It also keeps implementation support distinct from production credentials and the authority to accept integration risk.', common
  ], sources: [sources.owasp, sources.nist, sources.otel, sources.github], related: ['outsourced-webhook-signature-verification-study'] },
  { slug: 'outsourced-search-index-reconciliation-study', title: 'What evidence shows an outsourced search index is trustworthy?', excerpt: 'A research method for comparing source records, indexed documents, freshness, permissions, and repair outcomes.', topic: 'Search reconciliation', published: '2026-08-20', hero: '/research-heroes/2026-08-20/outsourced-search-index-reconciliation-study.png', body: [
    'Research question: what evidence shows that an application search index is complete, fresh, permission-aware, and repairable after outsourced programming work? Matching a total document count is not enough. A record can be omitted, stale, indexed under the wrong tenant, exposed after deletion, or transformed so that a critical field no longer searches. The study must compare the authoritative source with the index at the level of records and decisions.',
    'The evidence scope should name the source tables or API, index collection, field mapping, permission model, synchronization period, and repair mechanism. Use synthetic or approved masked records that cover creation, update, deletion, empty fields, special characters, permissions, and late-arriving events. The study should include a bounded export or query comparison and must not copy live customer data into a public or unmanaged workspace.',
    'Methodology joins stable source identities to indexed identities and records presence, version, freshness marker, permission attributes, and transformed fields. Reviewers classify differences as missing, stale, unauthorized, malformed, duplicate, or intentionally excluded. A second comparison after a repair action tests whether the correction is repeatable and whether the repair itself creates duplicates or widens visibility.',
    'OpenTelemetry documentation supports tracing work across services, while OWASP API Security guidance highlights authorization at data boundaries. The sources do not prescribe a search algorithm. They support a bounded inference that reconciliation should preserve traceability from source event to index observation and treat permission filtering as a first-class correctness condition, not a later operational concern.',
    'For an outsourced programming lane, the programmer can create comparison queries, fixtures, mapping tests, and a repair proposal. The client owner retains authority over source data, indexing policy, retention, tenant boundaries, and production execution. Every result should state which source is authoritative and what evidence is unavailable. An index that appears current cannot override a source-of-truth decision.',
    'Measurements should include source records sampled, index records matched, age distribution of stale entries, unauthorized visibility findings, duplicate identities, and repair success by category. Report both record-level and field-level coverage. Counts must show the period and cohort. A perfect total can coexist with an incorrect permission field, and a low mismatch rate can hide a severe single exposure.',
    'Analysis should distinguish eventual consistency from data loss. A record missing immediately after creation may be inside an agreed propagation window, while a record absent after the window suggests a synchronization or filtering defect. Updates need version or timestamp evidence so a late event cannot overwrite a newer state. Deletes require a tombstone or equivalent observation, not merely an empty search result.',
    'Limitations include index provider behavior, delayed queues, concurrent updates, tokenization differences, permission changes, and source systems that do not expose stable identifiers. A staging sample cannot establish every production load or tenant shape. Privacy, retention, and access decisions require the authorized owner and may require specialist review.',
    'Conclusion: search trustworthiness is evidence-led when source identity, indexed identity, freshness, transformed fields, permission outcome, and repair result are compared in a bounded cohort. The next step is a synthetic or masked reconciliation sample with ordinary and edge-state records. That gives an outsourced programmer a clear technical lane while keeping data governance and production authority with the client.', common
  ], sources: [sources.otel, sources.owasp, sources.nist, sources.github], related: ['outsourced-search-index-reconciliation-study'] },
];
