import type { ResearchPost } from './fleet-content';

const sources = {
  dora: ['DORA research', 'https://dora.dev/research/'] as const,
  nist: ['NIST Secure Software Development Framework', 'https://csrc.nist.gov/Projects/ssdf'] as const,
  github: ['GitHub pull request reviews', 'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'] as const,
  otel: ['OpenTelemetry documentation', 'https://opentelemetry.io/docs/'] as const,
  owasp: ['OWASP API Security', 'https://owasp.org/API-Security/'] as const,
  wcag: ['W3C WCAG 2.2', 'https://www.w3.org/TR/WCAG22/'] as const,
  google: ['Google Technical Writing', 'https://developers.google.com/tech-writing'] as const,
};

const boundary = 'This research is a bounded planning aid for teams working with outsourced programmers. It does not certify a product, establish a universal benchmark, or replace legal, privacy, security, accessibility, or release review. A company technical owner retains authority over production access, merges, releases, customer data, and residual risk.';

export const august21ResearchBatch: ReadonlyArray<ResearchPost> = [
  { slug:'outsourced-release-recovery-evidence-2026', route:'/research/outsourced-release-recovery-evidence-2026', datePublished:'2026-08-21', campaignDate:'2026-08-21', sourceDateField:'sourceDate', sourceDate:'2026-08-21', title:'Which evidence makes recovery from an outsourced software release credible?', excerpt:'A research study of release state, irreversible effects, and repeatable recovery evidence for delegated programming work.', topic:'Release recovery evidence', published:'2026-08-21', hero:'/research-heroes/2026-08-21/outsourced-release-recovery-evidence.png', body:[
    'Research question: which observations let a company decide whether an outsourced software release has a credible recovery path? A sentence in a ticket saying “rollback available” is not evidence. Recovery can be changed by schema migrations, queues, caches, configuration, scheduled work, third-party callbacks, and data written after the release. This study treats a release as a bounded comparison between an identified artifact, a known prior state, and checks another authorized operator can repeat.',
    'The evidence scope is a sample of release candidates from one application or work lane. It should include an ordinary code change, a feature-flagged change, a migration-bearing change, and a case where recovery is intentionally rejected. The unit is the release record, not the individual programmer. That distinction matters in outsourced work: a weak boundary between code, data, and operations is a system finding, not a fair basis for assigning personal blame.',
    'Methodology begins with an inventory of artifact identity, source revision, configuration assumptions, dependency versions, data changes, worker behavior, and external effects. The reviewer maps a proposed recovery action to a controlled rehearsal in an approved non-production environment. Every observation records a precondition, action, expected state, observed state, verification query, and human intervention. If an expert silently fixes a problem, the record marks that as a limitation instead of counting the rehearsal as ordinary reproducibility.',
    'DORA research describes delivery performance as a property of a system of work, while NIST SSDF emphasizes protected development and response readiness. Neither source proves a command is safe for every application. Their narrower contribution is methodological: recovery should be designed, protected, rehearsed, and observable. An outsourced programmer can prepare fixtures, comparison queries, scripts, and evidence; the company owner decides whether the evidence supports a release decision.',
    'The central analysis separates reversible behavior from forward repair. A code artifact may be restored while a destructive data transformation cannot be undone. A queue may keep processing messages against a reverted worker. A cache can repopulate from an incompatible database state. An external callback may already have created a side effect. Naming those boundaries gives a decision-maker more information than a binary label such as rollback-ready.',
    'Measures should compare planned recovery with observed recovery. Useful counts include releases with a named prior state, releases with a repeatable verification check, rehearsal failures by cause, unresolved irreversible steps, and time spent awaiting an owner decision. Report the cohort and denominator. A median recovery time cannot prove behavior under production load, and a short rehearsal misleads if it omits workers, permissions, data volume, or a representative user journey.',
    'Evidence becomes stronger when the study has a stopping rule. If a verification query disagrees with the expected state, the operator stops, captures the mismatch, and escalates. If a step requires privileged access, the record names that boundary without exposing credentials. If recovery requires forward migration, the record states the data it can touch and how it will be checked. This keeps implementation support precise while preserving release authority.',
    'Telemetry can connect an artifact to downstream behavior, but traces do not replace correctness checks. A recovery report should pair correlation identifiers with direct state comparisons, user-journey checks, and queue inspection where relevant. Pull-request review can preserve assumptions and evidence, but approval itself does not prove that an untested operational dependency will recover. Facts from the rehearsal must stay separate from analysis about likely risk.',
    'Limitations include provider behavior, load, clock differences, hidden data dependencies, retention policies, and recovery paths that cannot safely be rehearsed. One application and one work lane cannot establish a market benchmark. The study also cannot decide whether a company should continue forward, disable a feature, restore an artifact, or pause. That is a risk decision for the authorized owner after the evidence is reviewed.',
    'Conclusion: credible recovery evidence names the release and prior state, exercises the proposed action, checks data and external boundaries, records failed observations, and distinguishes reversible steps from forward repair. The next bounded assignment for an outsourced programmer is to prepare a masked fixture, rehearsal script, comparison queries, and an evidence record. Final release approval, production credentials, customer impact, and residual risk remain with the company owner.','The reviewer should receive the evidence without the author present and identify the tested cohort, the expected result, the observed result, and the next owner decision. If that handoff fails, record the ambiguity as a finding rather than treating informal rescue as proof of reproducibility. This matters in distributed outsourced programming because implementation knowledge and approval authority often belong to different people.',
    'Negative cases should remain visible. A failed fixture, missing permission, unexpected response, stale record, focus defect, or ambiguous instruction may be more informative than a clean happy path. Record containment, correction, retest scope, and what remains unverified. Do not turn a repaired sample into a universal claim; state the environment and evidence boundary each time.',
    'The resulting record should be easy to compare later. Keep the route or task identity, source revision, fixture version, date, reviewer, and exclusions together. A later reviewer can then distinguish a changed system from a changed test. That discipline gives an outsourced programmer a clear technical lane while keeping policy, release, customer impact, and residual-risk decisions with the company owner.','For this study, a pass means only that the named observation held under the stated conditions. It does not establish behavior for an untested tenant, browser, client, workload, dependency, or future revision. The limitation is useful because it identifies the next bounded question and prevents a polished article from becoming an unsupported promise.','Any follow-up should preserve the same evidence vocabulary and record why its scope is wider or narrower. That continuity makes daily research useful to a real software team: the next person can extend a bounded finding without silently changing its meaning or presenting a local observation as a company-wide result.', boundary
  ], sources:[sources.dora,sources.nist,sources.otel,sources.github] },
  { slug:'outsourced-api-compatibility-boundary-2026', route:'/research/outsourced-api-compatibility-boundary-2026', datePublished:'2026-08-21', campaignDate:'2026-08-21', sourceDateField:'sourceDate', sourceDate:'2026-08-21', title:'Where does an outsourced API change cross the compatibility boundary?', excerpt:'A source-led study of consumer expectations, negative behavior, and release sequencing for delegated API changes.', topic:'API compatibility boundaries', published:'2026-08-21', hero:'/research-heroes/2026-08-21/outsourced-api-compatibility-boundary.png', body:[
    'Research question: when does an API change move from an implementation detail into a compatibility decision for the company that owns the application? “Backward compatible” is too broad unless the study names consumers, versions, fields, status codes, authentication states, error handling, and timing assumptions. This research examines a bounded change prepared by an outsourced programmer and asks what evidence distinguishes a safe extension from an accidental contract break.',
    'The evidence scope should identify every known consumer class: browser code, mobile clients, scheduled jobs, partner integrations, internal scripts, and support tools. It should state the observation period and the version or route under review. Unknown consumers are not proof of safety; they are an uncertainty to surface. The study uses a representative contract fixture, normal and unauthorized requests, malformed input, missing fields, extra fields, pagination boundaries, and provider failure responses.',
    'Methodology starts with the current contract as observed by consumers, not only the server implementation. Record request shape, response fields, nullability, ordering, status code, error body, authentication requirement, and rate or timeout behavior where those are part of the interface. Compare the proposed response against that baseline. Each difference is classified as additive, tolerated, ambiguous, or breaking. The classification is a fact about the comparison; its release risk is an analysis that needs owner judgment.',
    'OWASP API Security guidance supports attention to authorization and input boundaries, while NIST SSDF supports protected development and verification. GitHub review guidance contributes a durable place to inspect the diff and evidence. These sources do not select a versioning strategy or prove that a particular client exists. They support a narrower conclusion: compatibility decisions need observable contracts, negative cases, and named assumptions rather than confidence based on a successful happy-path request.',
    'An additive field can still break a consumer that performs strict object comparison. A changed default can alter billing, filtering, or notification behavior without changing the schema. A new authorization rule can return a different status code and expose a previously hidden distinction. An error response that loses a machine-readable code may be more damaging than a renamed success field. The report therefore treats behavior, not just type declarations, as part of the API boundary.',
    'Testing should include a before-and-after comparison for each consumer class in scope. Preserve fixtures for valid, unauthorized, expired, malformed, empty, oversized, and concurrent requests. Check whether retry behavior remains safe after a timeout. For pagination, compare cursor meaning and stable ordering, not only the number of records. For asynchronous endpoints, compare event identity, delivery timing, and duplicate handling. Evidence should include the exact environment and fixture version.',
    'An outsourced programmer can extract a contract, build a compatibility matrix, add focused tests, and prepare a migration note. The company technical owner decides whether a consumer is supported, whether a deprecation window is required, and whether a release can proceed. Secrets, partner credentials, production data, and commercial commitments should remain outside the ordinary implementation lane. This role boundary reduces pressure to hide unknown consumers behind an optimistic pass result.',
    'The analysis should report facts separately from inference. “The old client accepted the new field” is an observation. “All clients will continue to work” is an unsupported generalization unless the consumer population and behavior were exhaustively established. Useful measures include cases by compatibility class, clients with unverified assumptions, contract tests that fail before the change, migration steps completed, and unresolved owner decisions. Report denominators so a pass rate cannot conceal a small but important client.',
    'Limitations include undocumented consumers, generated clients with different validation rules, proxies that rewrite behavior, network failures, authorization policy outside the test fixture, and production traffic patterns not represented in staging. A compatibility study is not a security assessment or a guarantee against every integration failure. If the change touches personal data, regulated behavior, or a material customer workflow, specialist review may be necessary before release.',
    'Conclusion: an API compatibility boundary is crossed when a change can alter an identified consumer’s accepted input, observed output, authorization outcome, error handling, or timing assumption. The evidence-led next step is a versioned fixture matrix with negative cases and a consumer inventory, followed by an explicit owner decision on migration and release. The outsourced programmer can prepare the technical record; the company retains contract authority and residual risk.','The reviewer should receive the evidence without the author present and identify the tested cohort, the expected result, the observed result, and the next owner decision. If that handoff fails, record the ambiguity as a finding rather than treating informal rescue as proof of reproducibility. This matters in distributed outsourced programming because implementation knowledge and approval authority often belong to different people.',
    'Negative cases should remain visible. A failed fixture, missing permission, unexpected response, stale record, focus defect, or ambiguous instruction may be more informative than a clean happy path. Record containment, correction, retest scope, and what remains unverified. Do not turn a repaired sample into a universal claim; state the environment and evidence boundary each time.',
    'The resulting record should be easy to compare later. Keep the route or task identity, source revision, fixture version, date, reviewer, and exclusions together. A later reviewer can then distinguish a changed system from a changed test. That discipline gives an outsourced programmer a clear technical lane while keeping policy, release, customer impact, and residual-risk decisions with the company owner.','For this study, a pass means only that the named observation held under the stated conditions. It does not establish behavior for an untested tenant, browser, client, workload, dependency, or future revision. The limitation is useful because it identifies the next bounded question and prevents a polished article from becoming an unsupported promise.','Any follow-up should preserve the same evidence vocabulary and record why its scope is wider or narrower. That continuity makes daily research useful to a real software team: the next person can extend a bounded finding without silently changing its meaning or presenting a local observation as a company-wide result.', boundary
  ], sources:[sources.owasp,sources.nist,sources.github,sources.dora] },
  { slug:'outsourced-search-permission-freshness-2026', route:'/research/outsourced-search-permission-freshness-2026', datePublished:'2026-08-21', campaignDate:'2026-08-21', sourceDateField:'sourceDate', sourceDate:'2026-08-21', title:'How should an outsourced team test search freshness without missing permission defects?', excerpt:'A research method for reconciling source records, indexed state, freshness windows, and access boundaries.', topic:'Search freshness and permissions', published:'2026-08-21', hero:'/research-heroes/2026-08-21/outsourced-search-permission-freshness.png', body:[
    'Research question: how can a company evaluate whether an outsourced search change preserves freshness and permission boundaries at the same time? Matching document counts are weak evidence. A record can be missing, stale, duplicated, malformed, visible to the wrong tenant, or searchable after deletion. This study compares source identity, indexed identity, version, transformed fields, freshness, and authorization for one bounded cohort instead of treating search quality as a single score.',
    'The scope names the authoritative source, index collection, mapping, tenant or role model, propagation window, synchronization period, and repair mechanism. Fixtures include creation, update, deletion, empty text, special characters, permission changes, delayed events, and duplicate delivery. Use synthetic or approved masked records. Never move live customer data into an unmanaged workspace or treat a public result as evidence that access control is correct.',
    'Methodology joins stable source identities to indexed identities before comparing fields. Each difference is classified as missing, stale, unauthorized, malformed, duplicate, or intentionally excluded. The reviewer performs a bounded repair and repeats the comparison. The before-and-after record includes the input cohort, expected result, observed result, repair action, unresolved cases, and whether a second run creates duplicates or repeats a side effect. This makes the repair itself part of the evidence.',
    'OpenTelemetry documentation supports tracing events across services, while OWASP API Security guidance highlights authorization at data boundaries. NIST SSDF contributes a protected-development perspective. These sources do not prescribe an indexing product or algorithm. They support a narrower inference: reconciliation should be traceable from source event to indexed observation, and permission filtering should be measured as correctness rather than postponed to operations.',
    'Analysis separates eventual consistency from data loss. A newly created record absent inside the documented propagation window may be expected; the same absence after the window needs another interpretation. A stale deletion or unauthorized result is not harmless eventual consistency. Version or timestamp evidence helps distinguish a delayed update from an older event overwriting newer state. The report should keep freshness and authorization as separate findings because their urgency can differ.',
    'The sample should be stratified rather than reduced to one random total. Include recent records, edited records, deleted records, records with no searchable text, permission-boundary records, and records affected by late events. Report source records sampled, indexed matches, age distribution, field mismatches, duplicate identities, and permission findings. One exposed record may be more urgent than many harmless freshness gaps, so counts should not hide severity.',
    'Repair evidence matters because a correct initial comparison does not prove recovery. Run an incremental repair twice and check for duplicate documents or repeated downstream effects. If a rebuild is used, test deletions, permissions, ordering, and transformed fields, not only final count. If stable identifiers must be masked, preserve a safe correlation token so an authorized reviewer can reproduce a mismatch without seeing sensitive values.',
    'For outsourced programming work, the programmer can prepare fixtures, mapping checks, comparison queries, traces, and a repair proposal. The company owner retains authority over source data, tenant policy, retention, indexing configuration, and production repair. The evidence should state which values were excluded, which source is authoritative, and which cases could not be investigated safely. That boundary is essential when a technical fix can affect access to customer information.',
    'Limitations include provider tokenization, delayed queues, concurrent updates, hidden identifiers, permission changes that emit no event, and staging data that does not resemble production tenants. A bounded sample cannot prove every load or content shape. A search result can also look correct while ranking, localization, or field transformation remains wrong. Those untested dimensions belong in the limitation statement rather than being silently inferred from count agreement.',
    'Conclusion: search quality is evidence-led when a cohort compares source identity, indexed identity, freshness, fields, permissions, and repair outcomes. The next bounded assignment is a masked reconciliation sample with ordinary and edge-state records, separate freshness and authorization reporting, and a repeatable repair check. That gives an outsourced programmer a precise engineering lane while preserving data governance, production authority, and the owner’s decision about residual risk.','The reviewer should receive the evidence without the author present and identify the tested cohort, the expected result, the observed result, and the next owner decision. If that handoff fails, record the ambiguity as a finding rather than treating informal rescue as proof of reproducibility. This matters in distributed outsourced programming because implementation knowledge and approval authority often belong to different people.',
    'Negative cases should remain visible. A failed fixture, missing permission, unexpected response, stale record, focus defect, or ambiguous instruction may be more informative than a clean happy path. Record containment, correction, retest scope, and what remains unverified. Do not turn a repaired sample into a universal claim; state the environment and evidence boundary each time.',
    'The resulting record should be easy to compare later. Keep the route or task identity, source revision, fixture version, date, reviewer, and exclusions together. A later reviewer can then distinguish a changed system from a changed test. That discipline gives an outsourced programmer a clear technical lane while keeping policy, release, customer impact, and residual-risk decisions with the company owner.','For this study, a pass means only that the named observation held under the stated conditions. It does not establish behavior for an untested tenant, browser, client, workload, dependency, or future revision. The limitation is useful because it identifies the next bounded question and prevents a polished article from becoming an unsupported promise.','Any follow-up should preserve the same evidence vocabulary and record why its scope is wider or narrower. That continuity makes daily research useful to a real software team: the next person can extend a bounded finding without silently changing its meaning or presenting a local observation as a company-wide result.', boundary
  ], sources:[sources.otel,sources.owasp,sources.nist,sources.github] },
  { slug:'outsourced-keyboard-navigation-evidence-2026', route:'/research/outsourced-keyboard-navigation-evidence-2026', datePublished:'2026-08-21', campaignDate:'2026-08-21', sourceDateField:'sourceDate', sourceDate:'2026-08-21', title:'What evidence shows an outsourced web change preserves keyboard navigation?', excerpt:'A research study of focus order, recovery, dynamic states, and bounded accessibility evidence in delegated web work.', topic:'Keyboard navigation evidence', published:'2026-08-21', hero:'/research-heroes/2026-08-21/outsourced-keyboard-navigation-evidence.png', body:[
    'Research question: what observations show that an outsourced web change preserves a usable keyboard journey rather than merely displaying a visible focus outline? Keyboard operation includes entry, order, visibility, activation, modal behavior, error recovery, and return to context. A route can pass a short tab test while trapping focus, skipping a dynamic control, or leaving a user lost after an asynchronous update. This study defines evidence around a representative journey and its negative states.',
    'The evidence scope names the route, supported browser and viewport, interaction journey, dynamic components, expected focus destination, and exclusions. Include navigation, forms, dialogs, menus, validation errors, loading states, disabled controls, and a return path after completion or cancellation. The study does not claim that one browser sample establishes legal conformance or covers every assistive technology. It does establish what was observed and which combinations remain untested.',
    'Methodology records the starting focus, each keyboard action, visible focus indicator, resulting context, announcement or state change where relevant, and recovery action. Test the ordinary path and at least one interruption: an error, delayed response, dialog close, or route transition. A screenshot can support a visual claim, but it cannot prove sequence or operability. A short recording, event log, and written observation are stronger when another reviewer needs to reproduce the result.',
    'WCAG 2.2 provides normative success criteria for keyboard operability and focus-related behavior. Google Engineering Practices supports reviewable change evidence, while NIST SSDF supports verification in protected development. These sources do not prove that a manual sample satisfies every accessibility obligation. Their narrower contribution is to frame accessibility evidence as observable behavior with stated scope, not as a claim inferred from a component library or a single automated scan.',
    'Focus order is a design property as well as a DOM property. A visually logical layout can produce a confusing sequence when CSS order, portals, hidden controls, or conditional rendering intervene. A dialog may receive focus correctly but return it to a destroyed trigger. A custom menu may expose items visually while leaving arrow-key behavior undefined. The study should describe the exact state transition and avoid collapsing materially different controls into one pass label.',
    'The report should distinguish facts from interpretation. “Focus moved to the first invalid field after submit” is an observation. “The form is accessible” is a broader conclusion that the sample cannot support alone. Useful measures include journeys tested, states covered, focus failures by cause, controls requiring specialist follow-up, and cases where browser or assistive technology differences changed the result. Report the tested cohort and excluded states so the evidence remains bounded.',
    'An outsourced programmer can reproduce the journey, repair component behavior, add focused tests, and document browser results. The company owner decides product priority, user impact, release timing, and whether specialist accessibility review is required. Avoid requesting unnecessary personal data in fixtures. Keep production credentials and customer information outside the ordinary test lane. Clear ownership lets the programmer address a concrete defect without implying authority over conformance or policy.',
    'Automated checks are useful for locating missing names, contrast issues, or obvious structure problems, but they do not replace keyboard observation. Manual evidence should include edge states that automation cannot infer: focus after a validation error, focus when a dialog is dismissed, and focus while content loads. If a component depends on timing, record the delay and the expected result. If a test is skipped, name the reason and what would be needed to close the gap.',
    'Limitations include browser differences, assistive-technology combinations, localization, zoom, dynamic content, custom widgets, and journeys not represented in the fixture. A bounded manual study cannot establish universal accessibility or legal compliance. It can still reveal a specific regression and provide a responsible next assignment. Facts should remain available to a reviewer who was not present during testing, rather than relying on an informal assurance that “keyboard works.”',
    'Conclusion: credible keyboard-navigation evidence follows a named journey through ordinary and interrupted states, records focus and context at each step, separates automation from manual observation, and discloses coverage limits. The next bounded assignment is a route-specific keyboard evidence record plus a focused repair or regression test. The outsourced programmer prepares and verifies the technical change; the company owner retains release, accessibility, and residual-risk decisions.','The reviewer should receive the evidence without the author present and identify the tested cohort, the expected result, the observed result, and the next owner decision. If that handoff fails, record the ambiguity as a finding rather than treating informal rescue as proof of reproducibility. This matters in distributed outsourced programming because implementation knowledge and approval authority often belong to different people.',
    'Negative cases should remain visible. A failed fixture, missing permission, unexpected response, stale record, focus defect, or ambiguous instruction may be more informative than a clean happy path. Record containment, correction, retest scope, and what remains unverified. Do not turn a repaired sample into a universal claim; state the environment and evidence boundary each time.',
    'The resulting record should be easy to compare later. Keep the route or task identity, source revision, fixture version, date, reviewer, and exclusions together. A later reviewer can then distinguish a changed system from a changed test. That discipline gives an outsourced programmer a clear technical lane while keeping policy, release, customer impact, and residual-risk decisions with the company owner.','For this study, a pass means only that the named observation held under the stated conditions. It does not establish behavior for an untested tenant, browser, client, workload, dependency, or future revision. The limitation is useful because it identifies the next bounded question and prevents a polished article from becoming an unsupported promise.','Any follow-up should preserve the same evidence vocabulary and record why its scope is wider or narrower. That continuity makes daily research useful to a real software team: the next person can extend a bounded finding without silently changing its meaning or presenting a local observation as a company-wide result.', boundary
  ], sources:[sources.wcag,sources.google,sources.nist,sources.github] },
  { slug:'outsourced-documentation-reproducibility-2026', route:'/research/outsourced-documentation-reproducibility-2026', datePublished:'2026-08-21', campaignDate:'2026-08-21', sourceDateField:'sourceDate', sourceDate:'2026-08-21', title:'How can an outsourced team measure whether technical documentation is reproducible?', excerpt:'Evidence-led research on whether another authorized reader can complete a documented engineering task without hidden assumptions.', topic:'Documentation reproducibility', published:'2026-08-21', hero:'/research-heroes/2026-08-21/outsourced-documentation-reproducibility.png', body:[
    'Research question: when does technical documentation become usable evidence rather than a polished explanation that only its author can follow? In outsourced programming, a handoff often crosses time zones, repositories, environments, and role boundaries. The relevant test is not word count or page views. It is whether another authorized reader can perform a bounded task, observe the expected result, identify a deviation, and know who owns the next decision without receiving undocumented rescue from the author.',
    'The evidence scope names the task, reader profile, environment, prerequisites, permissions, inputs, expected output, and safety constraints. Choose recurring work such as running a focused test, understanding a route, reproducing a bug, or reviewing a recovery check. Exclude secrets and sensitive data. The study should state whether the reader is expected to work in a local, preview, or other approved environment, because a document cannot be judged independently of the access and tools it assumes.',
    'Methodology uses an independent reader who did not write the document. The reader follows the instructions while an observer records blocked steps, ambiguous terms, missing prerequisites, deviations, and time spent seeking clarification. The result is compared with the expected state. A successful run is not enough if the reader was coached through a hidden step. Record interventions and classify them as documentation defects, environment blockers, or legitimate owner decisions.',
    'Google Technical Writing emphasizes audience, scope, and usable instructions. NIST SSDF highlights maintaining development and security information needed for trustworthy software practices, while GitHub review records provide a durable place to connect instructions with a change. These sources do not prescribe a house style or prove a document remains current. They support a narrower finding: documentation quality is better evaluated through an observed task and a stated audience than through prose polish alone.',
    'Reproducibility has multiple dimensions. A reader may reach the expected output but misunderstand why it matters. A test may pass while using a stale dependency or an unsafe fixture. A recovery note may identify a command but omit data implications. The record should therefore include prerequisites, action, expected result, observed result, interpretation, and escalation path. It should also state what the instructions intentionally do not cover so future readers do not infer universal scope.',
    'A useful study compares documents by task criticality and verification age. Current instructions for release, access removal, data handling, and recovery may matter more than a large archive of low-risk notes. Report tasks attempted, completed without intervention, blocked by company-controlled access, blocked by ambiguous wording, and requiring a substantive update. Do not use reader speed as a universal performance benchmark; familiarity, environment setup, and task complexity can change the result.',
    'For outsourced programming, the contributor can prepare a task record, update instructions, add reproducible commands, capture expected output, and note unresolved assumptions. The company owner retains authority over secrets, production data, release commands, policy, and exceptions. A document should never ask a reader to paste credentials or copy customer data into a broad workspace. The safety boundary is part of reproducibility because unsafe steps are not acceptable evidence of operational readiness.',
    'Versioning matters when a route, dependency, schema, or permission model changes. Link the document to the relevant source revision or ticket, record the verification date, and identify the owner of the next review. A stale document can remain grammatically excellent while becoming operationally wrong. The study should test one negative path, such as a missing permission or changed command, and show whether the document explains recovery instead of leaving the reader to guess.',
    'Limitations include small reader samples, environment differences, tacit knowledge, confidential setup, and tasks whose correct result depends on an owner decision. One reader cannot represent every audience. A successful rehearsal cannot prove that every future code change will preserve the instructions. Those limits do not weaken the core evidence; they keep its conclusion proportional and identify the next reader or environment that would add useful information.',
    'Conclusion: documentation is reproducible when an authorized reader can perform a named task in a stated environment, reach an expected result, surface deviations, and follow a safe escalation path without hidden author intervention. The next bounded assignment is an independent read-through with captured observations and a dated source-linked update. An outsourced programmer can improve the record; the company owner remains responsible for access, policy, production authority, and acceptance of operational risk.','The reviewer should receive the evidence without the author present and identify the tested cohort, the expected result, the observed result, and the next owner decision. If that handoff fails, record the ambiguity as a finding rather than treating informal rescue as proof of reproducibility. This matters in distributed outsourced programming because implementation knowledge and approval authority often belong to different people.',
    'Negative cases should remain visible. A failed fixture, missing permission, unexpected response, stale record, focus defect, or ambiguous instruction may be more informative than a clean happy path. Record containment, correction, retest scope, and what remains unverified. Do not turn a repaired sample into a universal claim; state the environment and evidence boundary each time.',
    'The resulting record should be easy to compare later. Keep the route or task identity, source revision, fixture version, date, reviewer, and exclusions together. A later reviewer can then distinguish a changed system from a changed test. That discipline gives an outsourced programmer a clear technical lane while keeping policy, release, customer impact, and residual-risk decisions with the company owner.','For this study, a pass means only that the named observation held under the stated conditions. It does not establish behavior for an untested tenant, browser, client, workload, dependency, or future revision. The limitation is useful because it identifies the next bounded question and prevents a polished article from becoming an unsupported promise.','Any follow-up should preserve the same evidence vocabulary and record why its scope is wider or narrower. That continuity makes daily research useful to a real software team: the next person can extend a bounded finding without silently changing its meaning or presenting a local observation as a company-wide result.', boundary
  ], sources:[sources.google,sources.nist,sources.github,sources.dora] },
];
