import type { BlogDetail } from './data';

type Article = {
  published: string;
  slug: string;
  title: string;
  excerpt: string;
  minutes: number;
  focus: string;
  sections: Array<[string, string]>;
};

const articles: Article[] = [
  { slug: 'outsource-rollback-plan-review', published: '2026-08-24', title: 'Outsource rollback-plan review before a risky code change', excerpt: 'Turn rollback language into a tested boundary with named triggers, reversible steps, and clear owner decisions.', minutes: 11, focus: 'rollback planning', sections: [
    ['Start with the failure you are trying to contain', 'A rollback plan is useful only when it names the change, the signal that would make it unsafe, and the state a team expects after reversal. For outsourced programming work, the first assignment should be to reconstruct the change boundary from the ticket, pull request, migration notes, and dependent services. “Revert if needed” is not an acceptance rule. The programmer should identify whether a code revert restores behavior, whether a data change survives it, and which user-visible symptoms would trigger a pause.'],
    ['Separate code reversal from data recovery', 'A code rollback and a data recovery action are different operations. A new field may be backward compatible while a destructive transformation is not; a feature can be hidden while records already changed remain. Ask for a table that names code, configuration, schema, queued work, caches, and external side effects separately. This prevents a technically clean revert from being presented as a complete recovery when the underlying state needs an owner-approved procedure.'],
    ['Choose observable stop signals', 'The plan should use signals a reviewer can actually inspect: a failed smoke check, an unexpected authorization result, a queue growth threshold, a migration lock, or a known error response. Avoid invented universal thresholds. The company owner decides what level of risk is acceptable, while the programmer can prepare a safe fixture, a dashboard link, or a command that makes the signal reproducible without touching customer data.'],
    ['Practice the smallest useful recovery', 'A rehearsal should exercise the narrowest meaningful path. Use a disposable branch, representative fixtures, and a controlled dependency response. Record the starting revision, commands, expected state, observed state, elapsed steps, and anything that required manual judgment. A rehearsal cannot prove every production condition, but it can expose missing permissions, undocumented prerequisites, or a recovery step that silently depends on the person who originally wrote the change.'],
    ['Review partial failure', 'Most rollback plans describe a clean stop and ignore work already in flight. Check an interrupted deployment artifact, a queued job, a cache containing the new shape, and a client that has already received a changed response when those cases apply. The programmer should document the first inconsistent state and the smallest safe follow-up. Do not ask them to invent customer communication, incident severity, or data policy.'],
    ['Keep review evidence attached to the change', 'The pull request should link the recovery matrix, fixture setup, test output, and open questions. A reviewer needs to know which steps ran, which were simulated, and which require production authority. Include the exact revision that was rehearsed so a later code change does not inherit a stale claim. Good evidence is specific enough for another programmer to repeat and bounded enough that it does not imply access that was never granted.'],
    ['Make ownership explicit', 'Recovery work crosses role boundaries. An outsourced programmer can inspect dependencies, write a script for a sandbox, improve a check, and explain technical consequences. The company keeps approval for release timing, customer impact, security exceptions, live data changes, and communication. Put those boundaries in the ticket. Escalation is a successful outcome when the plan reveals a decision the implementer is not authorized to make.'],
    ['Close with a decision-ready handoff', 'End with the change identity, tested recovery path, observed result, untested condition, stop signal, and named decision owner. State whether the result supports a merge, requires a follow-up, or is blocked by missing evidence. A rollback review succeeds when it reduces ambiguity before work begins; it does not need to promise that every failure can be reversed.']
  ] },
  { slug: 'outsource-application-log-redaction-review', published: '2026-08-24', title: 'Outsource application logging redaction review with safe fixtures', excerpt: 'Find sensitive values in logs, verify useful context remains, and keep privacy decisions with the application owner.', minutes: 10, focus: 'logging redaction', sections: [
    ['Define what must never appear', 'Logging review starts with a data inventory, not a grep command. Name credentials, session tokens, personal fields, payment references, internal identifiers, and request bodies that the application must not emit. Then distinguish a prohibited value from a safe diagnostic surrogate. An outsourced programmer can trace log statements and prepare synthetic fixtures; the company owner decides the policy and retention boundary.'],
    ['Trace values across the request path', 'A value can enter through a header, form, exception, queue payload, or third-party response and appear later in a different logger. Follow one controlled fixture through validation, persistence, retry, and error handling. Record the first point where the value becomes unsafe and whether a wrapper, serializer, or framework adds it automatically. A clean application log does not prove that a worker or provider log has the same behavior.'],
    ['Preserve diagnostic meaning', 'Redaction that removes every useful clue can slow recovery. Compare a raw synthetic token with a stable hash, type label, length, or last-four surrogate when those choices are approved. Test whether a reviewer can still connect related events without recovering the original secret. The programmer should show the tradeoff and propose a narrow implementation; privacy, security, and retention decisions stay with the owner.'],
    ['Exercise failures deliberately', 'Sensitive values often leak in validation errors, stack traces, timeout messages, and rejected authentication paths rather than successful requests. Build fixtures for malformed input, dependency failure, authorization denial, and retry. Capture only synthetic values and inspect structured fields as well as rendered text. If an exception includes a full request or library object, record the field path and stop before expanding access.'],
    ['Check structured and text logs', 'JSON fields, console strings, tracing attributes, and metrics labels may have different redaction paths. Compare the same fixture in each supported output. Pay attention to field names that imply safety while holding an entire object. Also check correlation identifiers: they should support diagnosis without becoming reusable credentials or exposing a person’s identity beyond the approved purpose.'],
    ['Test the boundary after changes', 'A redaction fix needs a regression fixture that would fail if the sensitive field returns. Keep the fixture local to the relevant handler and label its synthetic values clearly. Run the check at the narrowest layer that caught the issue, then verify a higher-level error path when the logger is configured differently there. Do not claim coverage for sinks or hosted tooling that were not available.'],
    ['Document retention and access questions', 'The review should state where evidence may be stored, who can view it, and how long it should remain. An outsourced programmer can remove values from source logs and describe observed output, but should not copy sensitive production records into a ticket. Escalate missing retention rules, unclear vendor access, or an incident indication to the named owner rather than quietly normalizing it.'],
    ['Deliver the redaction handoff', 'Include the field inventory, fixture inputs, output samples with safe values, source locations, tests, and unresolved policy questions. Say whether the change removes a confirmed leak, improves a suspected path, or remains unverified in another sink. The useful result is a reviewable boundary between diagnostic context and protected data, not a blanket claim that all logs are safe.']
  ] },
  { slug: 'outsource-cicd-permission-review', published: '2026-08-24', title: 'Outsource CI/CD permission review without handing over release authority', excerpt: 'Map workflow permissions, artifact access, and approval boundaries while keeping production release decisions internal.', minutes: 11, focus: 'CI/CD permissions', sections: [
    ['Map the workflow as identities and actions', 'A workflow file is only one part of a CI/CD permission boundary. List the identity that starts each job, the token scopes it receives, the repositories and artifacts it can read, the environments it can target, and the actions it can perform. An outsourced programmer can assemble this map from repository configuration and safe test runs; a company owner approves any permission change.'],
    ['Distinguish build from promotion', 'Build, test, artifact storage, staging promotion, and production release are different capabilities even when one workflow contains them. Review whether a test job can publish an artifact, whether an artifact can be replaced, and whether a staging credential can reach production. Keeping these stages separate makes least privilege concrete and prevents a convenience token from becoming an undocumented release key.'],
    ['Inspect pull request conditions', 'Check which events run workflows, whether untrusted code can influence a privileged job, and whether approval is required before a protected environment. Use a harmless branch and synthetic artifact to observe the path. The programmer should report the trigger, actor, permission set, and resulting action; they should not approve a change that weakens branch protection or bypasses the technical owner.'],
    ['Review secrets without exposing them', 'Permission review does not require printing secret values. Record secret names, scopes, environments, and the step that consumes each one. Check whether logs mask them and whether forks or pull requests from untrusted sources can reach the step. If a secret is broader than the task requires, describe the excess and route the decision to the security or platform owner.'],
    ['Test artifact identity', 'A release workflow should make it possible to connect a promoted artifact to its source revision and checks. Use a safe artifact and verify its name, digest or equivalent identity, producer job, and approval step. An outsourced programmer can add a trace or assertion, but the company decides which evidence is sufficient for release and which environments are protected.'],
    ['Look for inherited permissions', 'Reusable workflows, marketplace actions, organization defaults, and runner configuration can expand access outside the visible job. Trace those dependencies and record what was inspected. Do not treat a popular action or a successful run as proof of trust. Pin or review dependencies only within the approved scope, and escalate an organization-level setting that cannot be changed safely in the repository.'],
    ['Make denial paths visible', 'A permission review is stronger when it proves that an unapproved actor cannot promote, read a protected secret, or replace a release artifact. Use a test environment and deliberately denied identity where possible. Record the denial without attempting to defeat it. A failed permission check is evidence of the boundary, not an invitation to request broader access.'],
    ['Close with a release boundary record', 'The handoff should contain the workflow map, trigger cases, permission observations, artifact identity, secret inventory without values, denied actions, and owner decisions. State what was tested and what depends on organization settings. The programmer supplies precise evidence; the company retains merge, environment, release, and emergency-access authority.']
  ] },
  { slug: 'outsource-cache-key-review', published: '2026-08-24', title: 'Outsource cache-key review before stale or private data can spread', excerpt: 'Inspect cache identity, invalidation, permissions, and fallback behavior using controlled records and explicit ownership.', minutes: 10, focus: 'cache keys', sections: [
    ['Treat a cache key as an identity decision', 'A cache key decides which requests share a stored result. Review the route, user or tenant boundary, locale, feature state, and content revision that affect the response. An outsourced programmer should write the key dimensions down before changing code. The technical owner decides which variation is required; the reviewer verifies that the key does not accidentally merge private or incompatible results.'],
    ['Build contrasting fixtures', 'Use synthetic identities that differ in permission, tenant, locale, and content version. Add a public response beside a private response and vary one dimension at a time. The expected result should say whether sharing is safe, whether a miss is acceptable, and what the user sees after a change. Contrasts reveal cache collisions that a single happy-path request cannot show.'],
    ['Inspect population and lookup separately', 'A key can be correct at lookup but wrong when a response is stored, or correct for a page while an API helper uses another convention. Trace both paths, including headers, query parameters, server components, background revalidation, and client state where relevant. Record the first mismatch and avoid assuming that a cache library’s default matches the application’s privacy policy.'],
    ['Check invalidation timing', 'Freshness is not one number. Identify the event that should invalidate or revalidate the result, the observed delay, and what happens during the gap. Exercise an edit, permission change, deletion, and failed dependency where applicable. Keep customer-facing freshness promises with the owner; the programmer reports the controlled observation and the remaining uncertainty.'],
    ['Exercise fallback and errors', 'A cache miss, stale response, malformed entry, and unavailable origin can lead to different user outcomes. Use safe fixtures to see whether the application serves an honest fallback, retries safely, or exposes an earlier user’s data. Never use real private records to test a suspected collision. Stop and escalate if the fixture crosses an authorization boundary.'],
    ['Review serialization and version changes', 'Changes to field names, formatting, locale, or object shape can make old entries misleading even when the key string is unchanged. Compare serialized output across the change and decide whether a namespace or version marker is needed. The programmer can prepare a compatibility check; migration and purge timing require owner approval.'],
    ['Make observability useful', 'Cache hit and miss counts are helpful only when paired with the route, key class, and outcome being measured. Avoid logging raw keys if they contain identifiers. Add a safe category or digest when approved, then compare the observed category with the expected fixture. A high hit rate is not success if the wrong users share the result.'],
    ['Deliver a cache decision record', 'Include the key dimensions, fixtures, expected and observed responses, invalidation events, fallback behavior, serialization notes, and untested environments. Name whether the review found a collision risk, a freshness gap, or a preserved boundary. The handoff should let the owner approve one narrow change without turning cache cleanup into an unbounded architecture rewrite.']
  ] },
  { slug: 'outsource-api-pagination-review', published: '2026-08-24', title: 'Outsource API pagination review with stable ordering and boundary cases', excerpt: 'Verify cursors, page boundaries, totals, filtering, and client recovery against deterministic fixtures.', minutes: 10, focus: 'API pagination', sections: [
    ['Define the promise of a page', 'Pagination is a contract about identity, order, continuation, and omission. State whether the API uses a cursor, offset, page number, or time window, and what a client may rely on when records change between requests. An outsourced programmer can turn that promise into fixtures and assertions; the API owner decides compatibility and ordering policy.'],
    ['Use fixtures that expose ties', 'Create records with duplicate sort values, missing optional fields, equal timestamps, and more items than one page. Give each a stable synthetic identifier. A unique sort key or documented tie-breaker should make the next page deterministic. Without ties, a test can pass while real updates cause duplicates or skipped records.'],
    ['Walk every boundary', 'Check empty results, one item, exactly one page, one item over the boundary, a final page, an invalid cursor, and a cursor from a different filter. Record response fields, links, continuation behavior, and error meaning. Do not broaden the task to redesign pagination when a fixture exposes an existing ambiguity; state the decision needed.'],
    ['Change the collection between requests', 'A useful review asks what happens when an item is inserted, deleted, or edited after page one. Cursor approaches and offset approaches have different failure modes. Use a controlled sequence and compare the returned identities with the approved expectation. The result is evidence about the tested strategy, not a promise that every concurrent write is invisible.'],
    ['Keep filters attached to the cursor', 'A continuation token should not silently continue a different filter, tenant, or sort. Test reuse after changing each relevant query dimension and inspect whether the server rejects it or returns a misleading page. Use synthetic identities and never probe another tenant. Permission and compatibility rules remain with the service owner.'],
    ['Follow the client through recovery', 'Inspect how the consuming interface handles a missing next page, expired cursor, duplicate item, and server error. A technically valid response can still produce an infinite spinner or repeated records in the client. Record the first layer where meaning changes and separate server corrections from client corrections in the handoff.'],
    ['Measure totals honestly', 'Totals may be exact, estimated, omitted, or stale. Identify which one the API returns and whether the client treats it as authoritative. Use a fixture where the collection changes during traversal to reveal the assumption. The programmer can document observed behavior; the product owner decides how the interface should describe uncertainty.'],
    ['Leave a pagination matrix', 'The final record should link the fixture, sort rule, filter, page sequence, mutation sequence, response observations, client behavior, and untested cases. A reviewer should see whether the change preserves the contract, requires a migration, or is blocked on a product decision. Keep release approval and API policy with the company owner.']
  ] },
  { slug: 'outsource-frontend-error-recovery-review', published: '2026-08-24', title: 'Outsource frontend error-recovery review for actionable failure states', excerpt: 'Check loading, retry, validation, and navigation recovery so a failed request does not strand the user.', minutes: 10, focus: 'frontend error recovery', sections: [
    ['Name the recovery journey', 'A frontend error is not complete when a red message appears. Define the action the user was attempting, the state already changed, the safe next step, and whether retrying can repeat a side effect. An outsourced programmer can map the state machine and create controlled failures; the company decides user language, support promises, and product policy.'],
    ['Separate failure classes', 'Timeout, validation rejection, authorization denial, missing data, and dependency outage should not automatically share one recovery path. Use fixtures that force each class and record loading state, message, focus, available controls, and route behavior. A generic catch block can hide a meaningful distinction that the client needs in order to recover safely.'],
    ['Test retry idempotence', 'Retry is safe for some reads and dangerous for some mutations. Exercise a request that times out after the server may have accepted it, then inspect the client’s retry control and resulting state. Use an idempotency fixture or a no-side-effect sandbox. Do not declare retry safe merely because a second click did not visibly duplicate a row.'],
    ['Inspect stale and partial state', 'When a refresh fails, the interface may retain old data, clear the screen, or show a mixture of old and new fields. Decide what the approved behavior is for the journey and test it with a controlled response. Record timestamps or version labels where they help a reviewer distinguish stale information from a current empty result.'],
    ['Check keyboard and focus recovery', 'A failure that appears visually can be missed by keyboard or assistive technology users. Verify where focus goes after a submission error, whether the message is announced, and whether the retry control is reachable. Keep evidence tied to the affected journey rather than claiming a broad accessibility certification from one route.'],
    ['Handle navigation and refresh', 'Direct links, browser back, refresh, and a route change during a request can expose stale state or an unhandled promise. Use a fixture that delays the response and take each action deliberately. Record whether the result lands on the correct route and whether an old response can overwrite newer state.'],
    ['Make the handoff operational', 'A useful bug report names the trigger, fixture, expected state, observed state, browser or device, and smallest repeatable step. Include a screenshot only when it adds evidence; text is often better for focus and state transitions. Keep customer support language and severity decisions with the owner.'],
    ['Close with explicit boundaries', 'Conclude which failure classes are covered, what the client now does, what remains untested, and who approves the change. The programmer can implement a narrow state correction and add a regression case. The company retains release, incident, privacy, and customer communication authority.']
  ] },
  { slug: 'outsource-dependency-license-inventory', published: '2026-08-24', title: 'Outsource dependency license inventory with evidence for owner review', excerpt: 'Build a reproducible dependency inventory while keeping legal conclusions and release decisions with the company.', minutes: 10, focus: 'dependency license inventory', sections: [
    ['Define inventory scope', 'A dependency list should say whether it covers direct packages, transitive packages, development tools, generated artifacts, container layers, and runtime services. Start from the repository’s actual manifests and build inputs. An outsourced programmer can gather names and versions; the company owner or counsel decides the legal interpretation and release response.'],
    ['Record provenance, not guesses', 'For each package, capture the manifest location, resolved version, lockfile evidence, source URL when available, and the license text or metadata actually observed. Do not infer a license from a package name or a search result. If metadata conflicts, preserve both observations and escalate the conflict rather than selecting the more convenient label.'],
    ['Separate direct and transitive choices', 'A team may be able to replace a direct dependency but not immediately control a transitive one. Mark who selected each package and whether an update changes the dependency tree. This helps a reviewer distinguish an inventory finding from a remediation proposal. The programmer should not remove a package or upgrade a framework under the cover of an audit.'],
    ['Check generated and packaged output', 'A source manifest can omit a copied asset or a production image layer that the build includes. Inspect the repository’s native build inputs and document what was not examined. Use the smallest reproducible command and retain a machine-readable report without embedding it in public pages. The owner decides whether the evidence meets the organization’s release process.'],
    ['Handle missing or conflicting metadata', 'Missing license metadata is an evidence gap, not proof of permission or prohibition. Try the approved source of truth, record the lookup date, and identify the package owner or maintainer path. Do not publish legal conclusions in a technical handoff. A clear unresolved item is more useful than an overconfident classification.'],
    ['Keep the work bounded', 'License inventory can expand indefinitely when every historical artifact and vendor service is added. Name the revision, build target, and dependency classes in scope. If the scan reveals a security issue, an abandoned package, or an incompatible notice, escalate it as a separate decision rather than silently changing the audit’s purpose.'],
    ['Make review reproducible', 'The handoff should include the exact command, lockfile revision, report format, exclusions, and a short explanation of differences from the prior inventory if one exists. Synthetic test packages can validate the parser, but real package findings should remain traceable to repository evidence. Keep credentials and private registries out of shared artifacts.'],
    ['Finish with owner questions', 'State which packages were inventoried, which metadata was unavailable, what changed since the comparison point, and which questions need legal, security, or engineering review. The programmer provides a factual inventory. The company decides notices, replacement, upgrade, release, and communication.']
  ] },
  { slug: 'outsource-database-connection-pool-review', published: '2026-08-24', title: 'Outsource database connection-pool review with bounded load fixtures', excerpt: 'Inspect saturation, timeouts, cleanup, and retry behavior without turning a maintenance task into a production experiment.', minutes: 10, focus: 'database connection pools', sections: [
    ['Describe the pool’s job', 'A connection pool controls how application work reaches a database. Review should begin with pool size, acquisition timeout, idle behavior, transaction lifetime, and the owner of those settings. An outsourced programmer can trace configuration and build a bounded fixture; the company retains infrastructure and production capacity decisions.'],
    ['Observe acquisition separately from query time', 'A slow query and a depleted pool can look alike from an endpoint. Instrument or measure acquisition wait, query duration, transaction duration, and release behavior in a safe environment. Use a small workload with known concurrency and record the first queueing point. Do not extrapolate a local number into a capacity promise.'],
    ['Exercise cleanup paths', 'Connections can remain occupied after an exception, canceled request, stream, or transaction rollback. Prepare fixtures that fail at each relevant step and verify that the connection returns to the pool. A passing request count is not enough if later requests wait indefinitely. Keep database records disposable and avoid real customer data.'],
    ['Check timeout meaning', 'Acquisition timeout, query timeout, network timeout, and application request timeout should be distinguishable when the product depends on recovery. Force one condition at a time and inspect logs, metrics, error mapping, and user behavior. The programmer can clarify the technical path; the owner decides whether a retry is safe and what message a user should receive.'],
    ['Review transaction boundaries', 'Pool pressure often comes from transactions held across remote calls or user interaction. Trace the transaction start and end around the fixture, then document whether locks and connections are released when a downstream dependency fails. Do not redesign transaction policy without an approved scope; identify the narrowest offending path instead.'],
    ['Compare ordinary and burst cases', 'A small steady workload and a short burst reveal different risks. Use deterministic fixtures and a bounded concurrency ceiling, then compare wait time, errors, active connections, and cleanup. State the environment and database configuration so a reviewer understands what the result does and does not show.'],
    ['Protect the evidence', 'Connection diagnostics can include SQL text, identifiers, or configuration secrets. Redact values and keep the fixture schema minimal. Record settings as approved, not as a copy of a secret-bearing environment. If the review requires production telemetry, ask the owner for a sanitized export rather than requesting direct access.'],
    ['Leave a capacity boundary record', 'Conclude with settings inspected, fixture shape, observations, cleanup results, timeout distinctions, and untested conditions. Say whether the work supports a code correction, a separate load exercise, or an infrastructure decision. The programmer supplies reproducible evidence; the company retains capacity, database, and release authority.']
  ] },
  { slug: 'outsource-file-upload-retry-review', published: '2026-08-24', title: 'Outsource file-upload retry review with duplicate and partial-file checks', excerpt: 'Test interrupted uploads, retry identity, cleanup, and user feedback using non-production files and storage.', minutes: 10, focus: 'file-upload retries', sections: [
    ['Define what retry must preserve', 'An upload retry may preserve a file identity, restart bytes, create a new object, or resume a multipart session. Write the intended behavior before testing. An outsourced programmer can build safe fixtures and compare object records; the company decides retention, content policy, and whether a duplicate is acceptable.'],
    ['Use files that reveal boundaries', 'Prepare empty, small, large, renamed, repeated, and deliberately interrupted synthetic files. Include a file whose content changes while its name remains the same. Record expected object identity, size, checksum where available, and visible status for each case. Names alone are not sufficient to prove that retries refer to the same content.'],
    ['Interrupt at useful moments', 'Stop before the first byte, during transfer, after the server accepts metadata, and after completion but before the client receives confirmation. Then retry with the approved client behavior. This sequence exposes duplicate creation and uncertain-result handling that a single successful upload cannot show. Keep the storage target isolated and disposable.'],
    ['Check cleanup and expiry', 'Partial objects and abandoned sessions need an owner-approved cleanup rule. Inspect whether a failed attempt leaves a visible record, consumes quota, or remains retrievable. The programmer can verify a sandbox cleanup job and document timing; they should not delete live objects or choose retention policy.'],
    ['Review authorization on every step', 'Upload initiation, chunk transfer, completion, retry, and download may use different endpoints or tokens. Exercise identities with separate permissions and ensure a retry cannot attach to another user’s session. If the fixture reveals cross-account access, stop and escalate rather than probing further.'],
    ['Follow the interface state', 'The browser should distinguish uploading, paused, retrying, complete, failed, and unknown result. Test refresh, back navigation, network recovery, and a second click. Record whether the user can tell what happened and whether the next action risks a duplicate side effect. Product copy and support promises remain with the owner.'],
    ['Compare server and client identity', 'Match request identifiers, storage keys, object metadata, and displayed names across each attempt. A stable UI label can conceal a new object. Include the exact fixture hash or a safe equivalent in the handoff so the reviewer can tell content identity from filename identity.'],
    ['Deliver an upload recovery record', 'Include the interruption sequence, expected and observed states, object evidence, cleanup result, authorization cases, client behavior, and open decisions. State what was tested in the sandbox and what requires a separate storage or production review. The value is a narrow, safe retry contract rather than a blanket reliability claim.']
  ] },
  { slug: 'outsource-webhook-replay-review', published: '2026-08-24', title: 'Outsource webhook replay review with idempotent side-effect evidence', excerpt: 'Check duplicate deliveries, stale signatures, ordering, and recovery with a sandbox receiver and synthetic events.', minutes: 10, focus: 'webhook replay handling', sections: [
    ['State the side effect boundary', 'A webhook review should name the event, receiver, durable record, and side effect that must not happen twice. An outsourced programmer can prepare synthetic deliveries and inspect an isolated database; the company retains secret, payment, customer, and production event authority.'],
    ['Create delivery variants', 'Use a valid event, a duplicate, a delayed duplicate, an altered payload, a missing field, and an event that arrives out of order. Give each a stable synthetic identifier and expected response. Do not send test events to live endpoints or use real signatures. A variant matrix keeps the review about behavior rather than transport success.'],
    ['Test idempotency at the right key', 'A receiver may deduplicate by event ID, business object, or a combination. Record which identity the application treats as unique and what happens when two legitimate events refer to one object. The programmer can add a narrow uniqueness assertion; the owner decides business semantics when event meaning is ambiguous.'],
    ['Inspect signature and timestamp checks', 'Replay safety depends on canonical bytes, secret selection, timestamp tolerance, and rejection behavior. Exercise a changed body, stale timestamp, wrong secret, and alternate encoding in a sandbox. Capture status and durable state without recording secrets. A rejected request that still leaves a side effect is the first finding to escalate.'],
    ['Handle ordering and retries', 'Events can arrive late or retry after a newer state is stored. Use a controlled sequence to see whether the receiver ignores, reconciles, or applies an older event. Do not invent an ordering rule from one test. Record the rule the product expects and identify the owner when the source system’s delivery guarantee is unclear.'],
    ['Review operational recovery', 'A failed delivery should be observable, classifiable, and recoverable without manual database editing. Inspect retry status, dead-letter or replay controls, and the evidence required before reprocessing. The programmer can document a sandbox recovery; production replay and customer-impact decisions belong to the company.'],
    ['Keep fixtures safe and portable', 'Use local payloads with synthetic identifiers, bounded amounts, and no customer content. Preserve the exact canonical payload used for signing in a protected test fixture, not in public copy. State which provider behavior was simulated and which was observed from documentation or a sandbox.'],
    ['Close with a replay decision', 'The handoff should include the event matrix, signature cases, deduplication key, ordering observations, durable state, retry behavior, and gaps. Conclude whether the receiver is ready for a focused fix, needs an owner decision, or requires a separate integration exercise.']
  ] },
  { slug: 'outsource-search-relevance-review', published: '2026-08-24', title: 'Outsource search relevance review with explainable fixtures', excerpt: 'Compare ranking, filtering, permissions, and empty states without hiding defects behind a single relevance score.', minutes: 10, focus: 'search relevance', sections: [
    ['Define relevance for a real journey', 'Search relevance is meaningful only in relation to a user task. Choose a bounded query set and state what a useful result should help the user find. An outsourced programmer can build a fixture and record ranking evidence; the product owner decides what tradeoff matters when freshness, popularity, permissions, and exact match compete.'],
    ['Build a contrastive collection', 'Create records with exact, partial, synonym, typo, stale, private, and duplicate terms. Give them known ownership, dates, and categories. Predict the expected top results before running the query. A collection with only obvious matches cannot expose tokenization, tie-breaking, or access mistakes.'],
    ['Separate filtering from ranking', 'A result can be relevant but not permitted, or permitted but poorly ranked. Check the candidate set after permission filtering and then inspect ordering. Record missing, extra, and misplaced identities separately. Never use a relevance improvement that reveals a record outside the fixture’s intended audience.'],
    ['Test freshness and updates', 'Change a title, remove a record, and add a new one through the approved sandbox path. Record when the source changed, when the index accepted it, and what queries returned. A stale result can be a data or privacy issue; escalate the boundary before optimizing ranking.'],
    ['Explain empty and ambiguous queries', 'Test blank input, punctuation, short terms, stop words, misspellings, and a query with several plausible matches. Inspect message, suggested recovery, and whether filters reset unexpectedly. The programmer should document observed behavior instead of deciding what search language or product copy ought to be.'],
    ['Compare deterministic ordering', 'Ties should have a stable rule so repeated queries do not make the interface appear broken. Run the same query twice, then add a record with the same score and compare the result. Record the tie-breaker and whether pagination preserves it. Do not infer quality from one ranked list.'],
    ['Make evidence reviewable', 'Capture query, fixture revision, filters, permissions, result identities, rank, freshness, and user-visible state. Avoid screenshots that hide the underlying ordering. If a hosted search provider cannot expose a needed detail, mark it unavailable rather than filling the gap with assumption.'],
    ['Finish with a relevance boundary', 'State the queries covered, what improved or regressed, which policy questions remain, and the smallest next action. The company keeps ranking policy, content decisions, and release authority. The programmer contributes clear comparisons that let a reviewer choose deliberately.']
  ] },
  { slug: 'outsource-frontend-bundle-review', published: '2026-08-24', title: 'Outsource frontend bundle review with route-specific performance evidence', excerpt: 'Measure shipped assets, route cost, and loading behavior while avoiding unsupported performance promises.', minutes: 10, focus: 'frontend bundles', sections: [
    ['Choose a user journey and budget', 'Bundle review should start with a route, device class, network condition, and interaction that matter. Record the current asset set and the question the change must answer. An outsourced programmer can measure and propose a contained correction; the company decides the product tradeoff between capability, fidelity, and load cost.'],
    ['Trace what the route ships', 'Inspect entry chunks, shared modules, images, fonts, third-party scripts, and lazy boundaries. Connect each large asset to a feature or dependency rather than removing it by size alone. A bundle report is more useful when it says why an asset exists and what user behavior would change if it moved.'],
    ['Measure more than transfer size', 'Record transfer, parse, execute, render, and interaction observations where the tooling supports them. Use a repeatable fixture and state cache conditions. Avoid turning one local run into a universal page-speed claim. The evidence should show a before-and-after comparison for the route and environment actually tested.'],
    ['Check slow and reduced-capability cases', 'Test a throttled network, a slower device profile, disabled JavaScript behavior where relevant, and reduced motion when the route supports those choices. Watch for a performance fix that removes an accessible label, delays meaningful content, or breaks keyboard navigation. A smaller bundle is not an acceptable goal by itself.'],
    ['Review third-party boundaries', 'Third-party analytics, embeds, fonts, and widgets can dominate execution or delay interaction. Identify when each loads and what consent or privacy state controls it. The programmer can document the cost and prepare a defer or removal experiment; the company owns provider, privacy, and product decisions.'],
    ['Compare route behavior after change', 'A split chunk or lazy boundary can shift cost to a later click. Follow the first meaningful interaction and a secondary route, not just initial HTML. Record missing loading states, duplicate requests, and failures when the chunk is unavailable. Keep the review tied to a specific change.'],
    ['Preserve a reproducible report', 'Include build revision, route, environment, tool version, asset list, measurements, screenshots only where needed, and open gaps. State whether images and fonts were representative. If a hosted environment or real device was not available, label the limitation instead of implying a complete field study.'],
    ['Conclude without overclaiming', 'A good handoff names the changed asset, observed effect, retained behavior, and next owner decision. It can support one focused pull request or a separate investigation. The company retains release approval and any customer-facing performance claim.']
  ] },
];

export const august23BlogBatch = articles.map(({ slug, title, excerpt, minutes, published }) => ({ slug, title, excerpt, minutes, published }));

const commonSources = [
  { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/Projects/ssdf', note: 'Guidance for reducing software development risk through defined practices and evidence.' },
  { name: 'Google Technical Writing', url: 'https://developers.google.com/tech-writing', note: 'Guidance for clear, reviewable technical explanations.' },
];

export const august23BlogDetails: Record<string, BlogDetail> = Object.fromEntries(articles.map((article) => {
  const takeaways = [
    `Define the evidence boundary for ${article.focus} before implementation begins.`,
    'Use synthetic fixtures, named revisions, and reproducible checks.',
    'Separate observed behavior from policy or release decisions.',
    'Leave open questions with a named company owner.',
  ];
  const sections = article.sections.map(([title, text], index) => ({ id: `${article.slug}-${index + 1}`, title, paragraphs: [text, `${article.title} is ready for review when the expected behavior, safe fixture, observed result, and untested condition are written together. Keep the assignment narrow enough that another programmer can repeat the check without receiving broad production access. If the evidence exposes a product, security, data, or release decision, stop at that boundary and route the question to the company owner.`, `Record the exact source revision, environment, command or interaction, and result for this part of the review. A passing check proves only the stated case. It does not prove every browser, client, dependency, role, or operational condition. That limitation is useful information because it tells the next reviewer what still needs a decision.`] }));
  return [article.slug, { strictNoPricing: true, takeaways, readinessRows: [
    { area: 'Scope', ready: 'One named behavior with acceptance rules', notReady: 'A broad request to improve the system' },
    { area: 'Evidence', ready: 'Safe fixture and observed result', notReady: 'An unverified success claim' },
    { area: 'Access', ready: 'Task-limited sandbox permissions', notReady: 'Shared credentials or live customer data' },
    { area: 'Review', ready: 'Named owner accepts the result', notReady: 'Unreviewed policy or release change' },
  ], sections, roleBrief: [
    { label: 'First slice', text: 'Complete one bounded case with an explicit expected result.' },
    { label: 'Evidence', text: 'Link the fixture, revision, check, observed result, and open gap.' },
    { label: 'Boundary', text: 'Stop before product, security, data, or release authority is assumed.' },
    { label: 'Owner review', text: 'A named company owner decides acceptance, exceptions, merge, and release.' },
  ], faqs: [
    { question: 'What should the first task prove?', answer: `It should prove one observable part of ${article.focus} with a safe fixture and a named expected result.` },
    { question: 'What belongs in the handoff?', answer: 'Include the source revision, fixture, check, observed result, untested condition, and next owner decision.' },
    { question: 'Who keeps final authority?', answer: 'The company retains product, security, data, merge, release, and customer-impact decisions.' },
  ], sources: commonSources } as BlogDetail];
}));
