import type { ResearchPost } from './fleet-content';

const src = {
  api: [['OWASP API Security', 'https://owasp.org/API-Security/'], ['NIST SSDF', 'https://csrc.nist.gov/Projects/ssdf'], ['OpenAPI Specification', 'https://spec.openapis.org/oas/latest.html'], ['GitHub pull request reviews', 'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews']] as const,
  db: [['NIST SSDF', 'https://csrc.nist.gov/Projects/ssdf'], ['PostgreSQL documentation: transactions', 'https://www.postgresql.org/docs/current/tutorial-transactions.html'], ['DORA research', 'https://dora.dev/research/'], ['GitHub pull request reviews', 'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews']] as const,
  a11y: [['W3C WCAG 2.2', 'https://www.w3.org/TR/WCAG22/'], ['W3C Accessible Rich Internet Applications', 'https://www.w3.org/TR/wai-aria/'], ['MDN keyboard accessible', 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/Guides/Understanding_WCAG/Keyboard'], ['NIST SSDF', 'https://csrc.nist.gov/Projects/ssdf']] as const,
  deps: [['OpenSSF Scorecard', 'https://scorecard.dev/'], ['NIST SSDF', 'https://csrc.nist.gov/Projects/ssdf'], ['CISA Secure by Design', 'https://www.cisa.gov/securebydesign'], ['SLSA documentation', 'https://slsa.dev/spec/v1.0/']] as const,
  obs: [['OpenTelemetry documentation', 'https://opentelemetry.io/docs/'], ['DORA research', 'https://dora.dev/research/'], ['NIST SSDF', 'https://csrc.nist.gov/Projects/ssdf'], ['Google SRE book', 'https://sre.google/sre-book/monitoring-distributed-systems/']] as const,
};

const boundary = 'This is bounded research for teams working with outsourced programmers. It does not certify a product, establish a universal benchmark, or replace legal, privacy, security, accessibility, or release review. An authorized company technical owner retains control of production access, merges, releases, customer data, and residual risk.';

export const august23ResearchBatch: ReadonlyArray<ResearchPost> = [
  { slug:'outsourced-api-contract-drift-evidence-2026', route:'/research/outsourced-api-contract-drift-evidence-2026', datePublished:'2026-08-24', campaignDate:'2026-08-24', sourceDateField:'sourceDate', sourceDate:'2026-08-24', published:'2026-08-24', title:'How can an outsourced programmer detect API contract drift before release?', excerpt:'A research study of schema changes, consumer expectations, and evidence for delegated API maintenance.', topic:'API contract drift', hero:'/research-heroes/2026-08-24/outsourced-api-contract-drift-evidence-2026.png', body:[
    'Research question: what evidence can show that a delegated API change preserves the contract that known consumers rely on? “The endpoint still responds” is too weak. A contract includes paths, methods, authentication states, required and optional fields, data types, status codes, error shapes, pagination, ordering, and sometimes timing or idempotency expectations. For an outsourced programmer, the useful assignment is not to promise compatibility in the abstract. It is to compare a named previous contract with a proposed revision under a defined set of consumer observations.',
    'The evidence scope should be explicit. Select one API surface, one baseline revision, one proposed revision, and the consumer classes that the owner has approved for testing. Those classes may include a browser client, a scheduled job, a mobile client, an integration fixture, or another internal service. Do not claim that a handful of fixtures represents every consumer. The study asks whether the selected observations reveal a material difference, not whether future clients are impossible to break.',
    'The method begins by collecting the authoritative sources. The OpenAPI Specification explains how an interface description can represent operations and schemas; OWASP API Security provides a risk lens for authorization and object-level behavior; NIST SSDF supports controlled verification in software work; and GitHub review records provide a durable place to compare the proposed change with its evidence. These sources inform the method. They do not certify an application or prove that a generated schema matches actual behavior.',
    'Create a contract matrix before changing code. For each operation, record the request shape, response shape, success and failure status, authorization context, side effects, and test fixture. Include negative cases: a missing required field, an unknown field, an expired credential, an object that belongs to another test identity, and a repeated request where idempotency matters. A positive response from one happy path is not evidence that the boundary is safe for another principal or another state transition.',
    'Compare behavior at the wire boundary rather than only comparing types in a source file. Capture sanitized requests and responses, status codes, headers that affect caching or pagination, and durable state before and after the call. A field renamed in a TypeScript interface may still be emitted by a serializer, while a seemingly harmless default may alter a client’s interpretation. The programmer can prepare a repeatable fixture and report a difference; the owner decides whether the difference is acceptable and when it may ship.',
    'Distinguish additive changes from semantic changes. Adding an optional response field may be harmless for tolerant clients, but changing a nullable field to always-present, changing an error status, or narrowing accepted input can break a consumer without a compile error. A new authorization rule can also be a contract change even when the JSON schema is identical. Mark each observation as unchanged, additive, incompatible, or unresolved, and link the classification to the exact evidence rather than to intuition.',
    'A useful sampling design includes ordinary and boundary records. Test the smallest valid payload, the largest permitted fixture, an empty collection, a not-found object, a forbidden object, a malformed request, and a retry after an uncertain network result. For list endpoints, compare pagination cursor behavior, stable ordering, and duplicate or missing identities across pages. For write endpoints, inspect whether a retry repeats a side effect. These cases make the research about the real API boundary instead of a polished example.',
    'The analysis should report facts separately from interpretation. Facts include the revision identifiers, operation names, fixture identities, observed statuses, response keys, and persisted state. Analysis explains why a difference may matter to a named consumer or why more evidence is needed. Do not call a difference a defect without stating the contract rule it violates. Do not call a passing fixture proof of safety outside the stated consumer, authorization, data, and environment scope.',
    'Role boundaries are part of the result. An outsourced programmer may inspect the repository, update an approved schema, build synthetic consumer fixtures, and prepare a pull request with comparison evidence. The company owner should retain authority over secrets, customer data, production traffic, compatibility promises, migrations, merges, and release timing. If the test requires live credentials or an undocumented consumer export, stop and request a sanitized, authorized input instead of widening access.',
    'Limitations are material. Documentation may be stale, an API gateway may transform responses, hidden consumers may exist, and a test environment may not reproduce provider behavior or production data shapes. Contract comparison also cannot establish legal, privacy, or security compliance. A result can support a focused correction or a broader compatibility investigation, but it cannot justify a universal “safe for all clients” claim. Record what was unavailable and how that gap affects the decision.',
    'The evidence-led conclusion is narrow: API contract drift becomes actionable when a named baseline, named consumers, negative cases, authorization contexts, and sanitized before-and-after observations are reviewed together. The strongest outsourced programming assignment is a bounded compatibility study that leaves unresolved semantics visible and keeps release authority with the company. A team should expand the consumer set only when the first comparison shows which risk remains, not because a checklist appears complete.', boundary
  ,'A reviewer should preserve the comparison matrix, fixture revision, and unresolved consumer questions with the pull request. Repeating one case after a controlled change is more informative than adding many unbounded examples. This keeps the study useful for a company that must decide whether to widen testing, revise the interface, or defer a release.'], sources:src.api },
  { slug:'outsourced-database-migration-rehearsal-evidence-2026', route:'/research/outsourced-database-migration-rehearsal-evidence-2026', datePublished:'2026-08-24', campaignDate:'2026-08-24', sourceDateField:'sourceDate', sourceDate:'2026-08-24', published:'2026-08-24', title:'What makes a database migration rehearsal credible for outsourced programming work?', excerpt:'Research on reversible fixtures, lock behavior, data shape, and decision evidence for delegated schema changes.', topic:'Database migration rehearsal', hero:'/research-heroes/2026-08-24/outsourced-database-migration-rehearsal-evidence-2026.png', body:[
    'Research question: when does a rehearsal provide credible evidence for an outsourced database migration, and what remains unproven? A migration file that runs once on an empty database says little about existing rows, concurrent traffic, lock duration, rollback limits, or application versions that overlap during release. The study treats a migration as a change to data and behavior, not merely a script. It asks whether an authorized reviewer can understand the fixture, observe the transition, and identify the irreversible boundary.',
    'The evidence scope should name the engine and version, migration revision, representative schema, row-shape classes, expected duration, and application compatibility window. Use synthetic data designed to exercise nulls, duplicates, long values, foreign keys, large tables, and rows created during the transition. A fixture does not need to copy customer data to be useful. In fact, avoiding customer data reduces exposure while forcing the researcher to state which production distributions were not represented.',
    'PostgreSQL transaction guidance clarifies what a transaction can group and where transactional behavior has limits. NIST SSDF supports controlled verification of software changes, DORA research frames delivery outcomes as properties of a system rather than an individual, and pull-request review records preserve the comparison between intent, implementation, and evidence. These sources support a disciplined method, not a claim that a rehearsal proves production capacity or zero downtime.',
    'Start with a before-state inventory. Record tables, indexes, constraints, triggers, views, dependent jobs, and application queries that touch the affected fields. Identify whether the change is additive, backfilling, transforming, renaming, or removing data. For each step, state the expected invariant: every existing row remains addressable, a new column has a valid interpretation, a unique constraint has no collision, or two application versions can read the same record during a rolling release.',
    'Run more than the obvious path. Rehearse against an empty fixture, a small representative fixture, and a deliberately awkward fixture with the edge shapes identified in the inventory. Observe runtime, lock waits, blocked statements, errors, row counts, constraint violations, and post-migration queries. If the migration includes a backfill, separate the schema change from the data movement where the design permits it. A fast empty-database run must never be presented as evidence of large-table behavior.',
    'Test the application transition as well as the database command. If old and new application versions overlap, run reads and writes from both against the migrated fixture. Exercise a request that starts before the backfill and completes afterward, a retry after a timeout, and a worker that sees a partially converted record. These cases reveal assumptions hidden from the migration runner. An outsourced programmer can prepare the compatibility fixture; the company owner decides the deployment window and recovery posture.',
    'Rollback deserves a precise definition. A schema command may be reversible while transformed data is not. A new index may be removable while an external consumer has already observed a new field. For every step, label recovery as automatic, scripted, forward-only, or requiring an owner decision. Capture the prior snapshot or disposable fixture version, the command boundary, verification queries, and the evidence that says when to stop. “Rollback available” without a data and side-effect analysis is not a plan.',
    'Facts and analysis should remain separate in the report. Facts include engine version, fixture generator revision, command output, observed locks, row counts, timings, and query results. Analysis can explain that a lock was material under the tested concurrency or that a conversion needs a staged approach. Do not infer a production outage from a lab wait, and do not dismiss a warning because the fixture was small. Both observations should refine the next question.',
    'The work lane needs boundaries because databases carry durable consequences. The programmer may write a fixture, inspect an approved schema, run a local or isolated rehearsal, and prepare a migration pull request. The technical owner keeps production credentials, backups, customer data, destructive commands, maintenance windows, and final release authority. If a rehearsal exposes a possible data-integrity defect, stop at the evidence boundary and escalate rather than improvising a repair against a shared environment.',
    'Limitations include synthetic distributions, absent replicas, different storage hardware, provider-specific lock behavior, and an incomplete inventory of consumers. A rehearsal cannot prove a precise production duration unless its environment and workload are validated as comparable. It also does not establish regulatory, privacy, or backup compliance. These limits are not editorial disclaimers added at the end; they determine whether the evidence supports a code change, a capacity exercise, or an owner decision.',
    'The conclusion is evidence-led and bounded: a database migration rehearsal is credible when it connects a named change to representative data shapes, application-version overlap, observed lock and integrity behavior, and an explicit recovery boundary. For outsourced programming work, that produces a reviewable technical package without transferring production authority. The next action should be chosen from the observed gap—fixture expansion, staged backfill, query correction, backup validation, or owner-approved release planning—not from a generic promise that migrations are safe.',
    'Also record the point at which the rehearsal stops being representative. A small fixture may test correctness while a separate workload exercise tests contention, and neither should be silently treated as the other. Keeping those findings separate gives the technical owner a clearer basis for sequencing further investigation.', boundary
  ,'Preserve the rehearsal commands, fixture generator, and verification queries so another authorized reviewer can repeat one condition without copying sensitive data. The result should make clear whether the next decision concerns schema design, workload capacity, backup recovery, or release sequencing.','The owner should receive the exact fixture assumptions and the observed boundary conditions, including which checks were intentionally omitted. That makes a staged plan or recovery exercise a reasoned response to evidence rather than a generic migration ritual.'], sources:src.db },
  { slug:'outsourced-accessibility-regression-evidence-2026', route:'/research/outsourced-accessibility-regression-evidence-2026', datePublished:'2026-08-24', campaignDate:'2026-08-24', sourceDateField:'sourceDate', sourceDate:'2026-08-24', published:'2026-08-24', title:'Which evidence shows an outsourced web change preserved keyboard access?', excerpt:'A research method for separating automated signals, focus behavior, semantics, and user-task evidence.', topic:'Accessibility regression evidence', hero:'/research-heroes/2026-08-24/outsourced-accessibility-regression-evidence-2026.png', body:[
    'Research question: what evidence can show that a delegated web change preserves keyboard access for a defined user task? A green automated scan is not the same as a usable interaction. Keyboard access depends on focus order, visible focus, semantic controls, dialog behavior, error recovery, dynamic updates, and whether a person can complete the task without a pointer. This study asks how an outsourced programmer can prepare bounded evidence while the company retains responsibility for product decisions and conformance review.',
    'Define one route and one task before testing. Examples include opening a menu, filtering a list, submitting a form with an error, editing a record, or completing a checkout-like flow in a safe fixture. Name the starting focus, expected landmarks, interactive controls, state changes, and completion signal. The test should include a realistic path and a recovery path. A page can pass a static rule while trapping focus in a dialog or losing the user after validation fails.',
    'WCAG 2.2 provides success criteria and conformance structure; WAI-ARIA describes semantics and states for interactive widgets; MDN explains practical keyboard-accessible behavior; NIST SSDF contributes a controlled verification lens. The sources are claim-relevant guidance, not an audit certificate. They support a repeatable observation protocol. They do not prove that every assistive technology, browser, language, input method, or user journey behaves identically.',
    'Use a layered method. First inspect the rendered semantics and document landmarks, headings, labels, names, roles, states, and relationships. Next perform the task with the keyboard alone, recording every focus movement and visible indicator. Then test dynamic states such as an expanded menu, a modal, an inline error, a loading result, and a newly inserted item. Finally compare the expected task outcome with the observed page state. Each layer catches a different class of regression.',
    'Focus order should be recorded as a sequence, not a vague impression. Note where focus begins, which control receives it after activation, whether the order follows the visual and task order, and whether focus becomes invisible or stranded. For a dialog, test entry, internal navigation, escape behavior, close-button access, and return to the invoking control. For a menu or combobox, state whether the implementation follows its declared interaction model rather than assuming that a role attribute creates behavior.',
    'Error handling deserves its own evidence. Submit incomplete or invalid synthetic data, move through the fields with the keyboard, and observe whether the error is associated with the field, announced or otherwise discoverable, and recoverable without restarting the entire task. Test a server-side response as well as a client-side validation path where the product uses both. The programmer can reproduce a defect and propose a narrow fix; the owner decides copy, policy, and release priority.',
    'Automated tools are useful for finding missing labels, contrast risks, duplicate IDs, and structural anomalies, but they should be treated as one evidence layer. Record tool name and version, route state, fixture, and findings. Do not convert a tool pass into a claim of accessibility conformance. Conversely, a tool warning should be interpreted against the actual user task rather than blindly suppressed. Facts describe the observed rule or behavior; analysis explains its likely impact and confidence.',
    'Outsourced work needs a safe access boundary. The programmer may use a local or preview build, synthetic records, approved browser tooling, and a defined route. They should not request production customer data or announce a conformance claim without the owner’s review. If the route depends on authentication, provide a least-privilege test identity with disposable content. Security, privacy, legal, and release decisions remain outside the coding task.',
    'A useful sample compares the changed route with a prior approved behavior where available. Record the source revision, browser and viewport, operating-system input method, fixture state, task steps, expected focus, observed focus, and screenshots only when they clarify a state. Repeat the critical path after the fix and include an untouched control route to identify environment-wide changes. One successful pass is evidence for that path, not for every route in the application.',
    'Limitations include unavailable screen readers, incomplete browser coverage, dynamic third-party widgets, localized content, responsive layouts, and the difference between technical observation and lived user experience. WCAG mapping can also require judgment about context and conformance scope. State what was not tested and route unresolved issues to an appropriate accessibility or product reviewer. Do not use a limited keyboard exercise to imply legal compliance or universal usability.',
    'The conclusion is narrow: preserved keyboard access is better supported by a task-specific sequence of semantic inspection, keyboard interaction, dynamic-state checks, error recovery, and bounded repetition than by an automated score alone. Outsourced programmers can produce this evidence and a focused correction while the company decides product priorities, conformance interpretation, and release acceptance. The record is strongest when it names the exact path that passed and the paths that remain unknown.', boundary
  ,'Keep the exact task sequence and changed content available for a focused retest. One additional condition at a time can show whether the finding belongs to a component, a content shape, or a broader interaction pattern. That makes the evidence easier to review than a broad claim about the whole site.','A focused retest should preserve the same route and task while changing only one condition. This helps the reviewer decide whether the finding belongs to component behavior, content shape, or the wider interaction model.','The evidence should name the browser, viewport, input method, route state, and fixture revision. If one of those conditions was unavailable, record it as an explicit limitation rather than silently broadening the meaning of a passing observation. That keeps the accessibility result useful for the owner who must choose the next review.'], sources:src.a11y },
  { slug:'outsourced-dependency-provenance-review-2026', route:'/research/outsourced-dependency-provenance-review-2026', datePublished:'2026-08-24', campaignDate:'2026-08-24', sourceDateField:'sourceDate', sourceDate:'2026-08-24', published:'2026-08-24', title:'How should an outsourced programmer review dependency provenance?', excerpt:'Evidence-led research on package identity, update risk, build inputs, and bounded software supply-chain review.', topic:'Dependency provenance', hero:'/research-heroes/2026-08-24/outsourced-dependency-provenance-review-2026.png', body:[
    'Research question: what evidence lets a company understand the provenance and change risk of dependencies handled by an outsourced programmer? A package name in a manifest is not a complete supply-chain record. The decision may depend on the exact version, lockfile resolution, source repository, release artifact, build behavior, maintainer signals, license obligations, vulnerability history, and whether the package is actually reachable in production. This study focuses on evidence and boundaries, not on declaring a package safe from a single scan.',
    'Define the unit of review. It may be one proposed dependency, a transitive tree for a route, a build image, or a package update class. Record the repository and branch revision, package manager, lockfile, platform, and command used to produce the inventory. Distinguish direct dependencies from transitive ones and runtime packages from development-only tools. Without that separation, a large count of packages can obscure the few inputs that affect the shipped path.',
    'OpenSSF Scorecard offers automated signals about public project practices; SLSA describes provenance concepts for build integrity; NIST SSDF frames secure development practices; and CISA Secure by Design emphasizes reducing avoidable security risk. These sources support questions to ask and evidence to retain. None establishes that a package is appropriate for every application, that a score is a security verdict, or that a public repository’s history matches a privately mirrored artifact.',
    'Begin with identity and resolution. Compare the declared version with the lockfile version, integrity information, package tarball metadata, source URL, and the package manager’s actual install report. Note aliases, overrides, optional dependencies, platform-specific branches, post-install scripts, and packages pulled from private registries. Preserve sensitive registry details outside the public handoff. The programmer can produce a sanitized inventory; the owner decides which sources and credentials are authorized.',
    'Next connect the dependency to behavior. Search the application for imports, entry points, generated output, and build configuration that make the package reachable. A package may be present but unused, or a small utility may sit on an authentication or file-processing path. Run the project’s approved checks and record which route or command exercises the dependency. Reachability does not determine exploitability, but it gives a reviewer better context than a raw package count.',
    'Review change evidence rather than only current state. For an update, compare release notes, changelog, advisories, API changes, lockfile diff, build output, test results, and known compatibility boundaries. Separate facts—such as a major-version change or a new install script—from analysis about migration effort or risk. If a source cannot be verified, mark provenance as unresolved. Do not fill a missing artifact with a plausible assumption merely to complete a table.',
    'Build reproducibility is a separate question. Repeat installation in an approved clean environment using the committed lockfile and compare resolved identities and generated artifacts where the toolchain permits. Record operating system, runtime, package-manager version, and network or mirror behavior. A passing local build does not prove that every future registry response is identical, while a difference may reveal an environment or policy issue rather than a defect in the package itself.',
    'The review should include response options. A company may accept the dependency with monitoring, pin it, replace it, vendor it, restrict its use, defer the update, or commission a deeper security review. An outsourced programmer can research the package, prepare a lockfile change, add tests, and explain the evidence. They should not approve a security exception, publish a vulnerability conclusion, modify production registries, or make a legal license determination without the accountable owner.',
    'Use a bounded evidence record: package identity, resolved version, integrity, source, direct or transitive status, reachable path, update delta, tests, build context, unavailable fields, and recommended next decision. Avoid copying secrets, private URLs, or customer code into broad documents. If a scanner reports a vulnerability, preserve the advisory identifier and affected range, then route remediation and compensating-control decisions to security or engineering ownership.',
    'Limitations include private package opacity, incomplete reachability analysis, changing registries, unobserved build workers, false positives, and the fact that provenance does not equal absence of malicious or vulnerable behavior. Public project signals are not a substitute for threat modeling or code review. A dependency inventory can support a better decision, but it cannot establish universal safety, license compliance, or a complete software bill of materials unless the chosen process actually produces those artifacts.',
    'The conclusion is evidence-led: dependency provenance is reviewable when exact resolution, source identity, reachability, change history, build context, and unknowns are connected in one bounded record. For outsourced programming, this lets a contributor prepare useful supply-chain evidence without receiving broad authority. The next action should follow the unresolved fact—pinning, replacement, advisory analysis, provenance improvement, or owner-approved acceptance—rather than a simplistic package-count target.',
    'A useful review also preserves the comparison point. If the lockfile, registry, or build image changes later, the owner can tell whether a new finding reflects dependency movement or a better inspection method. That distinction prevents an outsourced maintenance ticket from quietly becoming an unbounded security investigation.', boundary
  ,'Retain the inventory with the proposed change so a later reviewer can distinguish a new package, a resolver change, and a scanner change. The review itself needs provenance too; otherwise a stale finding can be mistaken for current supply-chain evidence.','Retain the inventory and its unavailable fields with the proposed change. Later reviewers can then distinguish a new package, resolver behavior, and scanner behavior instead of treating an old score as current evidence.','The review should also identify who can approve an exception and which evidence would retire it. That makes the package useful for security and engineering review without turning a scanner result into a universal safety claim. Keep credentials and private registry details out of broad artifacts.'], sources:src.deps },
  { slug:'outsourced-release-observability-evidence-2026', route:'/research/outsourced-release-observability-evidence-2026', datePublished:'2026-08-24', campaignDate:'2026-08-24', sourceDateField:'sourceDate', sourceDate:'2026-08-24', published:'2026-08-24', title:'What observability evidence helps review an outsourced software release?', excerpt:'A research study of signal coverage, change correlation, and limits of release monitoring evidence.', topic:'Release observability', hero:'/research-heroes/2026-08-24/outsourced-release-observability-evidence-2026.png', body:[
    'Research question: what observability evidence can help an owner distinguish a healthy outsourced software release from an unobserved one? A dashboard with many charts is not necessarily useful. The review needs to connect a release identity to the user journey, service signals, errors, latency, logs, traces, and recovery decisions that matter for the changed behavior. This research examines how a programmer can prepare that connection without implying that a preview result predicts every production outcome.',
    'Set the boundary around one release and one change. Name the artifact or commit, route or operation, dependency path, expected behavior, and observation window. Include a control path if one helps separate a release effect from a platform-wide event. Decide in advance which signals would trigger investigation and which are merely contextual. Without a time and change boundary, monitoring becomes a collection of interesting numbers rather than evidence for a decision.',
    'OpenTelemetry documents traces, metrics, and logs as signals that can be correlated; DORA research treats delivery outcomes as properties of a system; NIST SSDF supports protected development and verification; and the Google SRE monitoring chapter explains why monitoring should serve actionable questions. These sources guide the design. They do not prove that instrumentation is complete, that a release caused a change, or that an observed threshold is a universal service-level target.',
    'Start from the user or operator question. If the change concerns a form submission, observe request acceptance, validation errors, downstream work, durable state, and user-visible confirmation. If it concerns an API, observe status classes, latency partitions, authorization failures, dependency errors, and retry behavior. If it concerns a background job, observe queue age, processing outcome, duplicate handling, and dead-letter state. Signals should explain the behavior under review rather than maximize dashboard density.',
    'Correlation requires stable identities. Record release revision, service name, environment, route or operation, request or trace identifier where safe, and the time basis used for comparison. Check whether logs, metrics, and traces use compatible clocks and labels. A spike in errors that cannot be connected to the changed path is a clue, not a causal finding. An outsourced programmer can improve labels or add a diagnostic query; the owner decides what data may be retained and who may view it.',
    'Compare a defined baseline with the changed state. Baselines should include the same route, fixture, workload class, and observation period where possible. Report counts and rates with their denominators, and separate user errors, authorization failures, dependency failures, and server faults. A mean can hide a severe tail, while a percentage from five requests can look more certain than it is. Preserve raw scope and sampling limits so a reviewer can judge the strength of the comparison.',
    'Test failure paths in an isolated environment. Use synthetic inputs to produce validation errors, timeouts, dependency unavailability, retries, and partial completion where the application supports them. Verify that the resulting signals are distinguishable and that sensitive values are redacted. Do not induce failures in production merely to create a dashboard example. If production evidence is necessary, request an approved sanitized observation window and stop short of changing traffic or data.',
    'Release observability also includes decision usability. A reviewer should be able to answer what changed, what was observed, what was expected, what remains unknown, and who decides the next action. Alerts that lack an owner or a runbook may create noise rather than control. The programmer can prepare queries, labels, dashboards, and a handoff; the company retains incident authority, customer communication, rollback, and release acceptance.',
    'Facts and analysis must be visibly separated. Facts include timestamps, revision, signal names, counts, sampled requests, observed errors, and tool configuration. Analysis may say that the evidence is consistent with a release-specific regression, but it should name competing explanations such as traffic mix, dependency health, or a concurrent platform change. Avoid claiming causation from temporal coincidence alone. Record which additional test would discriminate between the explanations.',
    'Limitations are unavoidable. Telemetry can be sampled, dropped, delayed, mislabeled, or unavailable across a provider boundary. A preview workload may not represent production traffic, and privacy controls may limit identifiers or payload detail. Observability cannot prove a negative, certify security, or guarantee that an untested customer journey is healthy. State the blind spots and avoid storing more customer data just to make a chart appear complete.',
    'The conclusion is bounded: release observability is useful when it links a named change to actionable signals, comparable scope, explicit denominators, failure-path evidence, and a decision owner. Outsourced programmers can prepare that evidence and improve the technical trail while the company retains production monitoring, incident response, rollback, and customer-impact authority. The right next step is the smallest missing observation that would change the release decision, not a universal demand for more telemetry.', boundary
  ,'Record the observation window, signal gaps, and decision outcome so the next release can compare like with like. If a signal did not affect the decision, that is still useful evidence about whether it belongs in a release gate or only in diagnosis.','The release record should preserve signal gaps and decision outcomes, not just healthy charts. That lets an owner distinguish a monitoring gap from a regression and choose a narrow follow-up.','A good handoff names the exact signal, comparison window, and unresolved competing explanation. If the evidence cannot change a release decision, the owner can decide whether the signal belongs in a gate, a runbook, or a later diagnostic study. That is a more disciplined outcome than collecting telemetry without a question.'], sources:src.obs },
];
