import type { ResearchPost } from './fleet-content';

const sources = [
  ['NIST Secure Software Development Framework', 'https://csrc.nist.gov/Projects/ssdf'],
  ['OWASP Application Security Verification Standard', 'https://owasp.org/www-project-application-security-verification-standard/'],
  ['CISA Secure by Design', 'https://www.cisa.gov/securebydesign'],
  ['Google Technical Writing', 'https://developers.google.com/tech-writing'],
  ['W3C WCAG 2.2', 'https://www.w3.org/TR/WCAG22/'],
  ['OpenTelemetry documentation', 'https://opentelemetry.io/docs/'],
] as const;

const body = (subject: string, finding: string, unit: string, limitation: string): readonly string[] => [
  `${subject} is best studied as a bounded engineering question, not as a promise that an outsourced programmer can solve an entire system. The useful unit is ${unit}. A route that compiles, a screenshot that looks correct, or a single successful request is only one observation. The research question should name the expected behavior, the affected cohort, the period, and the evidence that would change the decision.`,
  `Begin with a baseline before a change is proposed. Record the application version, relevant configuration, fixture identity, runtime, browser or device, time zone, and test date. If the baseline cannot be reproduced, later comparisons become stories about different systems. A technical owner should approve the baseline and identify which differences are material rather than asking the contributor to guess.`,
  `The strongest study separates correctness, security, performance, and recovery. A fast response can still be wrong; a complete response can still reveal data to the wrong identity; a passing automated check can still miss a user-facing failure. Record each dimension separately, with a denominator and observation window whenever a rate, duration, or failure count is reported.`,
  `Use synthetic or masked fixtures that represent the states that matter to ${subject.toLowerCase()}. Include empty values, malformed values, boundaries, repeated actions, permissions, and dependency failures where they are relevant. Keep the fixture versioned and resettable. Real customer records should not be used merely because they are convenient, and diagnostic output should be checked for secrets and personal data.`,
  `A useful comparison divides the population into meaningful cohorts instead of presenting one universal threshold. For ${subject.toLowerCase()}, compare critical and secondary journeys, authenticated and anonymous states, small and large inputs, and intended changes against regressions. Report sample size and selection rules. A median can hide a severe minority, while a single worst case can exaggerate a rare condition.`,
  `The evidence should be linked to an exact artifact: a route, request, fixture, commit, log record, trace, or review decision. Each observation needs an expected result, observed result, and disposition. This makes the work reviewable by someone who was not present during the test and prevents a polished summary from outrunning its underlying evidence.`,
  `Failure paths deserve deliberate attention. In an isolated approved environment, interrupt the relevant operation, remove a permission, repeat a request, exceed a limit, or make a dependency unavailable when that failure is within scope. Record the user-visible result, persisted state, retry behavior, cleanup, and escalation. Do not infer safe recovery from the existence of an undo button.`,
  `For distributed programming support, preparation and approval should remain distinct. An outsourced programmer can inventory cases, prepare a focused patch, run authorized checks, and document uncertainties. The company technical owner retains architecture decisions, production credentials, customer data, policy choices, release approval, and acceptance of residual risk. This division is a control, not a judgment about an individual contributor.`,
  `Authoritative guidance is useful when it narrows a claim. NIST describes practices for developing secure software, OWASP provides verification objectives, CISA explains secure-by-design principles, and Google emphasizes usable technical instructions. These sources support methods and terminology; they do not prove that a particular implementation complies. Cite the claim each source actually supports and label inferences as inferences.`,
  `The central finding for this study is ${finding}. That conclusion is conditional on the named cohort, fixture, environment, and observation window. It does not establish that every route, browser, tenant, provider, or future release behaves the same way. A reviewer should be able to challenge the conclusion by inspecting the cases that passed, the cases that failed, and the cases that were excluded.`,
  `Recovery and ownership should be part of the final record. Name the last known-good artifact, the reversible step, the irreversible boundary, the person authorized to stop or roll back, and the evidence required after recovery. If a change can affect stored data, external messages, caches, permissions, or billing state, code rollback alone is not a complete recovery argument.`,
  `Limitations must be explicit. ${limitation} Staging may differ from production traffic and integrations; synthetic fixtures may omit uncommon combinations; automated checks may miss semantics or assistive-technology behavior; and a short observation window cannot establish long-term reliability. These limits identify the next measurement rather than being hidden in a confident headline.`,
  `The practical decision rule is bounded: accept the evidence, narrow the change, collect a named missing observation, or escalate an unresolved risk. Prefer the smallest next step that can test the recommendation. Preserve the route or record identity, source versions, fixture details, reviewer, and disposition so later work can compare like with like instead of restarting from an undocumented assumption.`,
  `Do not confuse an implementation artifact with an outcome. A pull request, dashboard, test report, or runbook is valuable because it makes a decision inspectable, not because its existence proves quality. Reviewers should ask whether the artifact names the affected behavior, includes negative cases, identifies the owner, and can be refreshed when the dependency or product changes.`,
  `Time and sequence matter in interpretation. A first observation after a release may reflect warm-up, cached data, migration timing, or a temporary dependency condition. Record when the observation was made, what preceded it, and whether the same case was repeated. When comparing batches, keep the measurement method and inclusion rules stable or explain the difference explicitly.`,
  `The safest handoff also records unanswered questions. If a fixture omits a tenant type, a locale, a browser, a data volume, or a provider response, name that omission and state whether it blocks acceptance. A short list of bounded unknowns is more useful than a broad statement that the work is complete, because the owner can assign the next observation deliberately.`,
  `Evidence should be proportional to impact. A low-risk documentation correction may need a focused link and rendering check, while authorization, stored data, external side effects, and recovery paths need independent review and negative cases. This does not require every task to become a large test program; it requires the evidence to match the consequence of being wrong.`,
  `For an outsourced work lane, written evidence reduces avoidable context loss across time zones and review windows. The record should let the next programmer or owner understand what changed, why it changed, what was measured, what remains uncertain, and who can approve the next step. That continuity is especially important when the original contributor is unavailable.`,
  `A decision record should distinguish observation from interpretation. The measured result belongs in one field, the explanation in another, and the recommended action in a third. This separation helps a reviewer reject an attractive theory without discarding a reliable observation, and it prevents a proposed fix from being mistaken for proof that the diagnosis was correct.`,
  `Repeatability is a practical quality test for distributed work. A second authorized reviewer should be able to use the stated fixture, command, route, and expected result without private context from the original handoff. If reproduction fails, record the failure as evidence about the instructions or environment rather than silently changing the case until it passes.`,
  `Finally, retire stale evidence deliberately. Mark the release, dependency, source version, and review date so a later owner can tell whether the conclusion still applies. When a product boundary changes, reopen the relevant cases and preserve the earlier result as history instead of presenting it as current proof.`,
  `This research is a planning aid for teams working with outsourced programmers. It is not legal, tax, employment, privacy, accessibility-conformance, security, or operational advice. Validate the cited guidance against the actual product, contract, jurisdiction, threat model, data classification, and owner-approved change window before acting.`,
];

export const august13ReplacementResearchBatch: ReadonlyArray<ResearchPost> = [
  { slug: 'outsourced-nextjs-cache-invalidation-study', title: 'Cache invalidation evidence for outsourced Next.js maintenance', excerpt: 'Research on proving freshness, revalidation, and permission-safe cache behavior in distributed web work.', topic: 'Cache invalidation', published: '2026-08-13', body: body('Next.js cache invalidation behavior', 'freshness claims require an explicit content version, request cohort, invalidation event, and observation window rather than a single uncached request', 'a route under anonymous, authenticated, empty-data, and failure states', 'the study does not measure every browser, streaming condition, or provider integration'), sources },
  { slug: 'outsourced-postgres-zero-downtime-migration-study', title: 'Zero-downtime PostgreSQL migration evidence for outsourced teams', excerpt: 'Research on compatibility windows, lock behavior, and rollback boundaries during database changes.', topic: 'Database migrations', published: '2026-08-13', body: body('zero-downtime PostgreSQL migration behavior', 'migration safety depends on compatibility between application versions, lock observations, representative data, and a tested recovery boundary', 'a version pair exercised across the site’s named publishing and account journeys', 'a staging clone may not reproduce every hosting module, scheduled task, or extension configuration'), sources },
  { slug: 'outsourced-oauth-callback-security-study', title: 'OAuth callback security evidence for outsourced web applications', excerpt: 'Research on redirect validation, state handling, and failure behavior in delegated sign-in flows.', topic: 'OAuth callbacks', published: '2026-08-13', body: body('OAuth callback security behavior', 'callback confidence requires observed state binding, redirect validation, token handling, and denial paths for each supported client flow', 'a request identity and endpoint tested across normal, burst, and recovery windows', 'provider limits and network timing can change outside the controlled test environment'), sources },
  { slug: 'outsourced-webhook-signature-verification-study', title: 'Webhook signature verification research for outsourced integrations', excerpt: 'Research on authenticating webhook deliveries, replay resistance, and safe retry handling.', topic: 'Webhook verification', published: '2026-08-13', body: body('webhook signature verification behavior', 'delivery trust depends on canonical payload handling, timestamp tolerance, secret rotation, replay rejection, and observable retry outcomes', 'a migration version paired with representative rows and both application versions', 'a rehearsal cannot prove production lock duration or every live data distribution'), sources },
  { slug: 'outsourced-cicd-artifact-integrity-study', title: 'CI/CD artifact integrity evidence for distributed engineering teams', excerpt: 'Research on tracing build inputs, artifacts, approvals, and promotion eligibility.', topic: 'Artifact integrity', published: '2026-08-13', body: body('CI/CD artifact integrity behavior', 'artifact trust requires a traceable input set, reproducible identity, approval boundary, and rejection evidence for altered or incomplete outputs', 'an exception signature joined to a route, release, browser cohort, and safe reproduction', 'telemetry sampling and privacy filters can hide rare devices or context needed for diagnosis'), sources },
  { slug: 'outsourced-accessibility-focus-management-study', title: 'Focus-management evidence for outsourced accessible web work', excerpt: 'Research on keyboard focus, dialog transitions, errors, and route changes across representative journeys.', topic: 'Focus management', published: '2026-08-13', body: body('accessible focus-management behavior', 'focus claims require keyboard-observable transitions, meaningful announcements, recovery after errors, and checks across the affected journey rather than an automated score alone', 'a synthetic file and identity exercised through upload, rejection, retry, and retrieval states', 'provider scanning, storage policy, and network behavior may differ from the test fixture'), sources },
  { slug: 'outsourced-mobile-api-versioning-study', title: 'Mobile API versioning evidence for outsourced application teams', excerpt: 'Research on backward compatibility, deprecation signals, and safe client migration across release lag.', topic: 'Mobile API versioning', published: '2026-08-13', body: body('mobile API versioning behavior', 'compatibility confidence requires named client versions, contract differences, deprecation timing, and failure handling across the supported release lag', 'a release cohort joined to route health, error, latency, and rollback observations', 'a short canary window cannot establish behavior under every traffic mix or delayed job'), sources },
  { slug: 'outsourced-search-index-reconciliation-study', title: 'Search-index reconciliation research for outsourced application work', excerpt: 'Research on completeness, freshness, permissions, and repair evidence for application search indexes.', topic: 'Search reconciliation', published: '2026-08-13', body: body('search-index reconciliation behavior', 'index confidence depends on source-to-index counts, freshness markers, permission filtering, deletion handling, and a repeatable repair comparison', 'a bounded export job compared with source and destination identities over a stated period', 'counts can agree while field transformations, ordering, or late-arriving records remain untested'), sources },
  { slug: 'outsourced-payment-state-recovery-study', title: 'Payment-state recovery evidence for outsourced application teams', excerpt: 'Research on reconciling uncertain payment states without duplicating side effects or exposing sensitive records.', topic: 'Payment recovery', published: '2026-08-13', body: body('payment-state recovery behavior', 'recovery safety requires explicit pending, succeeded, failed, and unknown states with idempotency and reconciliation evidence for each transition', 'a named locale and timezone exercised across representative dates, amounts, and text lengths', 'the selected locales cannot represent every script, font, device, or translation workflow'), sources },
  { slug: 'outsourced-multitenant-isolation-study', title: 'Multitenant isolation evidence for outsourced software work', excerpt: 'Research on tenant boundaries, authorization cases, and leakage-resistant test evidence in shared applications.', topic: 'Tenant isolation', published: '2026-08-13', body: body('multitenant isolation behavior', 'isolation confidence requires cross-tenant negative cases at every data access boundary, plus evidence that caches, exports, logs, and errors preserve the boundary', 'a message identity followed through first delivery, retry, duplicate delivery, and recovery', 'an isolated queue cannot establish behavior under the production volume, ordering, or provider failure pattern'), sources },
];
