import type { ResearchPost } from './fleet-content';

const sources = [
  ['NIST Secure Software Development Framework', 'https://csrc.nist.gov/Projects/ssdf'],
  ['OWASP Application Security Verification Standard', 'https://owasp.org/www-project-application-security-verification-standard/'],
  ['CISA Secure by Design', 'https://www.cisa.gov/securebydesign'],
  ['Google Technical Writing', 'https://developers.google.com/tech-writing'],
  ['W3C WCAG 2.2', 'https://www.w3.org/TR/WCAG22/'],
  ['OpenTelemetry documentation', 'https://opentelemetry.io/docs/'],
] as const;

const body = (subject: string, finding: string, unit: string, limitation: string): readonly string[] => [
  `${subject} is best studied as a bounded engineering question, not as a promise that an outsourced programmer can solve an entire system. The useful unit is ${unit}. A route that compiles, a screenshot that looks correct, or a single successful request is only one observation. The research question should name the expected behavior, the affected cohort, the period, and the evidence that would change the decision.`,
  `Begin with a baseline before a change is proposed. Record the application version, relevant configuration, fixture identity, runtime, browser or device, time zone, and test date. If the baseline cannot be reproduced, later comparisons become stories about different systems. A technical owner should approve the baseline and identify which differences are material rather than asking the contributor to guess.`,
  `The strongest study separates correctness, security, performance, and recovery. A fast response can still be wrong; a complete response can still reveal data to the wrong identity; a passing automated check can still miss a user-facing failure. Record each dimension separately, with a denominator and observation window whenever a rate, duration, or failure count is reported.`,
  `Use synthetic or masked fixtures that represent the states that matter to ${subject.toLowerCase()}. Include empty values, malformed values, boundaries, repeated actions, permissions, and dependency failures where they are relevant. Keep the fixture versioned and resettable. Real customer records should not be used merely because they are convenient, and diagnostic output should be checked for secrets and personal data.`,
  `A useful comparison divides the population into meaningful cohorts instead of presenting one universal threshold. For ${subject.toLowerCase()}, compare critical and secondary journeys, authenticated and anonymous states, small and large inputs, and intended changes against regressions. Report sample size and selection rules. A median can hide a severe minority, while a single worst case can exaggerate a rare condition.`,
  `The evidence should be linked to an exact artifact: a route, request, fixture, commit, log record, trace, or review decision. Each observation needs an expected result, observed result, and disposition. This makes the work reviewable by someone who was not present during the test and prevents a polished summary from outrunning its underlying evidence.`,
  `Failure paths deserve deliberate attention. In an isolated approved environment, interrupt the relevant operation, remove a permission, repeat a request, exceed a limit, or make a dependency unavailable when that failure is within scope. Record the user-visible result, persisted state, retry behavior, cleanup, and escalation. Do not infer safe recovery from the existence of an undo button.`,
  `For distributed programming support, preparation and approval should remain distinct. An outsourced programmer can inventory cases, prepare a focused patch, run authorized checks, and document uncertainties. The company technical owner retains architecture decisions, production credentials, customer data, policy choices, release approval, and acceptance of residual risk. This division is a control, not a judgment about an individual contributor.`,
  `Authoritative guidance is useful when it narrows a claim. NIST describes practices for developing secure software, OWASP provides verification objectives, CISA explains secure-by-design principles, and Google emphasizes usable technical instructions. These sources support methods and terminology; they do not prove that a particular implementation complies. Cite the claim each source actually supports and label inferences as inferences.`,
  `The central finding for this study is ${finding}. That conclusion is conditional on the named cohort, fixture, environment, and observation window. It does not establish that every route, browser, tenant, provider, or future release behaves the same way. A reviewer should be able to challenge the conclusion by inspecting the cases that passed, the cases that failed, and the cases that were excluded.`,
  `Recovery and ownership should be part of the final record. Name the last known-good artifact, the reversible step, the irreversible boundary, the person authorized to stop or roll back, and the evidence required after recovery. If a change can affect stored data, external messages, caches, permissions, or billing state, code rollback alone is not a complete recovery argument.`,
  `Limitations must be explicit. ${limitation} Staging may differ from production traffic and integrations; synthetic fixtures may omit uncommon combinations; automated checks may miss semantics or assistive-technology behavior; and a short observation window cannot establish long-term reliability. These limits identify the next measurement rather than being hidden in a confident headline.`,
  `The practical decision rule is bounded: accept the evidence, narrow the change, collect a named missing observation, or escalate an unresolved risk. Prefer the smallest next step that can test the recommendation. Preserve the route or record identity, source versions, fixture details, reviewer, and disposition so later work can compare like with like instead of restarting from an undocumented assumption.`,
  `Do not confuse an implementation artifact with an outcome. A pull request, dashboard, test report, or runbook is valuable because it makes a decision inspectable, not because its existence proves quality. Reviewers should ask whether the artifact names the affected behavior, includes negative cases, identifies the owner, and can be refreshed when the dependency or product changes.`,
  `Time and sequence matter in interpretation. A first observation after a release may reflect warm-up, cached data, migration timing, or a temporary dependency condition. Record when the observation was made, what preceded it, and whether the same case was repeated. When comparing batches, keep the measurement method and inclusion rules stable or explain the difference explicitly.`,
  `The safest handoff also records unanswered questions. If a fixture omits a tenant type, a locale, a browser, a data volume, or a provider response, name that omission and state whether it blocks acceptance. A short list of bounded unknowns is more useful than a broad statement that the work is complete, because the owner can assign the next observation deliberately.`,
  `Evidence should be proportional to impact. A low-risk documentation correction may need a focused link and rendering check, while authorization, stored data, external side effects, and recovery paths need independent review and negative cases. This does not require every task to become a large test program; it requires the evidence to match the consequence of being wrong.`,
  `For an outsourced work lane, written evidence reduces avoidable context loss across time zones and review windows. The record should let the next programmer or owner understand what changed, why it changed, what was measured, what remains uncertain, and who can approve the next step. That continuity is especially important when the original contributor is unavailable.`,
  `A decision record should distinguish observation from interpretation. The measured result belongs in one field, the explanation in another, and the recommended action in a third. This separation helps a reviewer reject an attractive theory without discarding a reliable observation, and it prevents a proposed fix from being mistaken for proof that the diagnosis was correct.`,
  `Repeatability is a practical quality test for distributed work. A second authorized reviewer should be able to use the stated fixture, command, route, and expected result without private context from the original handoff. If reproduction fails, record the failure as evidence about the instructions or environment rather than silently changing the case until it passes.`,
  `Finally, retire stale evidence deliberately. Mark the release, dependency, source version, and review date so a later owner can tell whether the conclusion still applies. When a product boundary changes, reopen the relevant cases and preserve the earlier result as history instead of presenting it as current proof.`,
  `This research is a planning aid for teams working with outsourced programmers. It is not legal, tax, employment, privacy, accessibility-conformance, security, or operational advice. Validate the cited guidance against the actual product, contract, jurisdiction, threat model, data classification, and owner-approved change window before acting.`,
];

export const august13ReplacementResearchBatch: ReadonlyArray<ResearchPost> = [
  { slug: 'outsourced-server-component-boundary-study', title: 'Server-component boundary evidence for outsourced Next.js work', excerpt: 'Research on separating server and client responsibilities during distributed Next.js maintenance.', topic: 'Server components', published: '2026-08-13', body: body('server-component boundary behavior', 'server and client boundaries should be evaluated with route fixtures, authorization cases, and hydration evidence rather than with a compile result alone', 'a route under anonymous, authenticated, empty-data, and failure states', 'the study does not measure every browser, streaming condition, or provider integration'), sources },
  { slug: 'outsourced-wordpress-upgrade-compatibility-study', title: 'WordPress upgrade compatibility evidence for outsourced maintenance', excerpt: 'Research on testing plugin and theme interactions before a distributed WordPress change.', topic: 'WordPress upgrades', published: '2026-08-13', body: body('WordPress upgrade compatibility', 'compatibility evidence is strongest when version pairs, enabled extensions, critical journeys, and recovery artifacts are recorded together', 'a version pair exercised across the site’s named publishing and account journeys', 'a staging clone may not reproduce every hosting module, scheduled task, or extension configuration'), sources },
  { slug: 'outsourced-api-throttle-behavior-study', title: 'API throttle behavior research for outsourced engineering teams', excerpt: 'Research on measuring rate limits, backoff, and user-visible recovery in API work.', topic: 'API throttling', published: '2026-08-13', body: body('API throttle behavior', 'rate-limit research must record identity, window, response, retry guidance, and downstream effect instead of treating a limit number as the whole control', 'a request identity and endpoint tested across normal, burst, and recovery windows', 'provider limits and network timing can change outside the controlled test environment'), sources },
  { slug: 'outsourced-schema-change-rehearsal-study', title: 'Schema-change rehearsal evidence for outsourced database work', excerpt: 'Research on rehearsing database changes with compatibility, rollback, and data-integrity proof.', topic: 'Schema changes', published: '2026-08-13', body: body('database schema-change rehearsal', 'a migration is ready for review only when old and new application behavior, representative data, timing, and recovery boundaries are evidenced together', 'a migration version paired with representative rows and both application versions', 'a rehearsal cannot prove production lock duration or every live data distribution'), sources },
  { slug: 'outsourced-browser-error-triage-study', title: 'Browser error triage research for outsourced web support', excerpt: 'Research on turning frontend exceptions into reproducible, privacy-aware engineering evidence.', topic: 'Browser errors', published: '2026-08-13', body: body('browser error triage', 'frontend error work improves when exception identity, affected route, release, cohort, and reproduction evidence are separated from raw event volume', 'an exception signature joined to a route, release, browser cohort, and safe reproduction', 'telemetry sampling and privacy filters can hide rare devices or context needed for diagnosis'), sources },
  { slug: 'outsourced-object-storage-upload-study', title: 'Object-storage upload evidence for outsourced application work', excerpt: 'Research on upload validation, authorization, retention, and failure recovery.', topic: 'File storage', published: '2026-08-13', body: body('object-storage upload behavior', 'safe upload research must cover type validation, size boundaries, authorization, quarantine, failed transfer cleanup, and retrieval behavior as separate claims', 'a synthetic file and identity exercised through upload, rejection, retry, and retrieval states', 'provider scanning, storage policy, and network behavior may differ from the test fixture'), sources },
  { slug: 'outsourced-release-signal-readiness-study', title: 'Release-signal readiness research for distributed software teams', excerpt: 'Research on whether release telemetry can distinguish healthy rollout from silent failure.', topic: 'Release signals', published: '2026-08-13', body: body('release-signal readiness', 'a rollout signal is useful only when its owner, baseline, alert condition, missing-data behavior, and action path are explicit', 'a release cohort joined to route health, error, latency, and rollback observations', 'a short canary window cannot establish behavior under every traffic mix or delayed job'), sources },
  { slug: 'outsourced-export-reconciliation-study', title: 'Export reconciliation research for outsourced application teams', excerpt: 'Research on proving that exported records are complete, authorized, and repeatable.', topic: 'Data exports', published: '2026-08-13', body: body('data-export reconciliation', 'export confidence depends on a reconciled source count, filtered count, failure list, authorization check, and repeatability record', 'a bounded export job compared with source and destination identities over a stated period', 'counts can agree while field transformations, ordering, or late-arriving records remain untested'), sources },
  { slug: 'outsourced-locale-formatting-study', title: 'Locale and date-formatting regression research for outsourced web development', excerpt: 'Research on testing locale-sensitive text, numbers, dates, and layout without assuming one market.', topic: 'Locale formatting', published: '2026-08-13', body: body('locale and date-formatting behavior', 'locale testing should compare semantic value, timezone, direction, length, and assistive presentation instead of checking translated strings alone', 'a named locale and timezone exercised across representative dates, amounts, and text lengths', 'the selected locales cannot represent every script, font, device, or translation workflow'), sources },
  { slug: 'outsourced-queue-replay-safety-study', title: 'Queue replay safety research for outsourced application teams', excerpt: 'Research on retries, duplicate work, dead letters, and recovery ownership in queue-based systems.', topic: 'Queue replay', published: '2026-08-13', body: body('queue replay safety', 'replay confidence requires an idempotency rule, duplicate observation, dead-letter disposition, operator authority, and reconciliation evidence', 'a message identity followed through first delivery, retry, duplicate delivery, and recovery', 'an isolated queue cannot establish behavior under the production volume, ordering, or provider failure pattern'), sources },
];
