import type { ResearchPost } from './fleet-content';

const S={dora:['DORA research program','https://dora.dev/research/'] as const,google:['Google Engineering Practices','https://google.github.io/eng-practices/'] as const,nist:['NIST Secure Software Development Framework','https://csrc.nist.gov/Projects/ssdf'] as const,github:['GitHub pull request review documentation','https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'] as const,cisa:['CISA Secure by Design','https://www.cisa.gov/securebydesign'] as const,iso:['ISO/IEC/IEEE 29119 software testing overview','https://www.iso.org/standard/45142.html'] as const,otel:['OpenTelemetry documentation','https://opentelemetry.io/docs/'] as const};

const make=(thesis:string,notes:readonly string[]):readonly string[]=>[
 thesis,
 ...notes,
 'The study uses a frozen sample of real web, app, QA, and maintenance tickets over a named period. Each record retains its revision, work class, affected boundary, owner, reviewer, dependencies, access assumptions, state transitions, and expected result. Completed, blocked, reopened, rejected, and cancelled work is included where it affects the question. Missing timestamps are missing data, not facts to reconstruct from memory.',
 'The evidence separates implementation, review, owner decision, dependency waiting, and release authority. An outsourced programmer may prepare a patch, run an authorized check, reproduce a defect, or write a handoff. The client technical owner retains architecture decisions, sensitive access, customer-data handling, policy choices, merge authority, production release, and residual-risk acceptance.',
 'The primary measures are reported with denominators, observation windows, inclusion rules, and cohorts. Distributions and cause-specific counts are more useful than a single average. Routine documentation and maintenance should be separated from authentication, stored data, external effects, and release-adjacent work. A small sample supports precise cases and bounded inference, not a universal threshold.',
 'NIST SSDF, CISA Secure by Design, Google Engineering Practices, GitHub review records, and DORA research support methods for naming evidence, ownership, review, and delivery outcomes. They do not prove that a particular client complies with a framework or that one contributor caused an outcome. Each source is used only for the claim it actually supports.',
 'Negative and recovery states are tested where material with synthetic or masked fixtures, named identities, safe environments, and a reset path. The record names expected result, observed result, cleanup, and next owner when permissions are absent, dependencies fail, data is empty or malformed, requests repeat, or a reviewer rejects an assumption. A happy path cannot prove safe boundary behavior.',
 'Interpretation accounts for queue shape, reviewer availability, requirement quality, repository familiarity, dependency response, and owner decisions. These factors affect outsourced programming outcomes. Incidents, releases, staffing changes, and migrations are recorded as confounders. If evidence identifies a bottleneck, the next step is the smallest observation or bounded change that can distinguish competing explanations.',
 'A portable record links the source revision, route or ticket, fixture, test output, review discussion, limitation, and decision owner. Another authorized reviewer should be able to challenge the conclusion, reproduce the important check, or explain why reproduction is impossible under the access boundary. The existence of an artifact does not prove the quality of the behavior it describes.',
 'The conclusion is conditional on the named cohort, period, environment, and evidence rule. It does not establish that every browser, tenant, codebase, programmer, reviewer, dependency, or future release behaves the same way. This research is a planning aid, not legal, tax, employment, privacy, security, accessibility-conformance, or operational advice.',
 'Limitations include incomplete histories, staging differences, synthetic data that omits uncommon combinations, and short samples that overrepresent an incident or familiar contributor. Validate the cited guidance against the actual product, data classification, contract, jurisdiction, threat model, and owner-approved change window. Preserve excluded and failed cases so later readers can see the boundary of the claim.',
 'The practical decision is bounded: accept the evidence, narrow the work, collect a named missing observation, or escalate unresolved risk to the client owner. Refresh the result after a material system, dependency, reviewer, data, or policy change instead of presenting an old measurement as current proof.'
];

export const august17ResearchBatch:ReadonlyArray<ResearchPost>=[
{slug:'outsourced-programmer-queue-aging-study',title:'Queue aging in outsourced programming support',excerpt:'Research on whether aging tickets indicate capacity, unclear ownership, dependency delay, or weak intake.',topic:'Queue aging',published:'2026-08-17',body:make('Research question: when an outsourced programming ticket grows old, which observable cause best explains the delay? Queue age is ambiguous until decomposed into programmer work, review, owner decision, dependency, clarification, and explicit hold.',['Classify each interval from intake to completion and compare age with reopenings, review rounds, escaped defects, and scope changes. A ticket waiting for acceptance criteria is not equivalent to one in implementation.','DORA treats delivery as a system property, so the study tests whether aged work clusters around intake quality, reviewer availability, dependency response, or deliberate risk holds.','The useful output is a cause-specific queue profile and a named intervention, such as a reviewer field or better reproduction rule, followed by a re-measurement.']) ,sources:[S.dora,S.github,S.google,S.nist]},
{slug:'outsourced-programmer-scope-boundary-study',title:'Scope boundaries for outsourced programmer work',excerpt:'Research on distinguishing programming assignments suitable for outsourced execution from work requiring internal authority.',topic:'Scope boundaries',published:'2026-08-17',body:make('Research question: what evidence shows that an assignment is bounded enough for outsourced execution while consequential decisions remain with the client? Suitability is a property of design, access, reversibility, evidence, and authority.',['Classify proposed tickets by consequence if wrong, requirement uncertainty, access sensitivity, and reversibility; retain rejected examples as well as successful ones.','A bounded work sample tests whether the programmer identifies missing context, separates implementation from policy, and escalates hidden data or permission implications.','The boundary is not a job-title judgment: a small change can affect authentication or stored data, while a larger documentation change may be contained.']) ,sources:[S.nist,S.cisa,S.google,S.github]},
{slug:'outsourced-programmer-context-switching-study',title:'Context switching in outsourced programming support',excerpt:'Research on whether fragmented ticket assignment increases delay, review rework, or defect risk.',topic:'Context switching',published:'2026-08-17',body:make('Research question: how does switching among unrelated tickets affect outcomes for outsourced support? A switch is leaving active work before its next checkpoint, not every tab change or clarification.',['Record whether the first ticket had a clean checkpoint, uncommitted state, failed test, or unresolved question when interrupted.','Compare switch reasons, restoration time, review findings, repeated investigation, and reopened work across related and unrelated subsystems.','The goal is avoidable fragmentation, not suppressing incident response or reviewer escalation; a delayed but safer decision can be a positive outcome.']) ,sources:[S.google,S.github,S.dora,S.nist]},
{slug:'outsourced-programmer-escalation-threshold-study',title:'Escalation thresholds for outsourced programming decisions',excerpt:'Research on when a programmer should stop, ask for a decision, or continue under owner review.',topic:'Escalation thresholds',published:'2026-08-17',body:make('Research question: which observable conditions should trigger escalation during outsourced programming work? A useful threshold names consequence and authority rather than merely saying “uncertain.”',['Study access expansion, authorization, privacy, data mutation, external side effects, architecture, contradictory requirements, and absent test oracles as distinct triggers.','Measure timing, evidence quality, recipient, clarification rounds, and whether the owner decision was captured for reuse.','Calibration cases should include a small UI change with a hidden permission effect and a migration with an unclear recovery boundary.']) ,sources:[S.nist,S.cisa,S.google,S.github]},
{slug:'outsourced-programmer-evidence-portability-study',title:'Evidence portability across outsourced programming handoffs',excerpt:'Research on whether another authorized reviewer can reproduce a programmer’s evidence without private context.',topic:'Evidence portability',published:'2026-08-17',body:make('Research question: can an authorized reviewer reproduce the important part of evidence after the original work session ends? Portability requires claim, identity, setup, expected result, observation, and limitation.',['Sample screenshots, logs, test output, and review notes from real tickets, then test whether the next reviewer can locate the revision and repeat the claim.','Compare evidence types: a unit command may omit visual behavior, a screenshot may omit keyboard path, and a review comment may not prove the latest revision still passes.','A delayed reproduction records missing prerequisites, unavailable access, environment differences, and substantive disagreement without turning the exercise into a speed or memory test.']) ,sources:[S.google,S.github,S.nist,S.otel]},
{slug:'outsourced-programmer-maintenance-interruption-study',title:'Maintenance interruption cost in outsourced programming teams',excerpt:'Research on how unplanned support interruptions affect planned maintenance, review quality, and recovery time.',topic:'Maintenance interruptions',published:'2026-08-17',body:make('Research question: what is the measurable cost of interrupting planned maintenance with urgent support work? The cost includes context restoration and handoff ambiguity, not only calendar movement.',['At interruption, record revision, tests, changed files, unresolved questions, safe checkpoint, urgency reason, and owner who decides whether to resume.','Compare necessary incidents with avoidable queue churn and measure planned-ticket aging, repeated investigation, review findings, and incident benefit together.','A protocol with severity trigger, checkpoint note, named owner, and return decision is tested for lower recovery time without hiding legitimate urgent work.']) ,sources:[S.dora,S.nist,S.google,S.otel]},
{slug:'outsourced-programmer-knowledge-concentration-study',title:'Knowledge concentration risk in outsourced programming work',excerpt:'Research on detecting when critical repository knowledge depends too heavily on one contributor or reviewer.',topic:'Knowledge concentration',published:'2026-08-17',body:make('Research question: which evidence shows that a critical capability is concentrated in one outsourced contributor or one internal reviewer? Code ownership and commit history are clues, not proof of current capability.',['Inventory capabilities such as safe test execution, authorization review, queue diagnosis, route maintenance, and recovery explanation before counting primary and backup coverage.','A transfer exercise asks a second authorized person to reproduce a bounded task using existing evidence, while separating knowledge from credential access.','Weight one-person capabilities by consequence and time sensitivity; do not require every person to master every subsystem or share sensitive access casually.']) ,sources:[S.nist,S.google,S.github,S.cisa]},
{slug:'outsourced-programmer-qa-evidence-depth-study',title:'Evidence depth for outsourced programming QA',excerpt:'Research on matching QA evidence depth to consequence, state space, and recovery.',topic:'QA evidence depth',published:'2026-08-17',body:make('Research question: how much QA evidence is enough for a bounded outsourced change? Evidence depth depends on changed behavior, reachable states, consequence, and the test oracle, not raw case count.',['Classify normal, empty, invalid, unauthorized, dependency-failure, retry, and recovery states where relevant, recording explicit reasons for exclusions.','Inspect whether the expected result is actually correct for UI, API, data, accessibility, and QA-reporting claims; a passing test can assert the wrong behavior.','Compare risk class with observed and independently reviewed behavior classes, later review findings, reopened defects, and escaped failures in the claimed scope.']) ,sources:[S.iso,S.nist,S.cisa,S.github]},
{slug:'outsourced-programmer-requirements-ambiguity-study',title:'Requirements ambiguity in outsourced programming tickets',excerpt:'Research on ambiguous acceptance rules and their relationship to clarification, rework, and scope change.',topic:'Requirements ambiguity',published:'2026-08-17',body:make('Research question: which forms of ambiguity predict clarification, rework, or disputed acceptance? Ambiguity is not a writing-style score; it is missing decision information another authorized person needs.',['Classify undefined actor, success condition, error state, data lifecycle, dependency, non-goal, source of truth, and approval authority from tickets before implementation.','Measure clarification timing, review rounds, scope changes, reopenings, and acceptance disputes; early clarification may be a healthy outcome.','A useful brief makes actor, behavior, boundary, oracle, non-goals, and decision owner visible without pretending exploratory work has no unknowns.']) ,sources:[S.google,S.github,S.dora,S.nist]},
{slug:'outsourced-programmer-reviewer-load-study',title:'Reviewer load in outsourced programming teams',excerpt:'Research on whether reviewer demand, queue shape, and risk mix make review predictable and safe.',topic:'Reviewer load',published:'2026-08-17',body:make('Research question: how does reviewer load affect timeliness and depth for outsourced programming work? Load means risk-weighted demand and available review capacity, not a person’s total calendar occupancy.',['Record risk class, changed surface, requested reviewer, review window, competing incidents, findings, rounds, and whether review was independent.','Compare time to first review and decision with findings, reopened work, and downstream corrections; fast approval without outcome evidence is ambiguous.','Calibration examples can expose when one reviewer receives most permission, database, or release-adjacent changes, creating concentration as well as queue age.']) ,sources:[S.github,S.google,S.dora,S.nist]},
];
