import * as data from './data';
const dataAny = data as any;
const site = dataAny.site || {};
const footerItems = (dataAny.services || dataAny.roles || dataAny.industries || dataAny.blogPosts || []).slice(0,6);
const getTitle = (item: any) => typeof item === 'string' ? item : (item.title || item.name || item.label || item.question || String(item));
const getSlug = (item: any) => typeof item === 'string' ? item.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') : (item.slug || getTitle(item).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));
const domain = site.domain || 'this site';
const year = new Date().getFullYear();
export function JsonLd({data}:{data: any}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(data)}} />}
export function LogoMark(){return <span className="logo-mark-wrap"><img className="logo-img" src="/logo.svg" alt="" aria-hidden="true"/><span className="logo-name">{site.brand || domain}</span></span>}
export function Header(){return <header className="nav"><div className="nav-inner"><a className="logo" href="/" aria-label={`${site.brand || domain} home`}><LogoMark/></a><nav className="links" aria-label="Main navigation"><a href="/#workstreams">Services</a><a href="/#workstreams">Workstreams</a><a href="/blog">Guides</a><a href="/contact">Contact</a></nav><a className="btn nav-cta" href="/contact">Map the role</a></div></header>}
export function Footer(){return <footer className="footer legit-footer"><div className="footer-grid"><div className="footer-brand"><a className="footer-logo" href="/" aria-label={`${site.brand || domain} home`}><LogoMark/></a><p>{site.brand || domain} helps software teams define the tickets, repository rules, review ownership, and handoffs needed before they hire outside programmers.</p><p className="footer-note">This is an independent informational site. A request may be sent to a staffing team or service partner that can follow up about the role.</p></div><div><h3>Explore</h3><div className="footer-links">{footerItems.map((item:any,idx:number)=><a href={`/services/${getSlug(item)}`} key={idx}>{getTitle(item)}</a>)}</div></div><div><h3>Company</h3><div className="footer-links"><a href="/contact">Contact</a><a href="/blog">Guides</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms & Conditions</a><a href="/cancellation-policy">Cancellation Policy</a></div></div></div><div className="footer-bottom"><span>© {year} {site.brand || domain}. All rights reserved.</span><span>{domain}</span></div></footer>}
export function CTA(){return <section className="final-cta"><p className="eyebrow">Start with the backlog</p><h2>Define the role before you hire.</h2><p>Share the first tickets, stack, access limits, and review owner. We will use them to shape the programmer request.</p><a className="btn primary" href="/contact">Map the programmer role</a></section>}
