import type { ResearchPost } from './fleet-content';

type Study = Omit<ResearchPost, 'published'> & { body: string[] };
const date = '2026-10-02';

const paidTrial: Study = {
  slug:'outsourced-programmer-paid-trial-design-research-2026', title:'How should a company design a paid trial for an outsourced programmer?', excerpt:'A decision framework for representative work, fair measurement, secure access, and a useful stop condition.', topic:'Outsourced programmer paid-trial design', hero:'/research-heroes/2026-08-23/outsourced-release-observability-evidence-2026.png',
  body:[
`A paid trial is useful only when it samples the job the company needs while remaining small enough to review fairly. The central decision is not whether a candidate can produce a polished demo under unlimited conditions. It is whether both sides can learn how scope, questions, implementation, review, and revision work on a bounded assignment. For a Philippines-based programming role, the exercise should reflect the real repository and communication rhythm without exposing customers, production credentials, or an entire backlog. Write the decision the trial informs before choosing the task: proceed to a longer engagement, change the proposed lane, or stop with payment and feedback complete.`,
`This research compares official guidance on structured selection, secure development, and repository review with the site's service model. Facts come from the cited sources; the proposed trial is an analysis of those constraints, not a claim that one exercise predicts long-term performance. No candidate outcomes were available. The method therefore evaluates whether the process creates comparable evidence, not whether a score guarantees a successful hire. A good trial reduces uncertainty about a named work lane while leaving commercial terms, classification, and final hiring authority with the company. Sources were checked October 2, 2026.`,
`Map one normal work item into a trial brief. A frontend role might receive an accessible component defect with fixtures and acceptance states; a Node.js role could receive a failing contract test around a harmless endpoint; a WordPress role could receive a staging-only block correction. Avoid speculative architecture, emergency production work, secret business logic, or a task the company would otherwise need completed for free. State the timebox, payment, deliverables, allowed tools, environment, reviewer, and response window. If the company cannot explain how it will inspect the result, the assignment is not ready to send.`,
`A representative task needs controlled boundaries. Provide a disposable branch or exercise repository, synthetic data, local setup steps, supported versions, and observable acceptance criteria. Identify what is intentionally incomplete. The candidate should not have to guess whether pixel matching, tests, performance, or documentation matters most. Do not prescribe every edit: leave room to observe decomposition and questions. Record setup friction separately from implementation quality because a broken environment can consume the whole timebox and reveal more about the company's onboarding than the programmer.`,
`Use a scorecard tied to evidence rather than impressions. Useful dimensions are requirement interpretation, safety, correctness against named cases, clarity of tradeoffs, reproducibility, and response to one review cycle. Each dimension needs an anchor: tests that pass for the right reason, a concise pull-request note, no unrelated file changes, or a revision that addresses the comment without creating a regression. Fluency in a video call, rapid typing, or similarity to the reviewer's personal style should not substitute for work evidence. Apply the same core rubric and comparable assistance to candidates for the same lane.`,
`Security boundaries should resemble the eventual model at smaller scale. Use a named account with least repository access, require multi-factor authentication where supported, and exclude deployment, billing, secrets, customer records, and production logs. Seed synthetic records. Ask for dependency additions to be justified. Inspect the diff, lockfile, generated files, and test commands. A successful exercise does not justify wider access automatically; access grows only when a later task requires it and an accountable owner approves it.`,
`Communication evidence should come from work, not surveillance. A short kickoff confirms assumptions and working hours. Evaluate whether the programmer raises material ambiguity, reports a blocker early, and leaves a handoff another engineer can reproduce. For an asynchronous Philippines-to-client handoff, an end-of-day update names completed evidence, the next step, and a decision needed from the owner. That tests the actual coordination boundary without equating an accent, camera style, constant presence, or instant response with engineering quality.`,
`The review cycle is part of the trial. Give one or two actionable comments and distinguish defects from preferences. Observe whether the candidate can reproduce the issue, explain the correction, and update relevant scope. Record when the requirement itself changed; a moving target cannot fairly count as a candidate miss. If the change is acceptable but differs from a preferred implementation, score acceptance evidence and tradeoff rather than conformity. End at the promised timebox instead of quietly turning the exercise into days of unpaid revisions.`,
`Payment and ownership must be explicit first. State amount, currency, timing, invoice needs, and rights after payment. A trial creating usable production value should be priced and governed as real work. Contractor classification, tax, benefits, local labor rules, privacy, and intellectual property require qualified advice; a technical scorecard cannot resolve them. Do not condition payment on selection, do not reuse rejected work outside agreed terms, and preserve the brief and acceptance record.`,
`The decision memo separates observation from inference. Facts include revision, trial window, commands, results, review comments, and explanations. Analysis maps those facts to the rubric. Inference estimates performance on a broader backlog. Uncertainty includes unfamiliar domain context, an artificial repository, limited collaboration, and inaccessible systems. “Strong programmer” is too broad; “demonstrated a safe, reviewable React defect fix in the provided environment” is defensible.`,
`A trial also audits the buyer. Repeated setup failures, contradictory reviewers, missing criteria, delayed answers, or requests for privileged access are signals about the future engagement. Track owner response and brief changes alongside candidate work. If every candidate asks the same unanswered question, improve the role and onboarding rather than lower scores. A staffing conversation should start with recurring tasks, tools, schedule, decision limits, and finished-work examples because those inputs make selection and delivery more reliable.`,
`Limitations: a short exercise cannot establish long-term reliability, production judgment under real pressure, team compatibility, or performance across unfamiliar systems. It can disadvantage candidates needing accommodations unless the process offers them. It may reward familiarity with one framework. Use it as one structured sample alongside references, portfolio discussion, and role-specific interviews. EEOC material supports job-related selection principles; NIST and GitHub define software and review controls. They do not prescribe this trial or validate a candidate.`,
`Approve a paid trial only when the company can name the role decision, representative task, compensation, access envelope, comparable rubric, reviewer, and stop condition. Return the brief when setup or scoring is ambiguous. Decline when it asks for production authority or uncompensated business value. A Philippines-based specialist can demonstrate a real work lane while the company retains hiring, legal, merge, and release decisions. The useful outcome is a reproducible work sample, not a miniature project disguised as selection.`,
`Before comparing submissions, calibrate the reviewers on one reference response or a deliberately seeded example. Ask each reviewer to score independently, then discuss differences in how they interpreted the anchors. Preserve those differences rather than adjusting a candidate's score after learning who produced the work. If the exercise allows documentation, internet research, accessibility tools, or coding assistants, state that policy uniformly and ask for verification of the resulting code instead of trying to infer tool use from writing style. Accommodations can change the interaction format without weakening the job-related evidence. A candidate who identifies an unsafe requirement and proposes a bounded alternative may demonstrate more relevant judgment than one who completes every literal instruction. The final decision should record which evidence changed the initial view, what remained untested, and why the proposed next work lane is proportionate. That audit trail makes a rejection explainable and an acceptance easier to onboard, while still avoiding unsupported promises about future performance.`,
  ],
  sources:[['EEOC Employment Tests and Selection Procedures','https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures'],['NIST Secure Software Development Framework','https://csrc.nist.gov/Projects/ssdf'],['GitHub pull request reviews','https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'],['OWASP Developer Guide','https://devguide.owasp.org/']], related:['outsourced-programmer-knowledge-transfer-acceptance-test','philippines-outsourced-programmer-timezone-handoff','remote-dependency-inventory-review'], nextStep:{heading:'Turn a real task into a fair trial brief',copy:'Bring one recurring task, its constraints, and a finished-work example to the staffing intake.',href:'/contact',label:'Start the staffing intake'}
};

const access: Study = {
  slug:'outsourced-developer-repository-access-research-2026',title:'What repository access should an outsourced developer receive?',excerpt:'A least-privilege model that separates source contribution, automation, merge rights, and production authority.',topic:'Outsourced developer repository access',hero:'/research-heroes/2026-08-23/outsourced-dependency-provenance-review-2026.png',
  body:[
`Repository access is not a binary choice between trust and no trust. It is a set of capabilities: seeing code, creating branches, opening pull requests, running automation, reading issues, managing settings, approving changes, merging protected branches, accessing secrets, and triggering releases. A company hiring a Philippines-based programmer should assign only what the first work lane requires, then expand from observed need. The question is not “Can this person have GitHub?” It is “Which named actions must this role perform, on which repositories and environments, with which review and recovery controls?”`,
`This study uses threat-and-task mapping. Define expected work and assets, map every task to platform permissions, test normal delivery and prohibited boundaries with a disposable account, and record owner-only actions. GitHub and NIST establish platform behavior and security principles. The recommended matrix is an inference for outsourced delivery, not a universal model. No client access logs were used and no incident reduction is asserted. Sources were checked October 2, 2026.`,
`Inventory before inviting. List repositories, forks, packages, Actions, environments, issue trackers, wikis, code owners, branch rules, deploy keys, installed apps, and external CI. Classify them by the assigned work. A shared monorepo may expose customer code or infrastructure unrelated to the task, making read access broader than it appears. If a task can be isolated safely, prefer a scoped repository or sanitized fixture. Never copy secrets or customer data into a new repository merely to simplify administration.`,
`Use a named individual identity, supported multi-factor authentication, and no shared credentials or tokens passed through chat. Organization membership and outside-collaborator models create different visibility; choose deliberately and document removal ownership. Verify invitations through an approved channel. A profile name is not proof. Record account, repository, role, start date, approver, business reason, and review date in an access register without storing authentication material.`,
`Routine feature work often needs read access plus a branch or fork and pull-request creation. Protect production branches from direct writes, require review for material changes, and keep rule administration with a company owner. The programmer may read CI results without editing secrets or bypassing checks. Test the exact identity: clone, create a work branch, open a draft, receive review, and attempt one explicitly prohibited action. Documentation screenshots are weaker than a boundary test because inherited team membership changes effective access.`,
`Automation creates another authority plane. A pull request can cause workflows to read tokens, publish packages, comment externally, or deploy previews. Inspect triggers, fork behavior, environment approvals, and whether untrusted code reaches secrets. Write access may permit workflow edits, so human approval or restricted environments remain important. Masking log values does not make arbitrary code safe. Use low-risk preview credentials, synthetic data, and owner-approved production environments.`,
`Separate review from merge and release. An outsourced senior developer may provide valuable approval while the company requires a staff owner for protected branches. Allowing merge need not imply deployment. Write the split in branch rules, code owners, and runbooks. Emergency bypass should be attributable, time-bounded, and reviewed. If the platform cannot express the desired separation, add an external approval or narrow the work lane rather than rely on an unwritten promise.`,
`Issue access can leak as much as source. Tickets may contain customer details, vulnerability reports, pricing, credentials pasted by mistake, or plans outside the role. Scope boards and chat channels along the same task boundaries. Provide a private vulnerability route. A programmer discovering a secret in history should escalate without copying it elsewhere. Rotation and cleanup remain company incident decisions, while the developer can identify affected revisions and remove active references.`,
`Review access after the first pull request, any lane expansion, and at a fixed recertification interval. Compare permission with recent work instead of merely asking whether it is still needed. Give stale memberships, dormant tokens, unused deploy keys, and automation ownership explicit dispositions. Removal is not a judgment about the programmer; it is normal when a task no longer requires a capability.`,
`Offboarding begins before the final day. Identify company-owned branches, open reviews, packages, documentation, outstanding credentials, and scheduled automation. Transfer ownership, then remove repository, issue, chat, VPN, cloud, and vault access through authoritative systems. Revoke tokens even if expected to expire. Test that the identity no longer reaches resources and that builds do not depend on a personal fork or user-owned secret.`,
`The access matrix distinguishes fact, analysis, and uncertainty. A platform role and denied-action test are facts. Sufficiency is analysis against the task map. Unknown installed apps, inherited policy, self-hosted runners, undiscovered secrets, and untested external systems are uncertainty. Record exceptions with owner and expiry. “Least privilege” alone is not evidence; exact allowed and denied actions are.`,
`Limitations include changing platform models and integrations that extend authority beyond the user interface. A test repository may not reproduce enterprise policy or production runners. Small teams may require one person to merge, but that is an explicit risk choice with review and rollback. GitHub describes roles, branches, and Actions security; NIST describes account management. Neither knows the company's architecture or contract. Qualified owners must address regulated data.`,
`Approve access only when a work lane maps to exact repositories, capabilities, automation exposure, owner-only actions, and removal timing. Return requests for admin “just in case.” A Philippines-based developer can own branches, pull requests, tests, and documentation while a company owner retains secrets, rules, protected-branch exceptions, production environments, and commercial decisions. Location or employment model never substitutes for sound identity engineering.`,
`A concrete access worksheet should contain one row per action rather than one row per job title. “Read application source,” “create a branch,” “trigger an unprivileged preview,” “view a failed test log,” “approve a dependency update,” “merge main,” and “approve production” are separate actions with separate evidence. For each row, name the repository or environment, granting mechanism, approver, test, review date, and revocation event. Then inspect privilege escalation paths: team maintainers who can add members, workflow editors who can print tokens, package maintainers who can replace a dependency, and cloud identities assumed from CI. This catches authority hidden behind a modest repository label.`,
`Use time-bounded elevation for the unusual task. If a developer must inspect a protected setting or recover a release, open a ticket describing the reason, grant the smallest temporary capability, observe the action through platform logs, and remove it at the promised time. Do not leave elevated access in place because another incident might occur. For unavailable staff, use company-controlled break-glass identities with post-use review, never the departed contributor's session. The access register should also distinguish user credentials from machine credentials: rotating one person's token does not retire a deploy key, GitHub App installation, runner registration token, or cloud federation rule. A final reviewer should reconcile the platform's effective membership and integration list against the register. That comparison, plus an actual denied-action test, supports a bounded conclusion that the intended lane works without unnecessary production authority.`,
`Forks and local clones need an explicit data lifecycle. Decide whether private repository forking is allowed, where company code may be stored, whether full history is necessary, and how local copies are removed when the lane ends. Device controls should be proportional to the sensitivity of the source and agreed before access is issued. If the programmer uses a supplier-managed device, the company still needs a verifiable offboarding path rather than an unsupported promise that files were deleted. Avoid demanding invasive personal-device inspection; instead supply an approved managed workspace when stronger controls are required. Review package publishing separately from source contribution because a maintainer token can affect downstream users even without main-branch access. Require protected release workflows, provenance where supported, and an owner approval for public packages. Finally, rehearse a lost-device or compromised-token scenario: revoke the named credential, inspect platform audit events, rotate any exposed machine secret, and confirm normal contribution continues through a new approved identity. This demonstrates recoverability without granting a permanent administrative role.`,
  ],sources:[['GitHub repository roles','https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization'],['GitHub protected branches','https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches'],['GitHub Actions security hardening','https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions'],['NIST SP 800-53 Rev. 5','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final']],related:['outsourced-developer-production-incident-access-decision','software-development-access-governance-research','outsourced-developer-ai-coding-assistant-boundaries'],nextStep:{heading:'Define the first repository lane',copy:'List the repositories, task type, review owner, and actions the role must perform.',href:'/services/devops-support',label:'Review DevOps support'}
};

const review: Study = {
slug:'outsourced-programmer-code-review-service-level-research-2026',title:'How fast should a company review an outsourced programmer’s pull request?',excerpt:'A review service level that protects flow without rewarding shallow approval or permanent interruption.',topic:'Outsourced programmer code-review service level',hero:'/research-heroes/2026-08-23/outsourced-api-contract-drift-evidence-2026.png',
body:[
`A review service level is a promise about process, not a guarantee every pull request merges by a fixed hour. Across time zones, the damaging delay is often an unanswered decision that blocks the next task. A useful policy defines queue entry, a substantive first response, risk-based reviewers, and absence coverage. The target should encourage small prepared changes and thoughtful feedback instead of one-word approvals issued to protect a dashboard.`,
`The method maps arrival windows, reviewer capacity, risk, size, dependencies, and response types. Observe time from ready-for-review to first substantive response and then disposition. DORA informs feedback concepts; GitHub documents mechanics; Google documents review practices. None supplies a universal number. No internal pull-request dataset was available, so recommended windows are hypotheses to test, not a benchmark or productivity claim. Sources were checked October 2, 2026.`,
`Define readiness before measuring. A pull request identifies its issue, scope, user effect, tests, useful screenshots or logs, risk, rollback concerns, and open decisions. Required automation is running or has a documented exception. Draft work should not consume the same queue. The author marks readiness; a reviewer can return it with a specific missing item. This makes the metric actionable instead of blaming a reviewer for work that could not be evaluated.`,
`Segment risk and size. Documentation, a component fix, authentication change, migration, and infrastructure policy should not share one clock. Low-risk changes can target a response within one overlap window. Higher-risk work may require scheduled security, data, or platform review. Large changes should be decomposed or reviewed in stages. The aim is predictable attention, not an average hiding a migration behind tiny edits.`,
`A substantive response is approval, a bounded change request, an acceptance-related question, or a scheduling notice naming reviewer and time. Emoji, automation, and “later” without ownership do not close the clock. Comments should distinguish correctness, security, maintainability, and preference. Label unwritten preferences non-blocking. This reduces cycles where cosmetic revisions hide unresolved product decisions.`,
`Timezone design should use handoff windows rather than permanent overlap. A Philippines-based contributor can prepare a packet before the client's day. The client assigns a daily reviewer window and returns consolidated feedback. The contributor then has an unblocked revision or another scoped ticket. Urgent defects need a separate severity threshold, channel, and owner. Do not turn every pull request into an emergency or require responses outside agreed schedules.`,
`Reviewer capacity is a planning input. Count ready changes, review effort, specialist bottlenecks, and interruptions. Reserve review time. Code ownership can route work, but needs a backup. If one architect is required for everything, the constraint is organizational; measuring developer output will not remove it. Managers can reduce arrivals, train reviewers, narrow ownership, or change the target, but should not demand approvals from people who cannot understand the change.`,
`Measure distributions and aging rather than only averages. Record readiness, first response, review cycles, disposition, and blocked-owner intervals by risk class. Report median, an upper percentile, oldest items, and reasons. Pair speed with escaped defects, reopen rates, reverts, and findings. Faster response plus more rollback is not evidence of improved delivery.`,
`Sample feedback quality. Check whether comments cite criteria, describe a reproducible problem, give proportional guidance, and exclude sensitive data. Consolidate related comments. Authors may challenge requests with evidence; owners resolve conflicting reviewers. Repeated debate about an unwritten convention should produce a documented standard or automated check instead of forcing a remote contributor to memorize preferences.`,
`Create escalation before a miss. Near target, notify the reviewer. At target, route to backup or manager. A product or security decision remains blocked on its accountable owner; substitutes should not guess. If delay threatens a commitment, the company reschedules or rescopes. The developer preserves the branch and evidence but must not bypass protection or self-approve because the queue is late.`,
`Facts are timestamps, states, classification, comments, test results, and disposition. Analysis identifies bottlenecks. Inference estimates why a class waits longer and should be checked against threads. Unknown offline work, hidden workload, drafts, and complexity are uncertainty. Do not rank individuals from review latency: it emerges from the brief, author, automation, reviewers, and owners.`,
`Limitations: small teams have volatile arrival rates, and one release can dominate a month. Tools may not know when work was ready or analysis happened offline. Repositories need different controls. DORA, GitHub, and Google offer concepts but no outsourced-team hour target. Begin with a staffable service level, inspect misses after several weeks, and revise transparently rather than advertise an unsupported benchmark.`,
`Publish the queue rules where contributors and reviewers can challenge them. Adopt a service level only when readiness, risk classes, substantive response, coverage, backup, escalation, and quality measures are written. Start with daily review windows for routine work and scheduled specialist review for riskier changes, then tune from evidence. A Philippines-based programmer owns a prepared handoff and responsive revision; the company owns reviewer capacity, decisions, merge, and release.`,
`A practical pilot can run for four weeks without pretending to establish an industry benchmark. During week one, tag ready changes by risk and record arrival patterns without enforcing a target. In week two, reserve two reviewer windows and assign backups. In weeks three and four, inspect every miss with reason codes such as missing brief, failing automation, unavailable specialist, unresolved product decision, oversized change, or author revision. Do not use “developer delay” or “reviewer delay” when a more precise queue state exists. Compare the oldest items and repeated reasons at the weekly operating review.`,
`The company also needs a rule for partial review. A reviewer may validate interface behavior while deferring data migration or security boundaries to another owner. Record reviewed scope and remaining gates instead of presenting the first approval as complete. When several pull requests form a dependent stack, state whether later work may proceed before the base is approved and how rebases affect earlier evidence. For urgent corrections, shorten the queue through an incident route but preserve two-person review where risk requires it. For abandoned changes, close them with a reason so aging metrics do not become a graveyard. The best service level makes blocked decisions visible early and gives the outsourced contributor useful next work. It does not force every comment, approval, merge, and release into one clock or treat faster typing as a substitute for available decision owners.`,
`Review rework can reveal whether the intake itself is healthy. Sample changes with three or more cycles and label why each cycle happened: a missed acceptance case, late product requirement, conflicting review, incomplete test evidence, architectural discovery, or a defect introduced by revision. Do not count all cycles against the author. If late requirements dominate, move a product checkpoint before implementation. If reviewers repeatedly find the same test omission, improve the ready checklist or create a repository-specific example. If architecture questions surface after a large diff, introduce a short design note before code. The service-level report should show time controlled by the author separately from time awaiting company decisions, while avoiding surveillance of active minutes. It should also record when a review found a serious defect; longer attention may be exactly the desired result for high-risk work. This qualitative sampling prevents managers from gaming a response metric by splitting comments, approving prematurely, or pressuring authors to reduce questions. The operating goal is a trustworthy decision with predictable cadence.`,
],sources:[['DORA continuous delivery','https://dora.dev/capabilities/continuous-delivery/'],['GitHub pull request reviews','https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'],['Google code review','https://google.github.io/eng-practices/review/'],['Google review speed','https://google.github.io/eng-practices/review/reviewer/speed.html']],related:['software-development-review-consistency-research','software-development-handoff-reliability-research','outsourced-programmer-knowledge-transfer-acceptance-test'],nextStep:{heading:'Build review capacity into the role',copy:'Define readiness, daily handoff window, primary reviewer, and backup before work begins.',href:'/contact',label:'Discuss the role'}
};

const flaky: Study = {
slug:'outsourced-qa-flaky-test-ownership-research-2026',title:'Who should own flaky tests in an outsourced QA engagement?',excerpt:'A containment and repair model that keeps retries from hiding risk or making QA own every system defect.',topic:'Outsourced QA flaky-test ownership',hero:'/research-heroes/2026-08-23/outsourced-accessibility-regression-evidence-2026.png',
body:[
`A flaky test produces inconsistent outcomes without a relevant system change. The cause may be product, test, data, environment, dependency, runner, or expectation. Assigning every intermittent failure to outsourced QA is a category error. Ownership follows the evidence needed to remove uncertainty: QA can reproduce, classify, contain, and improve automation, while developers, platform owners, or service owners repair causes in their systems. The release owner decides whether risk permits a temporary exception.`,
`Methodology: define a failure taxonomy, preserve the first occurrence, vary one condition at a time, and route the defect to the demonstrated boundary. Playwright documents artifacts and retries; Google and pytest provide established flaky-test approaches. This routing model is analysis, not a standard they mandate. No client run history was available, so no failure-rate or savings claim is made. Sources were checked October 2, 2026.`,
`Preserve before rerunning. Save test and application revisions, runner image, browser versions, seed, workers, shard, locale, timezone, flags, synthetic account, network conditions, trace, video, screenshot, console, server logs, and timestamps. Sanitize secrets and personal data. A later pass does not erase the failure. If retries are automatic, report the initial attempt and retry disposition separately so the decision sees both instability and eventual outcome.`,
`Classify with controlled experiments. A locator may fail under concurrency; shared data may collide across shards; an application race may reproduce manually; an external sandbox may throttle. Vary worker count, order, seed, browser, network, dataset, clock, and dependency mode one at a time, then restore the suspected condition. Calling a failure environmental without evidence simply transfers responsibility to an unnamed owner.`,
`Containment protects signal. Move the test to a visible non-blocking lane, reduce concurrency, replace an unreliable dependency with an approved contract fixture, or pin a version temporarily. Quarantine records test, signature, first occurrence, impact, owner, expiry, and exit criteria. Deleting the test or adding unlimited retries removes the warning. Preserve affected coverage through a stable lower-level check or named manual control where feasible.`,
`Route by causal boundary. QA owns unstable selectors, leaked state, invalid waits, order coupling, and fixture cleanup. Feature teams own product races. Platform teams own controlled runner capacity, clock, container, browser distribution, and networking. External sandboxes may need an incident or stub. While cause is unknown, appoint an investigation owner. The release owner alone decides whether a required check may be waived.`,
`Retries have a narrow diagnostic role. They can collect a trace and reveal variation, but cannot convert nondeterminism into a passing control. Track retry-only passes and set escalation. Tests with real side effects can duplicate data unless fixtures and idempotency are safe. Never aim an experimental suite at production customers, payments, messages, or irreversible workflows merely to estimate frequency.`,
`Repair the demonstrated cause. Replace sleeps with bounded assertions on user-visible readiness or protocol events. Isolate data by worker. Freeze time only when product behavior permits it. Seed randomness. If the product races, add a regression failing before the application patch. After correction, repeat the original configuration and stress-oriented variations; one green run proves one outcome, not reliability.`,
`Measure unique flaky tests, affected runs, initial failures, retry-only passes, quarantine age, recurrence, and blocked release minutes. Group identical signatures so one infrastructure event does not appear as hundreds of defects. Show oldest quarantines and expired exceptions. A lower rate after deleting difficult coverage is not improvement; a rise after enabling detection may be visibility.`,
`The handoff includes smallest failing command, fixtures, artifacts, excluded factors, owner, containment, correction, verification runs, uncertainty, and deadline. A Philippines-based QA lane can send an asynchronous summary of new signatures, aged quarantines, owner responses, and release blockers. The company must provide safe environments and accountable feature owners, or QA becomes a reporting queue without resolution.`,
`Separate language: a trace showing a disabled button after API success is fact. A missed state update is analysis needing experiment or code evidence. Higher frequency under load is inference until measured. Unknown runner saturation and unavailable logs are uncertainty. Intermittent failures invite confident stories based on the latest pass, so retain competing explanations until controlled evidence rules them out.`,
`Limitations: repetitions estimate observed instability but cannot prove no recurrence. Fixtures may remove integration behavior, while sandboxes add uncontrolled variation. Frameworks evolve. Playwright, pytest, and Google do not assign contractual responsibility. Agreements should define response expectations, but technical ownership remains attached to systems and evidence rather than vendor labels.`,
`Review the register in the release forum that can assign product and platform owners, fund repairs, and reject expired waivers before the next release candidate. Use a shared flaky-test register with investigation owner, causal owner, release owner, containment expiry, and repair evidence. Outsourced QA can own detection, artifacts, test-side corrections, and verification. It should not silently waive a failed control or accept every application defect. The company keeps risk acceptance and release authority, ensuring an intermittent failure remains visible until explained, repaired, replaced, or consciously retired.`,
`An investigation matrix should begin with negative controls. Run an adjacent stable test under the same worker, browser, dataset, and network so a broad environment failure is not mistaken for one test's defect. Run the suspect behavior through a narrower API or component check to separate user-interface synchronization from server state. Repeat with a fresh identity and with the original failing identity if policy permits. If only one account fails, preserve its synthetic state before cleanup. If all tests on a runner fail, stop spending cycles on selector changes and route the incident to the platform boundary.`,
`Statistical language needs care. Ten passes do not prove stability, and one failure does not estimate a population rate well. Record the number of attempts, configuration, and confidence limits only if the team has enough observations and a defined sampling scheme. Otherwise report the outcomes plainly. Repair verification should include the original seed and order, several alternative orders, supported browsers, and the concurrency that exposed the problem. Reopen a supposedly repaired item when the same signature returns; do not create a fresh ticket that hides recurrence. Before removing quarantine, ensure the test still fails when its protected behavior is deliberately broken in a safe fixture. This mutation-style check guards against a “repair” that merely weakened the assertion. The decision owner can then see whether the control regained sensitivity, whether residual nondeterminism remains, and which customer-relevant behavior would be unprotected if the test were retired.`,
`Environment ownership deserves its own contract. Record who updates browser images, resets test tenants, maintains seed data, renews certificates, monitors sandbox quotas, and announces maintenance. Without those owners, QA may compensate for stale infrastructure inside tests until the suite becomes harder to understand. Use immutable runner versions for a diagnostic window, then test upgrades deliberately rather than allowing silent drift. For parallel suites, define namespaces for accounts, orders, files, queues, and email sinks so cleanup from one worker cannot erase another worker's evidence. Cleanup should be safe to repeat and restricted to the current synthetic namespace. If a run stops abruptly, a scheduled janitor can report and remove expired fixtures without masking the original failure. These controls turn “the environment was flaky” into specific observations: a certificate expired, a tenant exceeded quota, or two workers shared an identifier. Only then can the correct owner repair the boundary and QA verify the restored behavior.`,
],sources:[['Playwright retries','https://playwright.dev/docs/test-retries'],['Playwright Trace Viewer','https://playwright.dev/docs/trace-viewer'],['Playwright isolation','https://playwright.dev/docs/browser-contexts'],['pytest flaky tests','https://docs.pytest.org/en/stable/explanation/flaky.html'],['Google Testing Blog: Flaky Tests','https://testing.googleblog.com/2016/05/flaky-tests-at-google-and-how-we.html']],related:['software-development-review-consistency-research','outsourced-release-observability-evidence-2026','outsourced-accessibility-regression-evidence-2026'],nextStep:{heading:'Scope an evidence-led QA lane',copy:'Name critical journeys, environments, artifacts, feature owners, and release owner.',href:'/services/qa-automation',label:'Review QA automation'}
};

const continuity: Study = {
slug:'outsourced-programmer-continuity-bus-factor-research-2026',title:'How can a buyer reduce key-person risk with an outsourced programmer?',excerpt:'A continuity test built on reproducible work, owner-controlled access, and recovery drills.',topic:'Outsourced programmer continuity and key-person risk',hero:'/research-heroes/2026-08-23/outsourced-database-migration-rehearsal-evidence-2026.png',
body:[
`Key-person risk exists when important work cannot continue without one person's knowledge, identity, device, approval, or relationship. Outsourcing does not create the risk, and an internal hire does not remove it. Ask whether another authorized engineer can understand the work, reproduce the environment, operate the normal workflow, and recover a bounded service without borrowing personal accounts. For a Philippines-based engagement, continuity belongs in tickets, repositories, access, and review cadence from the first week, not a rushed document at contract end.`,
`This research applies continuity and secure-development principles to a software lane. Inventory critical outcomes, map single dependencies, define minimum evidence, and run a controlled absence drill. NIST supports contingency and secure development; CISA supports resilient design; Google SRE informs operational ownership. The proposed test is an inference, not certification. No internal recovery data existed, so no duration or availability promise is made. Sources were checked October 2, 2026.`,
`Inventory by outcome, not person. Identify repositories, build tools, registries, environments, infrastructure, vaults, domains, vendors, data stores, jobs, alerts, approvals, and commercial owners. Mark who can read, change, approve, pay, and recover each item. Personal email, private forks, local-only scripts, unshared MFA devices, and undocumented vendor relationships are continuity defects even when daily delivery looks smooth. Reference credentials in owner-controlled systems; never copy them into the inventory.`,
`Define a reproducible work packet. A new authorized engineer obtains approved source, installs supported dependencies, configures synthetic data, runs focused tests, understands the deployment path, and finds recent decisions. Pin versions and explain non-obvious services. Keep example environment files secret-free. Explain generated artifacts. Name what cannot run locally and who owns a safe non-production equivalent.`,
`Tickets and pull requests carry operational memory. A completed item connects requirement, revision, acceptance evidence, reviewer, and follow-up risk. Design choices need short decision records with context, alternatives, consequence, and status. Capture decisions another engineer would otherwise reverse-engineer, not every conversation. The company owns these systems of record; personal notes cannot be the only memory for maintained software.`,
`Access continuity requires redundancy with control. At least two suitable company-controlled identities should administer critical repositories, domains, cloud accounts, registries, and vaults. Contributors still receive least privilege. Recovery codes and break-glass procedures live in an audited secure system. Test that ownership transfers without approval from the programmer's personal device. Redundancy does not mean universal admin rights; it removes dependence on one unavailable identity.`,
`Run a planned absence drill on a low-risk task. The primary programmer stops participating for the exercise window. A second authorized engineer uses the packet to set up, diagnose a seeded harmless defect, prepare a correction, run tests, and write a release handoff without deploying. Measure questions, missing access, stale commands, hidden assumptions, and owner decisions. The goal is gap discovery, not substitute speed.`,
`Operational continuity needs a separate drill. Choose a non-production alert or job and trace detection, triage, escalation, mitigation proposal, rollback instructions, and evidence preservation. Keep production execution with the owner. A runbook containing commands but no thresholds is dangerous: someone may know how to restart without knowing when integrity requires stopping. State prerequisites, safe observations, prohibited actions, impact owner, and exit conditions.`,
`Measure recovery capability, not document volume: critical systems with two administrators, clean-environment setup success, validated-runbook age, unresolved access gaps, time to prepare a reviewable drill change, and decisions requiring the absent person. Count stale procedures honestly. A hundred unexecuted pages are weaker than a concise guide another engineer used. Revalidate after major platform, dependency, vendor, or team changes.`,
`Commercial continuity should be explicit and proportionate. With qualified advice, define notice, handover, company-owned artifacts, data return or deletion, replacement requests, final payment, and removal. Do not rely on punitive lock-in or permanent availability. The model should tolerate leave, time zones, illness, and role changes. A supplier may offer replacement capacity, but the buyer still needs owner-controlled accounts and review knowledge.`,
`The report separates observation from prediction. Clean setup, completed drill, and tested administrators are facts. Analysis identifies workflows that could continue. Inference estimates resilience during real absence. Unknown vendor behavior, production-only behavior, undocumented expertise, and events outside the drill are uncertainty. Do not claim the bus factor is fixed; name the tested route, date, and remaining single points.`,
`Limitations: drills simplify real pressure, substitutes may share hidden context, and access redundancy can increase attack surface if ignored. Specialized systems may require a vendor or restoration contract rather than duplicated expertise. NIST, CISA, and Google do not validate an outsourcing provider or contract. Legal, privacy, and retention decisions remain with qualified owners.`,
`Record the drill result, corrections, and next review date in the company system of record. Approve an ongoing lane when source, artifacts, identities, decisions, and recovery paths are company-controlled and a second authorized person has exercised the minimum workflow. Return a plan consisting only of a final handover promise. The programmer owns accurate work evidence; the company owns systems of record, administrator redundancy, risk acceptance, and release. Continuity becomes a routine delivery property rather than a document assembled after access disappears.`,
`Choose recovery objectives at the level of a business capability. The ability to edit source within four hours is different from restoring a public service, resuming scheduled billing, or answering a security alert. For each critical lane, name the maximum tolerable interruption, the latest acceptable data state, and the owner who can accept a longer gap. Then design the drill around prerequisites that influence those outcomes. A repository clone is not continuity evidence when the package registry, database backup, signing key, or domain account remains tied to the absent person.`,
`Continuity work should also avoid creating a shadow organization. Do not duplicate secret copies, fork production code into personal accounts, or create unmonitored administrator identities merely to raise a redundancy count. Use the existing company vault, identity provider, repository organization, backup system, and issue tracker. Rotate drill fixtures after use and close temporary access. When a procedure fails, preserve the safe evidence and correct the authoritative guide rather than circulating another private checklist. Schedule the next drill based on risk: after an ownership change, major platform migration, failed restoration, or material dependency shift. A successful handoff is demonstrated when the substitute can state what is safe to do, what requires owner approval, and what remains unknown, not when the person improvises a production change. This distinction protects service continuity and preserves decision accountability during an actual absence.`,
`Supplier continuity and technical continuity should be tested separately. A provider may nominate another programmer quickly, yet the replacement can still be ineffective if repository history, environment setup, reviewer availability, and architecture decisions are missing. Conversely, strong company-owned evidence may allow a different supplier or internal engineer to resume without a formal replacement program. Record the skills needed for each lane, supported technologies, expected overlap for handover, and which decisions require domain rather than framework knowledge. When a transition is planned, give the incoming engineer a fresh task instead of asking for a tour alone; questions raised while producing a small reviewable change expose gaps that presentations conceal. Close the transition only after open branches, issue ownership, alerts, scheduled jobs, package permissions, and vendor contacts have named successors. Keep the outgoing programmer's access until the agreed handoff evidence is captured, then remove it on schedule rather than leaving dormant accounts as an informal safety net.`,
],sources:[['NIST SP 800-34 Rev. 1','https://csrc.nist.gov/pubs/sp/800/34/r1/upd1/final'],['NIST SSDF','https://csrc.nist.gov/Projects/ssdf'],['CISA Secure by Design','https://www.cisa.gov/securebydesign'],['Google SRE On-Call','https://sre.google/sre-book/being-on-call/'],['Google SRE Managing Incidents','https://sre.google/sre-book/managing-incidents/']],related:['outsourced-programmer-knowledge-transfer-acceptance-test','outsourced-developer-production-incident-access-decision','software-development-handoff-reliability-research'],nextStep:{heading:'Test continuity before it is urgent',copy:'Choose one application, list owner-controlled systems, and schedule a clean-setup drill.',href:'/contact',label:'Plan the staffing handoff'}
};

export const october2ResearchBatch: ReadonlyArray<ResearchPost> = [paidTrial,access,review,flaky,continuity].map(post => ({...post,published:date}));
