import type { ResearchPost } from './fleet-content';
const published='2026-10-09';
type Study={slug:string;title:string;excerpt:string;topic:string;subject:string;measure:string;sources:readonly (readonly [string,string])[]};
const studies:readonly Study[]=[
 {slug:'outsourcedprogrammers-queue-wait-state-evidence-study',title:'Outsourced Software Development Queue Wait-State Evidence Study',excerpt:'A source-backed study for outsourced software development teams to whether waiting reasons explain queue age.',topic:'Change failure evidence',subject:'change failure evidence',measure:'release outcome, restoration action, affected service, discovery stage, and verified contributing control',sources:[['DORA research program','https://dora.dev/research/'],['Google SRE monitoring guidance','https://sre.google/sre-book/monitoring-distributed-systems/'],['NIST Secure Software Development Framework','https://csrc.nist.gov/Projects/ssdf'],['GitHub pull request reviews','https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'],['OpenTelemetry specification','https://opentelemetry.io/docs/specs/']]},
 {slug:'outsourcedprogrammers-reviewer-agreement-reliability-study',title:'Outsourced Software Development Reviewer Agreement Reliability Study',excerpt:'A source-backed study for outsourced software development teams to whether reviewers reproduce the same conclusion.',topic:'Review queue latency',subject:'code-review queue latency',measure:'ready timestamp, first accountable review, return reason, revision count, risk class, and reviewer ownership',sources:[['DORA research program','https://dora.dev/research/'],['Google Engineering Practices','https://google.github.io/eng-practices/review/'],['GitHub pull request reviews','https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'],['Google Technical Writing','https://developers.google.com/tech-writing'],['NIST Secure Software Development Framework','https://csrc.nist.gov/Projects/ssdf']]},
 {slug:'outsourcedprogrammers-minimum-access-effectiveness-study',title:'Outsourced Software Development Minimum Access Effectiveness Study',excerpt:'A source-backed study for outsourced software development teams to whether permissions are sufficient but bounded.',topic:'Test-data privacy',subject:'test-data privacy control',measure:'data class, approved purpose, transformation, access owner, retention limit, and verified disposal result',sources:[['NIST Privacy Framework','https://www.nist.gov/privacy-framework'],['NIST SP 800-53 Rev. 5','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'],['OWASP Test Data Management','https://cheatsheetseries.owasp.org/cheatsheets/Test_Data_Management_Cheat_Sheet.html'],['CISA Secure by Design','https://www.cisa.gov/securebydesign'],['NIST Secure Software Development Framework','https://csrc.nist.gov/Projects/ssdf']]},
 {slug:'outsourcedprogrammers-handoff-completeness-observation',title:'Outsourced Software Development Handoff Completeness Observation',excerpt:'A source-backed study for outsourced software development teams to whether a receiving team can continue without private clarification.',topic:'Dependency update lead time',subject:'dependency-update lead time',measure:'advisory or release date, inventory match, triage decision, compatibility evidence, approval, and deployed artifact',sources:[['OpenSSF Scorecard','https://scorecard.dev/'],['CISA Known Exploited Vulnerabilities','https://www.cisa.gov/known-exploited-vulnerabilities-catalog'],['NIST National Vulnerability Database','https://nvd.nist.gov/'],['SLSA specification','https://slsa.dev/spec/v1.0/'],['NIST Secure Software Development Framework','https://csrc.nist.gov/Projects/ssdf']]},
 {slug:'outsourcedprogrammers-control-change-traceability-research',title:'Outsourced Software Development Control Change Traceability Research',excerpt:'A source-backed study for outsourced software development teams to whether operating changes remain attributable and reversible.',topic:'Release recovery time',subject:'release recovery-time evidence',measure:'detection, decision, mitigation start, service restoration, verification, and unresolved data repair',sources:[['Google SRE incident response','https://sre.google/sre-book/managing-incidents/'],['DORA research program','https://dora.dev/research/'],['NIST incident handling guide','https://csrc.nist.gov/pubs/sp/800/61/r2/final'],['OpenTelemetry specification','https://opentelemetry.io/docs/specs/'],['NIST Secure Software Development Framework','https://csrc.nist.gov/Projects/ssdf']]},
];
const body=(s:Study)=>[
 `Research on ${s.subject} is useful only when the unit of observation is explicit. Identify one maintained repository, service, release path, and observation window. Record ${s.measure}. Those fields create an auditable sequence rather than a number detached from context. They also separate work performed by an outsourced programmer from approvals, queues, environment failures, and production actions controlled by the company.`,
 `The cited guidance favors traceable software practices, risk-based controls, and observable outcomes. It does not support keystrokes, online presence, or message volume as engineering-quality measures. A durable ticket, exact revision, named reviewer, test result, and release record provide stronger evidence. This study treats ${s.subject} as a delivery-system property, not an individual contributor score.`,
 `Define start and end events before collection. A queue does not begin because a draft exists, and recovery does not end because a command ran. Starting evidence must show required inputs and ownership; ending evidence must show the intended result was checked. Classify missing evidence separately instead of guessing timestamps. Precise definitions prevent incomplete handoffs from appearing fast.`,
 `Build the dataset from accountable systems: version control, review history, CI results, deployment events, incident timelines, inventories, or approved access logs. Use stable identifiers to join facts and retain only fields needed for the question. Do not copy secrets, customer content, private messages, or broad log archives. Document the extraction query and field dictionary.`,
 `Clean observations before calculating a rate or duration. Remove duplicates, automated test records outside the population, cancelled work, and events outside the window. Preserve exclusions with reason codes. Never silently discard long-running or failed cases; those tails may contain the weakness the study should expose. Report population and missing-data counts beside every summary.`,
 `Segment by work type, risk, service, and release mechanism. Documentation corrections, authentication changes, dependency emergencies, and database migrations have different shapes. Combining them into one average yields a number that is easy to quote and difficult to act on. Use medians and upper percentiles for skewed durations, and show distributions or counts.`,
 `Establish a negative control. Insert a synthetic incomplete handoff and confirm the classifier does not mark it ready, exercise a prohibited path and expect rejection, or compare an intentionally mismatched revision. A method that reports success for a known-bad control is not trustworthy enough for management or release decisions.`,
 `Interpret association carefully. A longer interval or higher failure share does not identify a cause. High-risk work may receive deeper review, improved detection may raise incident counts, and small samples swing after one event. Review representative cases, corroborate with technical evidence, and label hypotheses. Do not use correlation to rank individuals.`,
 `Make ownership visible. Outsourced programmers may prepare fixtures, queries, dashboards, and remediation proposals. Company owners retain access policy, security exceptions, customer communication, merge approval, production execution, and risk acceptance. When a delay waits on an internal decision, classify that ownership accurately.`,
 `Protect measurement from becoming a target. Rewarding only a shorter value may encourage premature ready states, artificial record splitting, skipped checks, or unreported failures. Pair speed with evidence completeness, risk, escaped defects, and recovery verification. Review samples and retain qualitative context. Dependable flow matters more than a cosmetically favorable dashboard.`,
 `A useful view shows population, definitions, revision, period, distribution, exceptions, and limitations. It links reproducible queries and sanitized examples. Alert thresholds need a responder and action. Detailed observations follow least privilege, while aggregated findings can support process review. Do not expose private performance or security data merely because a dashboard can display it.`,
 `Run the method for comparable periods before setting a target. Verify consistent event definitions and automation across tool changes. Compare manual samples with generated results. Version the query and field dictionary. Annotate process changes rather than pretending the series stayed comparable. A stable measurement system is itself part of the result.`,
 `Translate findings into bounded experiments: improve an intake template, add a missing fixture, reserve reviewer capacity, automate an inventory check, or rehearse rollback. Each experiment needs an owner, expected signal, time limit, and review date. Recalculate afterward and inspect whether safety, evidence quality, and flow improved together.`,
 `Local context limits generalization. Tool configuration, repository age, criticality, frequency, and sample size all matter. Authoritative sources provide principles, not a universal threshold for ${s.subject}. Document local definitions, legal and privacy obligations, supported systems, and approval boundaries before acting on the metric.`,
  `Research takeaway: measure ${s.subject} through reproducible system events, risk context, and named ownership. Preserve exact revisions and negative controls, publish limitations, and use results to improve briefs, fixtures, review capacity, and recovery. Keep employment assessment, security exceptions, customer decisions, and production authority with qualified company owners.`,
  `Validate the analysis with a second reviewer who can reproduce at least one included record and one excluded record from source systems. Resolve discrepancies in definitions rather than averaging conflicting interpretations. Store the reviewer, query revision, and validation date with the result. This check detects silent changes in workflow labels and integrations that can otherwise make a stable-looking trend incomparable across periods.`,
  `Apply retention and access controls to the research dataset itself. Detailed engineering and incident records may reveal vulnerabilities, personnel information, customer impact, or operational topology. Use named access, approved purpose, minimal fields, and an expiry date. Preserve aggregate findings and decision evidence where useful, then verify disposal of temporary extracts and locally downloaded working files.`,
  `Review the metric alongside a small sample of actual outcomes at a regular governance meeting. Owners should ask what decision the evidence supports, what alternative explanation remains, and whether the collection process creates harmful incentives. Pause or revise the measure if it encourages hidden work or weaker reporting. Evidence earns continued use by helping teams make safer decisions, not merely by being easy to calculate.`,
];
export const october9ResearchBatch:ReadonlyArray<ResearchPost>=studies.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,topic:s.topic,published,body:body(s),sources:s.sources,related:studies.filter(x=>x.slug!==s.slug).slice(0,3).map(x=>x.slug),hero:'/programmer-workbench.jpg'}));

// This October 9 control starts from one bounded observation, preserves missing evidence as missing, and keeps the consequential decision with the named accountable owner.
