import type { BlogDetail } from './data';

type Source = { name: string; url: string; note: string };
type Topic = {
  slug: string; title: string; excerpt: string; focus: string; system: string; serviceUrl: string; serviceLabel: string;
  scenario: string; baseline: string; boundary: string; evidence: string; diagnosis: string; correction: string; failure: string;
  fieldwork: string; tradeoff: string; deepDive: string; handoff: string; sources: readonly Source[];
};

const topics: readonly Topic[] = [
  {
    slug: 'outsource-nextjs-route-handler-cors-review',
    title: 'Review CORS behavior in a Next.js Route Handler before opening it to another origin',
    excerpt: 'Test preflight, credentials, allowed headers, caching, error responses, and origin matching with harmless clients.',
    focus: 'Route Handler cross-origin access', system: 'Next.js application', serviceUrl: '/services/nextjs-development', serviceLabel: 'Next.js development',
    scenario: 'A partner dashboard sends a credentialed request from its approved origin, while an attacker uses a lookalike subdomain and a CDN reuses a preflight response without the right origin variation.',
    baseline: 'Call the Route Handler from its same origin and from one explicitly approved synthetic origin. Record methods, request headers, credentials, response headers, cookies, status, and actual business effect.',
    boundary: 'Send simple and preflighted requests from approved, denied, null, mixed-case, lookalike, and port-varied origins; vary methods and headers; omit Origin; use credentials; trigger errors; and repeat through the configured cache.',
    evidence: 'source revision, route and method, exact Origin, requested method and headers, authentication context, preflight status, allow-origin and allow-credentials values, Vary, cache result, actual response, browser console result, and server-side effect',
    diagnosis: 'Separate browser permission from server authorization. CORS determines whether browser code may read a response; it does not authenticate the caller or stop non-browser clients from reaching the endpoint.',
    correction: 'Match normalized origins against an explicit allowlist, answer preflight consistently, limit methods and headers, vary cacheable responses by Origin where required, avoid wildcard credentials, and retain normal endpoint authentication and authorization.',
    failure: 'The dangerous result is an origin reflection rule that approves a lookalike or a cached allow response served to another origin. A browser error can also hide that the server already performed a state change.',
    fieldwork: 'Use two tiny browser pages hosted on distinct local origins plus direct HTTP fixtures. Capture both network traffic and JavaScript readability. Test the error path because middleware and exception responses often omit the headers applied on success, leaving approved clients unable to diagnose a real failure.',
    tradeoff: 'A broad pattern is convenient for preview deployments but expands trust as new subdomains appear. If dynamic previews require access, bind the rule to a controlled registry and lifecycle rather than accepting any suffix that resembles the company domain.',
    deepDive: 'Inspect where headers are produced. Next.js configuration, middleware, the Route Handler, a reverse proxy, and a CDN can each add or overwrite CORS values. Duplicate allow-origin headers are invalid even when each layer looks reasonable alone. Preflight caching deserves its own decision: a long max age reduces traffic but delays policy changes. Confirm that OPTIONS does not invoke the business operation, that denied origins receive no privileged data, and that cross-site cookie settings and anti-forgery protections match the credentialed workflow.',
    handoff: 'Provide the origin matrix, browser and direct-request fixtures, header transcripts for success and error paths, proxy and cache observations, credential behavior, actual side-effect checks, regression tests, approved-origin ownership, and the release owner’s policy decision.',
    sources: [{ name: 'Next.js CORS guide', url: 'https://nextjs.org/docs/app/api-reference/config/next-config-js/headers', note: 'Official response-header configuration reference.' }, { name: 'Fetch Standard CORS protocol', url: 'https://fetch.spec.whatwg.org/#http-cors-protocol', note: 'Primary browser protocol specification.' }],
  },
  {
    slug: 'outsource-react-external-store-subscription-test',
    title: 'Test a React external-store subscription before outsourcing a state bridge',
    excerpt: 'Exercise snapshots, subscription cleanup, server rendering, concurrent updates, and selector stability.',
    focus: 'external-store subscription correctness', system: 'React application', serviceUrl: '/services/react-application-development', serviceLabel: 'React application development',
    scenario: 'A component reads an external store during server rendering, the store changes before hydration, and a second mounted view subscribes while the first view is being removed.',
    baseline: 'Mount one component against a fixed store, record the snapshot identity and value, issue one update, verify one render, unmount, and confirm the listener count returns to its starting value.',
    boundary: 'Return cached and newly allocated snapshots, update during render and transition, mount two selectors, unsubscribe during notification, hydrate from an older server snapshot, change store instances, and exercise development Strict Mode.',
    evidence: 'React and component revisions, store instance, server and client snapshot values, snapshot identity, listener count, subscribe and cleanup times, update sequence, selector result, render count, hydration output, warning, and final DOM',
    diagnosis: 'Treat getSnapshot as a cached observation contract rather than an ordinary getter. A fresh object on every call can loop, while a mutable object with stable identity can hide real changes from React.',
    correction: 'Cache immutable snapshots, make subscribe return exact cleanup, provide a truthful server snapshot, keep store instance changes explicit, stabilize selectors where necessary, and move derived UI-only state back into React when no external store is needed.',
    failure: 'The defect may appear as missed updates, excessive renders, hydration replacement, or leaked listeners. A final screen that looks right once does not prove the subscription remains correct across mount cycles.',
    fieldwork: 'Instrument the store with listener and snapshot counters without changing notification order. Run production-like hydration as well as development checks. Force an update between server output and client hydration, then state whether the product expects identical data, a frozen bootstrap snapshot, or an intentional client correction.',
    tradeoff: 'A generic bridge can connect many stores, but abstraction can obscure each store’s mutation and caching guarantees. Keep the adapter small until the team can state how snapshots become immutable and when server data expires.',
    deepDive: 'Test selectors that return objects and arrays, because equivalent content with new identity can defeat memoization. If the store is browser-only, decide what the server renders instead of reading globals conditionally during render. Subscription callbacks should only signal that a snapshot may have changed; they should not smuggle values from a stale closure. Also check error recovery: if getSnapshot throws while a store is temporarily unavailable, the nearest boundary and retry path should be deliberate, and cleanup must still occur when React abandons a render.',
    handoff: 'Attach the minimal instrumented store, snapshot and listener timeline, hydration fixture, Strict Mode comparison, selector cases, render counts, cleanup proof, unsupported store behaviors, regression tests, and the React owner’s decision about server snapshots.',
    sources: [{ name: 'React useSyncExternalStore', url: 'https://react.dev/reference/react/useSyncExternalStore', note: 'Official external-store contract and troubleshooting.' }, { name: 'React StrictMode', url: 'https://react.dev/reference/react/StrictMode', note: 'Official development checks and effect behavior.' }],
  },
  {
    slug: 'outsource-nodejs-job-idempotency-retry-review',
    title: 'Review Node.js job idempotency before outsourcing retry handling',
    excerpt: 'Prove what happens after timeouts, worker exits, duplicate delivery, and partial side effects.',
    focus: 'background-job idempotency', system: 'Node.js worker and queue', serviceUrl: '/services/nodejs-api-development', serviceLabel: 'Node.js API development',
    scenario: 'A worker charges a sandbox order, exits before acknowledging the message, and receives the same job again after another worker has already sent its notification.',
    baseline: 'Run one synthetic job to completion and map every durable state change, external call, queue transition, log identifier, and acknowledgement in chronological order.',
    boundary: 'Exit before and after each side effect, time out an external call with an unknown outcome, deliver duplicates concurrently, retry after process restart, and move an exhausted job to its terminal queue.',
    evidence: 'code revision, job and business keys, attempt, lease owner, queue timestamps, state transition, external request key, external result, acknowledgement, retry delay, terminal reason, and reconciliation result',
    diagnosis: 'Distinguish message delivery from business completion. At-least-once delivery means the same work may arrive again, while a timeout means the caller may not know whether an external effect happened.',
    correction: 'Choose a stable business idempotency key, persist guarded state transitions, pass supported keys to external providers, make notifications replay-safe, and provide reconciliation for ambiguous outcomes.',
    failure: 'Catching an exception and retrying is not a complete design. The harmful outcome is a duplicate irreversible effect or a job marked failed even though part of the business operation succeeded.',
    fieldwork: 'Use a sandbox and inject a stop at every boundary. Read the durable store after restart rather than trusting in-memory counters. A parallel duplicate case is essential because sequential replay can hide an unsafe check-then-write race.',
    tradeoff: 'Exactly-once language often hides operational compromises. Retaining idempotency records has storage and privacy costs, while short retention can reopen an old duplicate. The business owner must choose a truthful replay window.',
    deepDive: 'Study the transaction boundary around the durable receipt. If the queue acknowledgement and business database cannot share a transaction, the design needs a recoverable intermediate state. An outbox, inbox, or reconciliation scan may be appropriate, but each has an owner and latency. Verify retry classification too: malformed input should not consume capacity forever, while a temporary dependency outage should retain enough context for recovery. Backoff and jitter protect the dependency, yet they must not extend beyond the business deadline without a visible terminal state. Measure queue age separately from the duration of the current attempt.',
    handoff: 'Include the side-effect map, failure-injection table, queue settings, idempotency schema, concurrent traces, provider behavior, ambiguous-outcome procedure, dead-letter ownership, retention decision, and commands for a bounded replay.',
    sources: [{ name: 'BullMQ retrying jobs', url: 'https://docs.bullmq.io/guide/retrying-failing-jobs', note: 'Official retry behavior for a common Node.js queue.' }, { name: 'AWS Builders Library idempotent APIs', url: 'https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/', note: 'Primary engineering guidance on safe retries.' }],
  },
  {
    slug: 'outsource-wordpress-rest-api-permission-callback-review',
    title: 'Review WordPress REST API permission callbacks before exposing a custom endpoint',
    excerpt: 'Test capability, object ownership, nonce assumptions, malformed input, and information leakage.',
    focus: 'custom REST endpoint authorization', system: 'WordPress plugin', serviceUrl: '/services/wordpress-engineering', serviceLabel: 'WordPress engineering',
    scenario: 'A logged-in contributor sends a valid request to an endpoint intended for editors and substitutes the identifier of a private post owned by another user.',
    baseline: 'List anonymous, subscriber, contributor, editor, and administrator expectations for each method and object state before invoking the endpoint.',
    boundary: 'Call each method anonymously and with every role, vary object ownership and publication state, omit or replay browser nonces, send malformed identifiers, and request objects that do not exist.',
    evidence: 'WordPress and plugin revision, route, method, identity, role, capability checks, object state, nonce context, normalized parameters, response code and shape, database effect, and log result',
    diagnosis: 'A nonce demonstrates request context but is not a substitute for capability and object-level authorization. A broad role check can also miss restrictions tied to a particular post.',
    correction: 'Register an explicit permission callback, use current capability mapping for the target object, sanitize and validate arguments, return consistent errors, and minimize data exposed before authorization.',
    failure: 'The endpoint may appear protected in the block editor while remaining callable outside that interface. Leaking whether a private object exists is itself an observable authorization defect.',
    fieldwork: 'Create disposable users and posts in staging. Exercise requests through the normal client and a direct HTTP fixture. Compare response bodies as well as status codes so unauthorized callers cannot infer titles, authors, or internal identifiers.',
    tradeoff: 'Custom capabilities can express the product boundary more accurately, but they add lifecycle and migration work. Prefer existing mapped capabilities where they are truthful; do not collapse policy into administrator-only access merely to simplify testing.',
    deepDive: 'Trace parameter handling before and after the permission callback. WordPress can validate and sanitize registered arguments, but the callback still needs a reliable target identifier to make an object-level decision. Confirm that a malformed identifier cannot fall back to a global operation. Then compare collection and single-object routes: permission to list a filtered collection does not automatically grant permission to read every item through a direct route. Preserve compatibility deliberately if existing clients depend on an error code or response shape, and document any contract change. Check application passwords and cookie-authenticated requests as distinct authentication contexts with the same authorization expectations.',
    handoff: 'Provide the route inventory, role-and-object matrix, direct request fixtures, permission callback diff, sanitization rules, response comparisons, tests, compatibility notes, and the WordPress owner who approves the public contract.',
    sources: [{ name: 'WordPress REST routes and endpoints', url: 'https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/', note: 'Official endpoint and permission callback guidance.' }, { name: 'WordPress roles and capabilities', url: 'https://wordpress.org/documentation/article/roles-and-capabilities/', note: 'Official capability reference.' }],
  },
  {
    slug: 'outsource-shopify-theme-cart-state-test',
    title: 'Test Shopify theme cart state across sections, tabs, and failed requests',
    excerpt: 'Reconcile cart drawers, page carts, discounts, inventory responses, and accessibility with a development store.',
    focus: 'storefront cart-state consistency', system: 'Shopify theme', serviceUrl: '/services/shopify-development', serviceLabel: 'Shopify development',
    scenario: 'A shopper changes quantity in a cart drawer while another tab removes the line and the server rejects the first tab because available inventory changed.',
    baseline: 'Add two variants in a development store and record line keys, quantities, totals, discounts, cart sections, focus, and announcements after one ordinary update.',
    boundary: 'Update from drawer and page, use two tabs, trigger inventory and network failures, apply a discount, remove the final line, press controls rapidly, use keyboard only, and reload after a rejected change.',
    evidence: 'theme revision, development-store fixture, cart token hash, line key, user intent, request and section parameters, server cart response, rendered regions, totals, discount, focus, announcement, and recovery action',
    diagnosis: 'Treat the server cart response as authoritative and identify every rendered copy of cart state. Updating only the initiating component leaves stale count badges, totals, or checkout controls elsewhere.',
    correction: 'Serialize or identify conflicting intents, render all requested sections from the accepted response, restore usable controls after failure, preserve focus deliberately, and explain inventory corrections without inventing success.',
    failure: 'A drawer that looks correct can coexist with a stale page total or checkout link. The consequential defect is a shopper acting on contradictory price, quantity, or availability information.',
    fieldwork: 'Use product variants with controlled inventory and reversible discounts. Capture the response payload and each affected section after every transition. The empty-cart and last-item cases deserve separate evidence because markup often changes shape.',
    tradeoff: 'Disabling all cart controls prevents some races but can make the storefront feel broken and does not address a second tab. Decide which actions may proceed concurrently and how the interface explains a server correction.',
    deepDive: 'Inspect line identity rather than assuming a product variant uniquely identifies a cart row. Selling plans, properties, and personalization can create distinct lines for the same variant. A repair keyed only by variant can update or remove the wrong row. Test whether server-rendered sections contain executable scripts or event bindings that the replacement path must restore. Finally, make totals and currency formatting part of the oracle: the theme should render the values returned for the current cart, not recalculate money from stale DOM text or floating-point arithmetic.',
    handoff: 'Attach the cart-state diagram, variant fixtures, multi-tab sequence, failed-response recordings, section list, keyboard observations, supported theme and browser versions, regression cases, and merchant decisions about discount and inventory messages.',
    sources: [{ name: 'Shopify Ajax API cart reference', url: 'https://shopify.dev/docs/api/ajax/reference/cart', note: 'Official cart request and response contract.' }, { name: 'Shopify bundled section rendering', url: 'https://shopify.dev/docs/api/ajax/section-rendering', note: 'Official multi-section rendering guidance.' }],
  },
  {
    slug: 'outsource-playwright-auth-state-isolation-audit',
    title: 'Audit Playwright authentication state before sharing it across tests',
    excerpt: 'Detect account collisions, stale storage, parallel-worker leakage, and unsafe committed credentials.',
    focus: 'browser-test authentication isolation', system: 'Playwright test suite', serviceUrl: '/services/qa-automation', serviceLabel: 'QA automation',
    scenario: 'Two parallel workers reuse one stored session, one test changes the account role, and a later test passes only because it inherited cookies and local storage from that changed identity.',
    baseline: 'Run the target flow from a clean browser context with one disposable account and inventory the cookies, origins, storage, permissions, and server-side account state it creates.',
    boundary: 'Run in parallel, revoke the session, change the role, expire credentials, reuse state on another base URL, fail setup midway, start a clean project, and inspect repository and artifact output for secrets.',
    evidence: 'suite revision, project and worker, account label, state-file digest and location, origin, cookie metadata, setup time, role, revocation time, test start, isolation choice, result, trace, and cleanup status',
    diagnosis: 'Separate immutable login setup from mutable account data. Storage-state reuse saves time only when tests cannot change the identity or shared server records in ways that affect one another.',
    correction: 'Create worker-scoped accounts where mutation is possible, generate state in a controlled setup, exclude it from version control, refresh on expiry, keep environment origins separate, and destroy disposable identities after the run.',
    failure: 'The suite can report green while testing the wrong role or relying on order. A committed state file may also contain live session material even when its filename looks harmless.',
    fieldwork: 'Hash rather than print secret-bearing state during the audit. Deliberately make one worker revoke or demote its account and confirm other workers retain their expected state. Review traces and uploaded artifacts for accidental cookie capture.',
    tradeoff: 'Logging in through the UI for every test maximizes independence but can waste time and overload identity controls. Reuse is reasonable when its ownership and invalidation rules are explicit and measured.',
    deepDive: 'Review project dependencies as well as files. A setup project may refresh state once while several browser projects consume it with different locale, device, or base URL settings. Confirm the stored origin and cookie scope are valid for each consumer and that one project cannot silently authenticate against an unintended environment. When tests use API login, cover the browser transition that establishes anti-forgery or device state separately. Speed improvements are only real if retries and false positives do not shift review time downstream.',
    handoff: 'Include the account ownership map, state-generation code, parallel collision experiment, expiry behavior, ignore rules, artifact redaction check, run-time comparison, cleanup evidence, and the identity owner who approves test-account scope.',
    sources: [{ name: 'Playwright authentication guide', url: 'https://playwright.dev/docs/auth', note: 'Official storage-state and account-isolation guidance.' }, { name: 'Playwright parallelism', url: 'https://playwright.dev/docs/test-parallel', note: 'Official worker behavior reference.' }],
  },
  {
    slug: 'outsource-docker-container-signal-shutdown-test',
    title: 'Test container signal handling before outsourcing a shutdown fix',
    excerpt: 'Trace PID 1, stop signals, readiness, open requests, workers, and forced termination.',
    focus: 'container shutdown behavior', system: 'Dockerized service', serviceUrl: '/services/devops-engineering', serviceLabel: 'DevOps engineering',
    scenario: 'The platform asks a container to stop while it is serving a long request and processing a background job, but the application is hidden behind a shell process that does not forward the signal.',
    baseline: 'Start one container locally, identify PID 1 and its children, send one normal request, and record readiness, logs, open connections, and exit status during an ordinary stop.',
    boundary: 'Stop during startup, idle time, a slow request, a job, and a dependency failure; vary the grace period, send the configured stop signal, exceed the deadline, and restart immediately.',
    evidence: 'image digest, command and entrypoint, PID tree, signal and time, readiness transition, request and job identifiers, connection state, cleanup events, deadline, forced signal, exit code, and restart result',
    diagnosis: 'Trace the signal from runtime to the actual application process. Exec-form commands, wrapper behavior, framework hooks, and orchestrator deadlines determine whether cleanup code ever runs.',
    correction: 'Make the application reachable by the stop signal, fail readiness before draining, stop accepting new work, bound request and job completion, close owned resources once, and exit before the platform deadline.',
    failure: 'A zero exit code from a quiet container does not prove graceful shutdown. Real harm appears as truncated responses, duplicate jobs, abandoned leases, or a replacement instance competing with the old one.',
    fieldwork: 'Use labelled synthetic requests and jobs, then correlate client observations with process and resource events. Repeat forced termination as a negative control; the system still needs retry or recovery behavior when graceful cleanup cannot finish.',
    tradeoff: 'A longer grace period protects some work but delays rollouts and failure recovery. The service owner must decide which operations can finish, which can resume elsewhere, and which clients should receive an early retryable response.',
    deepDive: 'Distinguish liveness from readiness during the drain. Killing the process because readiness became false defeats graceful shutdown, while leaving readiness true invites new traffic. Document how the actual platform interprets both probes. Check child processes and subprocess groups as well: the main server may exit cleanly while a worker continues holding a port or lease. If an init process is added, verify its reaping and forwarding behavior rather than assuming the package name solves the lifecycle automatically.',
    handoff: 'Provide the image and runtime configuration, PID evidence, signal timeline, drain behavior, forced-stop comparison, client results, job recovery, chosen grace budget, regression command, and platform owner approval for production settings.',
    sources: [{ name: 'Dockerfile ENTRYPOINT', url: 'https://docs.docker.com/reference/dockerfile/#entrypoint', note: 'Official signal and exec-form behavior.' }, { name: 'Docker container stop', url: 'https://docs.docker.com/reference/cli/docker/container/stop/', note: 'Official stop signal and timeout behavior.' }],
  },
  {
    slug: 'outsource-postgresql-row-level-security-test',
    title: 'Test PostgreSQL row-level security before delegating a tenant-data change',
    excerpt: 'Exercise policies, roles, pooled connections, background work, new rows, and administrative bypass.',
    focus: 'tenant isolation with row-level security', system: 'PostgreSQL application database', serviceUrl: '/services/database-engineering', serviceLabel: 'Database engineering',
    scenario: 'A pooled connection retains the previous tenant setting and a background worker runs under a table-owning role that bypasses policies while updating shared records.',
    baseline: 'Create two synthetic tenants with clearly different rows. Record database roles, table owner, active policies, application session settings, and expected reads and writes for each operation.',
    boundary: 'Select, insert, update, delete, upsert, join, use prepared statements, reuse pooled connections, omit tenant context, run background work, change roles, and exercise table-owner or bypass privileges.',
    evidence: 'schema and policy revision, database role, session and transaction identifiers, tenant context, query shape, parameters, affected row identifiers, policy path, result count, error, pool checkout and reset, and audit record',
    diagnosis: 'Evaluate policy behavior under the exact role and connection lifecycle used by the application. A policy that works in an interactive client may be bypassed by ownership or contaminated session state.',
    correction: 'Use a non-owning application role, set tenant context transactionally, reset pooled state, write explicit USING and WITH CHECK rules, test every command, and reserve bypass privileges for separately controlled administration.',
    failure: 'Returning no rows for one SELECT is weak proof. Cross-tenant insertion, an UPDATE that silently targets another tenant, or a background process with broader rights can violate isolation through different paths.',
    fieldwork: 'Log harmless row identifiers and tenant labels in a disposable schema. Intentionally poison a pooled connection, return it, and borrow it as another tenant. Compare ordinary application, migration, and worker roles rather than assuming one test identity represents them all.',
    tradeoff: 'Database enforcement adds defense in depth but cannot repair ambiguous tenancy rules. Complex policies can also surprise maintenance tools and migrations, so ownership and privileged operating paths must be documented.',
    deepDive: 'Check policy composition when more than one policy applies. Permissive and restrictive policies combine differently, and a new migration can broaden access without editing an existing rule. Test foreign keys and functions invoked by a query under their real security context. Security-definer functions deserve explicit review because they can cross the boundary intentionally or accidentally. Monitoring should record denied or anomalous access without copying protected row contents into logs, and emergency administration should use a separately audited path rather than the ordinary application pool.',
    handoff: 'Attach the role graph, policy definitions, command matrix, pooled-connection experiment, worker results, explain plans where relevant, migration compatibility, monitoring proposal, rollback steps, and database owner approval.',
    sources: [{ name: 'PostgreSQL row security policies', url: 'https://www.postgresql.org/docs/current/ddl-rowsecurity.html', note: 'Official RLS semantics and bypass rules.' }, { name: 'PostgreSQL SET LOCAL', url: 'https://www.postgresql.org/docs/current/sql-set.html', note: 'Official transaction-local setting behavior.' }],
  },
  {
    slug: 'outsource-mobile-offline-sync-conflict-test',
    title: 'Test mobile offline sync conflicts before outsourcing a data repair',
    excerpt: 'Reconcile edits, deletes, clock differences, retries, attachments, and user-visible recovery.',
    focus: 'offline synchronization conflict handling', system: 'mobile application and sync API', serviceUrl: '/services/mobile-app-development', serviceLabel: 'Mobile app development',
    scenario: 'A phone edits a record offline, a tablet deletes it online, and the phone reconnects with an attachment after its local clock has moved backwards.',
    baseline: 'Create one synthetic record on two devices, synchronize both, and record server version, local identifiers, tombstone behavior, queued operations, attachment state, and displayed timestamps.',
    boundary: 'Edit the same and different fields, delete on either side, reconnect in both orders, skew device clocks, retry a timed-out upload, reinstall, use two accounts, and interrupt synchronization after metadata but before an attachment.',
    evidence: 'app and API revisions, account and device labels, local and server IDs, base version, operation identifier, field changes, tombstone, client clock, server time, upload digest, retry, merge decision, final records, and displayed explanation',
    diagnosis: 'Define conflicts in product terms rather than relying on last-write-wins by device time. Field independence, deletion authority, attachment ownership, and version ancestry determine whether changes can merge safely.',
    correction: 'Use server-assigned versions or causal tokens, give operations stable identifiers, retain bounded tombstones, make uploads resumable and deduplicated, and ask the user when intent cannot be inferred safely.',
    failure: 'The worst outcome may be silent resurrection: a deleted sensitive record returns because an old offline client looked newer. Duplicate attachments and edits applied to the wrong account are equally important boundaries.',
    fieldwork: 'Use devices or emulators with controlled connectivity and clocks. Preserve local database snapshots and server records at each transition. A screen recording helps explain user experience, but hashes and version histories prove what data survived.',
    tradeoff: 'Automatic merging reduces prompts but can invent a result no user chose. Keeping tombstones and operation histories improves safety while increasing retention. Product and privacy owners should approve those windows.',
    deepDive: 'Define what happens when the local queue contains operations against a record whose schema changed while the device was offline. A client may need to migrate its queued representation before upload or stop with a visible recovery path. Test pagination and partial sync too: receiving page two before a delayed page one must not make an older snapshot authoritative. When attachments are encrypted or compressed, the digest and resume protocol should refer to a clearly defined representation so deduplication cannot join different user files accidentally.',
    handoff: 'Include the conflict taxonomy, two-device scripts, local and server state captures, clock-skew cases, deletion and attachment results, recovery copy, telemetry boundaries, retention decisions, regression tests, and sync-owner approval.',
    sources: [{ name: 'Android offline-first guidance', url: 'https://developer.android.com/topic/architecture/data-layer/offline-first', note: 'Official mobile data-layer guidance.' }, { name: 'Apple synchronizing model data', url: 'https://developer.apple.com/documentation/coredata/synchronizing-a-local-store-to-the-cloud', note: 'Official synchronization context.' }],
  },
  {
    slug: 'outsource-legacy-api-character-encoding-review',
    title: 'Review character encoding at a legacy API boundary before rewriting it',
    excerpt: 'Trace bytes, declared charsets, normalization, storage, logs, signatures, and round trips.',
    focus: 'legacy text-encoding compatibility', system: 'legacy integration', serviceUrl: '/services/legacy-application-maintenance', serviceLabel: 'Legacy application maintenance',
    scenario: 'A partner sends a customer name in Windows-1252 while declaring no charset, an intermediary assumes UTF-8, and the repaired value later fails a byte-level signature comparison.',
    baseline: 'Capture a permitted raw request fixture and map bytes through transport decoding, parser, application strings, database columns, export, logs, and the return response without using real customer data.',
    boundary: 'Use accented Latin text, smart punctuation, combining characters, emoji, replacement bytes, a mismatched declaration, decomposed and composed forms, truncation near field limits, and a signed payload.',
    evidence: 'integration and fixture revisions, raw-body digest, content type and charset, byte excerpt in safe notation, decoder, normalization decision, code points, database encoding and column, stored length, exported bytes, signature result, and round-trip comparison',
    diagnosis: 'Find the first irreversible conversion. Mojibake shown late in the pipeline is often created earlier, and re-encoding already-corrupted text can make recovery less reliable.',
    correction: 'Honor a documented partner contract, preserve raw bytes where verification requires them, decode once at a named boundary, validate failures explicitly, normalize only for approved comparisons, and keep display repair separate from stored evidence.',
    failure: 'A browser screenshot showing a readable name does not prove fidelity. Searching, deduplication, signatures, exports, and downstream billing files may still operate on different byte sequences.',
    fieldwork: 'Build a synthetic corpus with expected bytes and Unicode code points. Compare every hop and retain hashes rather than copying sensitive payloads. Include a fixture that must be rejected so the patch does not silently replace unknown input.',
    tradeoff: 'Permissive fallback decoding can preserve business continuity but makes interpretation ambiguous. Strict rejection is safer for integrity yet may interrupt an old partner. The integration owner must choose and monitor a bounded compatibility policy.',
    deepDive: 'Measure lengths in the unit each boundary actually enforces. Bytes, Unicode code points, and user-perceived characters differ, so a field that fits in one layer can be truncated in another. Test the truncation behavior before normalization because composition can change length. Logs and CSV exports need separate checks: terminals, spreadsheet software, and log shippers may guess encodings independently. If historical corruption is repaired, retain a reversible mapping and confidence level rather than overwriting the only evidence of the original bytes.',
    handoff: 'Provide the byte-flow diagram, synthetic corpus, declared and observed encodings, first-loss location, round-trip results, signature case, database and export constraints, partner questions, compatibility window, tests, and rollback plan.',
    sources: [{ name: 'WHATWG Encoding Standard', url: 'https://encoding.spec.whatwg.org/', note: 'Living standard for web-compatible encodings.' }, { name: 'Unicode normalization report', url: 'https://unicode.org/reports/tr15/', note: 'Authoritative normalization forms and constraints.' }],
  },
  {
    slug: 'outsource-graphql-field-authorization-audit',
    title: 'Audit GraphQL field authorization before adding a delegated resolver',
    excerpt: 'Check nested fields, aliases, batching, errors, introspection, and object ownership with synthetic identities.',
    focus: 'field-level GraphQL authorization', system: 'GraphQL API', serviceUrl: '/services/api-development', serviceLabel: 'API development',
    scenario: 'A support user may see an account summary but requests a nested billing field through an alias and a batched loader returns data cached for a previous administrator.',
    baseline: 'List permitted fields for an anonymous user, customer, support user, account administrator, and internal worker across two synthetic accounts.',
    boundary: 'Query protected fields directly and through fragments, aliases and nested connections; batch two identities, reuse loader caches, request missing objects, inspect errors, and compare introspection in supported environments.',
    evidence: 'schema and resolver revisions, operation digest, identity and account, requested field path, variables, policy decision, loader key, cache scope, data-source query, returned shape, null and error behavior, and audit event',
    diagnosis: 'Authorization must follow the data field, not merely the top-level operation. Resolver composition and request-scoped loaders can accidentally trust a parent object or cache result without identity context.',
    correction: 'Centralize policy decisions with object context, scope loaders to a request and truthful key, minimize fetched columns, return deliberate errors or nulls consistently, test fragments and aliases, and audit sensitive access without logging values.',
    failure: 'Blocking the obvious query while leaking the same value through a nested relation is still a breach. Different error shapes can also reveal that an unauthorized object exists.',
    fieldwork: 'Generate a query corpus from the schema and hand-write abuse cases for sensitive relationships. Compare response JSON and backing data-source calls. Run two identities in one process to expose caches that outlive a request.',
    tradeoff: 'Schema directives can make policy visible but may oversimplify decisions that depend on object state. Resolver-local checks are flexible but easy to omit. Choose one enforced composition pattern and make exceptions reviewable.',
    deepDive: 'Include mutations and subscriptions in the authorization map, not only queries. A mutation may correctly reject its main object while accepting nested input that references another account. Subscription authorization must remain true after connection establishment if membership changes. Cost controls also interact with policy: an unauthorized query should not trigger expensive downstream work before denial. Capture whether data loaders fetch a broad row and then discard fields, because minimizing the response is not the same as minimizing privileged data access. Repeat the audit after schema stitching or federation changes the resolver path.',
    handoff: 'Attach the role-field matrix, query corpus, fragment and alias results, loader lifetime evidence, backing query observations, error policy, introspection decision, audit-log sample, regression tests, and API owner sign-off.',
    sources: [{ name: 'GraphQL security guidance', url: 'https://graphql.org/learn/security/', note: 'Official GraphQL security considerations.' }, { name: 'OWASP GraphQL cheat sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html', note: 'Authoritative defensive guidance.' }],
  },
  {
    slug: 'outsource-ci-artifact-provenance-handoff',
    title: 'Verify CI artifact provenance before outsourcing a release pipeline change',
    excerpt: 'Connect source revision, workflow identity, dependencies, build output, attestations, and deployment input.',
    focus: 'build-artifact provenance', system: 'CI and release pipeline', serviceUrl: '/services/devops-engineering', serviceLabel: 'DevOps engineering',
    scenario: 'A rerun builds from the expected commit but downloads a mutable dependency and publishes an artifact under the same friendly name as an earlier workflow attempt.',
    baseline: 'Choose one non-production artifact and trace its source commit, workflow file, runner image, dependency resolution, build command, digest, storage location, retention, and downstream consumer.',
    boundary: 'Rerun the same commit, change a lockfile, rebuild on another runner, attempt an untrusted pull request, expire and restore caches, download by name and digest, verify an attestation, and select the artifact for a staging release.',
    evidence: 'repository and full commit, workflow revision, event and actor, run and attempt IDs, runner identity, permissions, dependency lock digest, cache result, build command, artifact name and digest, attestation subject, storage, and deployment-selected digest',
    diagnosis: 'Source provenance is a chain, not a commit label. Mutable inputs, excessive workflow permissions, ambiguous artifact names, or a deployment that resolves latest can break the link after a correct build.',
    correction: 'Pin reviewable inputs, restrict job permissions, isolate untrusted events, identify outputs by cryptographic digest, generate supported attestations, verify before promotion, and make deployment consume the recorded immutable artifact.',
    failure: 'A successful workflow badge proves that commands exited cleanly. It does not prove which bytes were deployed or whether another run replaced an artifact with the same name.',
    fieldwork: 'Rebuild a harmless fixture twice and compare digests, then explain any nondeterminism. Follow the exact download and promotion path rather than stopping at upload. Do not expose tokens while recording workflow permissions.',
    tradeoff: 'Perfect reproducibility may require toolchain changes beyond a bounded ticket. Start by making inputs and outputs identifiable, then document remaining nondeterminism and who accepts it before expanding scope.',
    deepDive: 'Inspect the boundary between a reusable workflow and its caller. Pinning a public action by commit is useful only if nested actions and downloaded tools are also reviewable. Record the identity that signs or attests and how verification trusts that identity. A valid attestation for the wrong repository, workflow, or event must fail policy. For container images, connect the manifest digest used by deployment to the attested subject; a mutable tag can remain a convenience label, but it cannot be the sole release identifier.',
    handoff: 'Provide the provenance chain, workflow permission diff, pinned inputs, run and attempt evidence, artifact and attestation digests, verification command, staging selection proof, nondeterminism notes, rollback path, and release-owner approval.',
    sources: [{ name: 'GitHub artifact attestations', url: 'https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations', note: 'Official attestation workflow guidance.' }, { name: 'SLSA provenance', url: 'https://slsa.dev/spec/v1.1/provenance', note: 'Primary provenance specification.' }],
  },
];

const sharedSource: Source = { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/Projects/ssdf', note: 'Primary framework for reviewable software practices.' };

function makeDetail(topic: Topic, index: number): BlogDetail {
  return {
    strictNoPricing: true,
    heroImage: index % 2 ? '/illustrations/getillustrations/inkdex-saas/code-control.webp' : '/programmer-workbench.jpg',
    takeaways: [
      `Write the expected ${topic.focus} decision before assigning code.`,
      `Reproduce the boundary with synthetic data in the ${topic.system}.`,
      `Retain ${topic.evidence}.`,
      'Keep policy, merge, credentials, and release approval with the company owner.',
    ],
    readinessRows: [
      { area: 'Scope', ready: `One bounded ${topic.focus} decision`, notReady: 'A request to improve the whole system' },
      { area: 'Fixture', ready: topic.baseline, notReady: 'Production customer data or shared credentials' },
      { area: 'Evidence', ready: topic.evidence, notReady: 'A pass label without observed values' },
      { area: 'Approval', ready: 'A named company owner reviews policy and release', notReady: 'The contractor changes production alone' },
    ],
    sections: [
      { id: 'decision-first', title: `Define the ${topic.focus} decision before assigning work`, paragraphs: [
        `An outsourced programmer can investigate ${topic.focus} well when the ticket names the decision a reviewer must make. The system in scope is the ${topic.system}. The concrete case is this: ${topic.scenario} This gives the work a user, state transition, and observable result instead of an open request to “check” the implementation.`,
        `${topic.failure} Write the allowed outcome, forbidden outcome, stop condition, and reviewer in plain language. Keep architecture, access policy, and production approval with the company. The contractor’s useful contribution is a repeatable fixture, an explained observation, a bounded patch, and evidence another person can challenge.`,
      ] },
      { id: 'baseline', title: 'Build a clean baseline before chasing the edge case', paragraphs: [
        `${topic.baseline} Run the simple path first and keep the output. A baseline proves the fixture can succeed, reveals hidden defaults, and gives the reviewer something concrete to compare with the failure. Without it, a broken test environment may be mistaken for a product defect.`,
        `Record ${topic.evidence}. Use synthetic identities, inert payloads, reversible records, and a named source revision. Mask secrets rather than copying them into screenshots or tickets. Note the versions and configuration that influence the result, and say which production conditions the fixture does not reproduce.`,
      ] },
      { id: 'boundary-matrix', title: 'Exercise the boundaries that change the decision', paragraphs: [
        `${topic.boundary} Change one important condition at a time before combining cases. Label each run with its intent and expected state. Include at least one negative control that must be rejected and one positive control that must succeed, otherwise a universally failing guard can look secure.`,
        `${topic.fieldwork} Keep timing and ordering where they matter. A final screenshot is rarely sufficient for concurrency, authorization, caching, or retry behavior. Preserve the sequence of requests and durable state so the reviewer can identify the first divergence rather than infer it from the last screen.`,
      ] },
      { id: 'diagnose', title: 'Diagnose ownership and state before proposing a patch', paragraphs: [
        `${topic.diagnosis} Draw the smallest state model that explains the evidence: who owns the decision, which data is authoritative, when it may become stale, and which component can create an irreversible effect. This prevents a local patch from hiding a wider contract mismatch.`,
        `${topic.tradeoff} Put that tradeoff in the handoff instead of quietly choosing on the company’s behalf. If evidence reveals an architecture or policy decision outside the ticket, stop at a diagnostic checkpoint with options, risks, and the smallest next experiment.`,
      ] },
      { id: 'correct', title: 'Make the smallest correction that preserves the contract', paragraphs: [
        `${topic.correction} Add regression coverage around the observed boundary, not only the helper changed by the patch. Rerun the baseline and negative controls, review logs for sensitive values, and confirm the fix did not broaden permissions or hide a failure the user still needs to understand.`,
        `Prefer an explicit error and recoverable workflow to silent coercion. Keep unrelated refactors outside the patch so reviewers can connect evidence to code. If a dependency, data migration, privileged configuration, or production-only experiment is required, name it as separate owner-approved work rather than smuggling it into the estimate.`,
      ] },
      { id: 'deeper-review', title: `Review the ${topic.focus} details that generic checklists miss`, paragraphs: [
        topic.deepDive,
      ] },
      { id: 'handoff', title: 'Leave a handoff that a technical owner can verify', paragraphs: [
        `${topic.handoff} Link the ticket, branch, commands, fixtures, and exact source revision. Separate observed facts from assumptions and state every untested condition. The reviewer should be able to reproduce the main result without reconstructing the contractor’s environment from chat history.`,
        `Estimate discovery, fixture creation, correction, regression work, and documentation separately. Name who removes test accounts and artifacts. End with a merge recommendation and a release checklist, but leave both decisions with the company’s technical owner. That boundary turns outsourced programming into reviewable capacity rather than transferred accountability.`,
      ] },
    ],
    roleBrief: [
      { label: 'Assignment', text: `Investigate one bounded ${topic.focus} decision in the ${topic.system}.` },
      { label: 'Baseline', text: topic.baseline },
      { label: 'Evidence', text: `Retain ${topic.evidence}.` },
      { label: 'Owner decision', text: 'The company technical owner approves policy, merge, and release.' },
    ],
    faqs: [
      { question: 'What should the first run prove?', answer: topic.baseline },
      { question: 'What should the programmer change?', answer: topic.correction },
      { question: 'What belongs in the handoff?', answer: topic.handoff },
    ],
    sources: [...topic.sources, sharedSource],
    internalLinks: [
      { label: topic.serviceLabel, url: topic.serviceUrl, note: `Plan scoped ${topic.focus} support.` },
      { label: 'Build a technical handoff', url: '/blog/outsourced-programmer-technical-handoff', note: 'Give the reviewer reproducible evidence.' },
      { label: 'Contact Outsourced Programmers', url: '/contact', note: 'Discuss a bounded programming assignment.' },
    ],
  };
}

export const october2BlogBatch = topics.map((topic) => ({
  slug: topic.slug, title: topic.title, excerpt: topic.excerpt, minutes: 12, published: '2026-10-02',
}));

export const october2BlogDetails: Record<string, BlogDetail> = Object.fromEntries(
  topics.map((topic, index) => [topic.slug, makeDetail(topic, index)]),
);
