import type { BlogDetail } from './data';

type Source = { name: string; url: string; note: string };
type Topic = {
  slug: string; title: string; excerpt: string; focus: string; system: string; owner: string;
  fixture: string; scenario: string; baseline: string; boundaries: string; evidence: string;
  diagnosis: string; correction: string; handoff: string; noteA: string; noteB: string;
  serviceUrl: string; serviceLabel: string; sources: readonly Source[];
};

const topics: readonly Topic[] = [
  {
    slug: 'outsource-nextjs-streaming-personalization-cache-test',
    title: 'Test Next.js streaming personalization without caching one user’s shell for another',
    excerpt: 'Separate static shells, streamed boundaries, request identity, cache tags, navigation, and logout with disposable users.',
    focus: 'Next.js streaming personalization and cache isolation', system: 'Next.js application', owner: 'Next.js architecture and security owner',
    fixture: 'an isolated route with two disposable users, anonymous state, a shared static shell, personalized streamed regions, tagged data, controlled response delays, clean browser profiles, and captured cache headers',
    scenario: 'User A loads a delayed personalized dashboard, User B requests the same URL while the stream is open, and then User A signs out before both clients navigate back from browser history.',
    baseline: 'Load the route anonymously and as each user in clean profiles, recording initial HTML, streamed chunks, final DOM, server reads, and cache observations.',
    boundaries: 'Interleave two users, delay each boundary, refresh, prefetch, navigate through history, sign in and out, revalidate tags, restart the server, and repeat through the configured edge cache.',
    evidence: 'source revision, route, request identity label, initial HTML digest, streamed chunk sequence, cache status and key inputs, data tags, rendered identity, navigation action, logout time, and final DOM',
    diagnosis: 'Classify every fragment by whether it is public, request-specific, user-specific, or invalidated by content. A route-level cache decision can be unsafe even when the visibly personalized component runs dynamically.',
    correction: 'Keep identity-dependent reads inside the correct dynamic boundary, avoid caching personalized responses under shared keys, scope tags to truthful data ownership, and clear or refresh client state at authentication transitions.',
    handoff: 'Include paired-user transcripts, chunk timing, HTML and DOM comparisons, cache configuration, navigation and logout cases, regression tests, and any hosting-layer cache behavior not reproduced locally.',
    noteA: 'Streaming changes when bytes become visible, while caching changes which computation runs at all. Review these as separate dimensions. Capture the server-produced shell before hydration and each later chunk so a personalized value cannot hide behind a correct final screenshot. The most important negative control uses two identities against the same URL and cache state. If only one browser is tested at a time, a shared cache leak can look like an ordinary successful render.',
    noteB: 'Authentication transitions are especially revealing because client routers, prefetched payloads, browser history, and server caches can retain different generations of the page. Define the expected result after sign-in, sign-out, and back navigation. A safe implementation should not briefly restore the previous account’s name or private counts while new data streams. Treat such a flash as disclosure evidence, not harmless visual polish, and trace which cached layer supplied it.',
    serviceUrl: '/services/nextjs-development', serviceLabel: 'Next.js development',
    sources: [{ name: 'Next.js caching guide', url: 'https://nextjs.org/docs/app/guides/caching', note: 'Official cache interactions and invalidation guidance.' }, { name: 'Next.js loading UI and streaming', url: 'https://nextjs.org/docs/app/getting-started/linking-and-navigating#streaming', note: 'Official streaming behavior.' }],
  },
  {
    slug: 'outsource-react-form-state-race-condition-test',
    title: 'Test React form state when submissions finish out of order',
    excerpt: 'Control validation, double submits, navigation, retries, and response order before accepting an outsourced form repair.',
    focus: 'React form submission race behavior', system: 'React application', owner: 'React product owner',
    fixture: 'a representative form with labelled requests, controllable response delays, success and validation failures, keyboard focus markers, navigation, and observable stored state',
    scenario: 'A user submits Address A, immediately corrects it to Address B, and receives the first response after the second response has already succeeded.',
    baseline: 'Submit one valid value and one invalid value separately, recording pending controls, announcements, focus, rendered data, and stored data.',
    boundaries: 'Reverse two response orders, press submit twice, edit while pending, navigate away and back, retry a failure, and unmount the form before completion.',
    evidence: 'component revision, user intent, request identifier, submitted snapshot, pending state, completion order, rendered value, stored value, focus, announcement, and retry outcome',
    diagnosis: 'Tie each response to the intent and data snapshot that created it. A last-response-wins implementation can overwrite a newer successful choice with older data or an obsolete error.',
    correction: 'Disable only unsafe duplicate operations, associate results with request identity, reconcile from authoritative data, preserve the newest edit, and expose a keyboard-accessible recovery path.',
    handoff: 'Provide the timing harness, response-order matrix, screen-reader status observations, final server state, screenshots of each terminal state, and an explicit list of navigation cases.',
    noteA: 'The useful unit of evidence is not a green component test with immediate promises. It is a timeline. Record when the user changed each field, when each payload was captured, when pending UI appeared, and when each response altered the screen. A timeline exposes whether the component is reasoning about the user’s current intent or simply applying callbacks in arrival order. It also gives a reviewer a repeatable way to challenge the proposed fix.',
    noteB: 'Do not solve the race by freezing the whole page unless the product truly requires a single blocking transaction. Users may need to correct unrelated fields, copy information, or leave safely. Review cancellation and unmount behavior alongside visible errors. A rejected earlier request should not steal focus from a later success, while a genuine current failure must remain perceivable and recoverable without forcing the user to reconstruct the entire form.',
    serviceUrl: '/services/react-application-development', serviceLabel: 'React application development',
    sources: [{ name: 'React useActionState', url: 'https://react.dev/reference/react/useActionState', note: 'Official action state API.' }, { name: 'WAI-ARIA status role', url: 'https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA22', note: 'Accessible status-message technique.' }],
  },
  {
    slug: 'outsource-nodejs-abort-signal-cleanup-test',
    title: 'Test Node.js request cancellation before outsourcing a slow endpoint',
    excerpt: 'Trace abort signals through database, fetch, stream, timer, and cleanup paths with harmless fixtures.',
    focus: 'Node.js request cancellation and cleanup', system: 'Node.js API', owner: 'Node.js service owner',
    fixture: 'an isolated endpoint with a slow upstream, controlled database delay, streamed output, labelled timers, an aborting client, resource counters, and harmless generated data',
    scenario: 'A client disconnects after headers arrive while the service is waiting on an upstream request and holding a database connection for the same operation.',
    baseline: 'Complete the endpoint normally at short and representative durations, recording resource acquisition, response events, and final open-handle counts.',
    boundaries: 'Abort before headers, during an upstream call, during streaming, after the database query, and while several requests are active; also inject cleanup failures.',
    evidence: 'service revision, request identifier, client event, abort reason and time, upstream state, query state, stream events, timer state, resource release time, logs, and process handle count',
    diagnosis: 'Map ownership for every resource. Client disconnect, framework cancellation, upstream timeout, and internal deadline are different events even when they should converge on the same bounded cleanup path.',
    correction: 'Propagate an AbortSignal where APIs support it, stop producing unused work, close only resources owned by the request, make cleanup idempotent, and retain a separate service-level timeout.',
    handoff: 'Attach the cancellation timeline, resource counters before and after every case, masked logs, test commands, known libraries that ignore signals, and the chosen timeout policy for owner review.',
    noteA: 'Cancellation is valuable because it protects capacity, not because every disconnected request must instantly disappear. Some database operations cannot be interrupted safely, and some shared work should continue for other subscribers. The ticket should classify each operation as request-owned, shared, or irreversible. That classification tells the programmer whether to abort, detach, await cleanup, or merely stop writing to the response, avoiding a broad fix that cancels work another request still needs.',
    noteB: 'Watch the unhappy cleanup path as carefully as the primary error. Event listeners that remain attached, rejected cleanup promises, and timers that retain request objects can leak memory long after the HTTP socket is gone. Repeat the abort scenario enough times to reveal growth, but use bounded loads rather than an uncontrolled stress test. A stable handle count and released pool slot are stronger evidence than a log line saying the request was cancelled.',
    serviceUrl: '/services/nodejs-api-development', serviceLabel: 'Node.js API development',
    sources: [{ name: 'Node.js AbortController', url: 'https://nodejs.org/api/globals.html#class-abortcontroller', note: 'Official cancellation primitive.' }, { name: 'Node.js HTTP request events', url: 'https://nodejs.org/api/http.html', note: 'Official request lifecycle reference.' }],
  },
  {
    slug: 'outsource-wordpress-plugin-schema-upgrade-rehearsal',
    title: 'Rehearse a WordPress plugin schema upgrade before changing stored site data',
    excerpt: 'Test version gates, concurrent requests, partial failures, multisite scope, retries, and rollback with disposable tables.',
    focus: 'WordPress plugin database schema upgrades', system: 'WordPress plugin and database', owner: 'WordPress application and database owner',
    fixture: 'a staging site with disposable plugin tables and options, old and new plugin builds, representative synthetic rows, multisite fixtures where supported, concurrent request controls, injected query failures, and database snapshots',
    scenario: 'Two requests load immediately after deployment, both observe the old schema version, and one upgrade fails after adding a column but before recording its new version.',
    baseline: 'Install the old build, create representative records, record schema and version markers, then upgrade once with no traffic and verify reads, writes, and repeat execution.',
    boundaries: 'Start concurrent upgrades, fail each migration step, retry from partial state, activate per site and network-wide, skip a historical version, roll code back, and uninstall a disposable fixture.',
    evidence: 'WordPress, database and plugin versions, site or network ID, migration step, schema before and after, version marker, request identifier, query result, lock or coordination state, row counts, application behavior, retry, and rollback result',
    diagnosis: 'Treat the schema and recorded version as one state machine. A request can observe partial DDL or data conversion even when the activation hook appeared to succeed.',
    correction: 'Make each step detectable and safe to resume, coordinate competing runners, separate large data backfills from request startup, verify affected rows, and define the earliest code version compatible with the new schema.',
    handoff: 'Include schema diffs, version-path matrix, failure injection results, concurrency evidence, representative data checks, multisite scope, retry commands, backup and rollback limits, and owner-approved release sequencing.',
    noteA: 'Activation hooks do not cover every real update path: automatic updates, command-line deployment, network activation, and a process restart can reach code before a privileged administrator visits a screen. Locate where the version check truly runs and measure its cost. A migration that scans a large table during ordinary traffic can turn a correct schema change into an outage. The rehearsal should distinguish fast structural preparation from backfill work that needs its own resumable operational step.',
    noteB: 'Rollback is a compatibility question, not just a database restore instruction. New code may write values the previous build cannot interpret, and a later migration may drop information the old build requires. Document a point of no return and prefer expand-and-contract sequencing where both builds can coexist temporarily. If multisite is supported, prove whether markers and tables are global or site-specific; a successful first site must not conceal hundreds of unvisited schemas.',
    serviceUrl: '/services/wordpress-engineering', serviceLabel: 'WordPress engineering',
    sources: [{ name: 'WordPress creating tables with plugins', url: 'https://developer.wordpress.org/plugins/creating-tables-with-plugins/', note: 'Official schema installation and upgrade guidance.' }, { name: 'WordPress multisite network administration', url: 'https://developer.wordpress.org/advanced-administration/multisite/administration/', note: 'Official multisite operating context.' }],
  },
  {
    slug: 'outsource-shopify-webhook-hmac-replay-test',
    title: 'Test Shopify webhook verification and replay handling before outsourcing a consumer',
    excerpt: 'Verify raw-body signatures, duplicates, ordering, retries, deletion events, and bounded acknowledgement.',
    focus: 'Shopify webhook authenticity and replay handling', system: 'Shopify webhook consumer', owner: 'Shopify application and commerce owner',
    fixture: 'a development store, captured synthetic webhook payloads, valid and altered signatures, duplicate delivery identifiers, controlled event order, a durable receipt store, and delayed processing',
    scenario: 'The same paid-order webhook arrives twice around a cancellation webhook while one consumer pauses after recording the event but before finishing downstream work.',
    baseline: 'Deliver one correctly signed supported event, verify the acknowledgement time, durable receipt, business effect, and masked operational record.',
    boundaries: 'Alter raw bytes, signature and topic headers, duplicate deliveries before and after completion, reverse related topics, omit referenced data, delay processing, and replay after restart.',
    evidence: 'application revision, shop, topic, webhook and delivery identifiers, raw-body digest, signature result, received time, acknowledgement, receipt state, attempt, business effect, and terminal state',
    diagnosis: 'Authenticate the exact received bytes before parsing, then treat authenticity and idempotency as separate controls. A valid signature does not make a repeated or stale business transition safe.',
    correction: 'Use constant-time signature comparison, persist a unique receipt before effects, make processing retry-safe, fetch authoritative state when order matters, and acknowledge within the platform window.',
    handoff: 'Provide masked request fixtures, signature tests, duplicate and ordering matrix, receipt schema, recovery procedure, processing latency, and merchant-owned decisions about conflicting states.',
    noteA: 'A webhook is a notification that something happened, not necessarily a complete current snapshot. If two topics can describe related transitions, replaying their payloads in delivery order may produce the wrong final state. The consumer should document which decisions can rely on payload data and which require a current API lookup. This is especially important when the downstream action affects inventory, fulfilment, customer messaging, or another operation that cannot be casually reversed.',
    noteB: 'Keep the acknowledgement path small. Signature verification and durable receipt usually belong before the successful response, while slow integrations belong in a retryable worker. Test the failure between those phases: if the process exits after receipt but before enqueueing, the event still needs a visible recovery path. Conversely, if the event is enqueued but the receipt is not committed, redelivery must not create a second irreversible effect.',
    serviceUrl: '/services/shopify-development', serviceLabel: 'Shopify development',
    sources: [{ name: 'Shopify webhook HTTPS delivery', url: 'https://shopify.dev/docs/apps/build/webhooks/subscribe/https', note: 'Official validation and response guidance.' }, { name: 'Shopify webhook best practices', url: 'https://shopify.dev/docs/apps/build/webhooks/best-practices', note: 'Official duplicate and reconciliation guidance.' }],
  },
  {
    slug: 'outsource-playwright-clock-dependent-test-review',
    title: 'Make Playwright tests deterministic around clocks, time zones, and expiry',
    excerpt: 'Separate browser time, server time, locale, timers, and network delay before accepting flaky-test repairs.',
    focus: 'Playwright clock-dependent test determinism', system: 'web application and Playwright suite', owner: 'QA automation and product owner',
    fixture: 'a test environment with fixed browser time, selectable time zones and locales, short-lived synthetic records, controlled network responses, and timestamped server observations',
    scenario: 'A browser is set just before local midnight, a session expires according to the server clock, and a delayed response renders a date after the visible day has changed.',
    baseline: 'Run the supported flow with real time once, recording browser, server, database, and displayed timestamps before introducing a controlled clock.',
    boundaries: 'Advance timers across expiry and midnight, change time zone and locale, delay responses, reload, open a second page, restore real time, and run workers in parallel.',
    evidence: 'application and test revision, worker, browser engine, clock source, time zone, locale, server time, stored timestamp, timer advancement, request timing, rendered text, and assertion',
    diagnosis: 'Identify which clock owns each behavior. Freezing the browser cannot control a server-side expiry, and formatting differences should not be mistaken for a wrong stored instant.',
    correction: 'Inject or control the relevant clock, compare canonical instants for business rules, assert localized output deliberately, isolate parallel workers, and restore clock state after every test.',
    handoff: 'Include a clock-ownership map, deterministic fixtures, commands, runs in each required browser, before-and-after flake evidence, cleanup hooks, and all production assumptions excluded from testing.',
    noteA: 'Avoid replacing every wait with a large timer jump. Applications often combine animation frames, microtasks, network completion, and scheduled callbacks. Advance only the clock that drives the behavior, then wait for a meaningful observable state. A test that races through hours of timers may create an impossible sequence and pass for the wrong reason. The reviewer should be able to explain why each advancement corresponds to an actual user or system interval.',
    noteB: 'Date-only values deserve their own decision. A billing day, birthday, or publication date is not interchangeable with a UTC instant. Write whether the product expects a calendar date in a named zone or a moment later formatted for display. Then test that contract around daylight-saving changes and midnight. This prevents a contractor from hiding a domain error with a snapshot update or a locale-insensitive string comparison.',
    serviceUrl: '/services/qa-automation', serviceLabel: 'QA automation',
    sources: [{ name: 'Playwright Clock', url: 'https://playwright.dev/docs/clock', note: 'Official clock emulation guide.' }, { name: 'MDN Date', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date', note: 'Platform date and time behavior.' }],
  },
  {
    slug: 'outsource-docker-healthcheck-startup-review',
    title: 'Review Docker health checks for slow startup and partial dependency failure',
    excerpt: 'Distinguish process start, readiness, liveness, warm-up, and degraded dependencies with controlled containers.',
    focus: 'Docker container health and readiness behavior', system: 'containerized application', owner: 'platform and service owner',
    fixture: 'an isolated container stack with controlled startup delay, a health endpoint, optional and required dependency proxies, resource limits, timestamped probes, and disposable state',
    scenario: 'The application process starts quickly, migrations continue for a minute, the required database is reachable, and an optional analytics dependency remains unavailable.',
    baseline: 'Start the image under normal dependencies and record process start, listening socket, health transitions, first successful real request, and steady-state probe cost.',
    boundaries: 'Delay startup, fail required and optional dependencies separately, exhaust a resource, stall the event loop, return cached health, restart during warm-up, and recover dependencies.',
    evidence: 'source and image digest, configuration, container start time, probe command and interval, exit status, health output, dependency states, application logs, request result, restart count, and recovery time',
    diagnosis: 'Define what the orchestrator may infer from each probe. A live process can be unready for traffic, while an optional dependency outage may justify degradation rather than restart.',
    correction: 'Make probes cheap and bounded, test required local capability, expose readiness separately where the platform supports it, allow truthful startup time, and avoid restart loops caused by external systems.',
    handoff: 'Attach probe definitions, transition timeline, dependency matrix, image digest, resource settings, restart observations, rollback note, and the owner-approved meaning of healthy and degraded.',
    noteA: 'A health command runs inside the same resource envelope as the application. A complicated probe can worsen the exact overload it is trying to detect, especially when many replicas probe on the same cadence. Measure its duration and allocation, and avoid deep checks that create writes or fan out across several services. The objective is an actionable local signal, not a miniature end-to-end monitoring suite hidden in the container definition.',
    noteB: 'Startup grace should reflect evidence rather than conceal an unpredictable boot. Capture the distribution of initialization steps and identify which can be moved out of request-serving startup. If migrations need exclusive control, health configuration should not let several replicas race them. If warm-up is optional, the application may accept traffic while exposing lower capacity. Record these choices so an outsourced Docker change does not silently rewrite the release model.',
    serviceUrl: '/services/devops-support', serviceLabel: 'DevOps support',
    sources: [{ name: 'Dockerfile HEALTHCHECK', url: 'https://docs.docker.com/reference/dockerfile/#healthcheck', note: 'Official probe semantics.' }, { name: 'Docker container health status', url: 'https://docs.docker.com/reference/cli/docker/container/inspect/', note: 'Official inspection reference.' }],
  },
  {
    slug: 'outsource-postgresql-online-index-build-review',
    title: 'Review a PostgreSQL online index build before outsourcing a production migration',
    excerpt: 'Rehearse locks, invalid indexes, long transactions, retries, disk use, and query plans on representative data.',
    focus: 'PostgreSQL concurrent index migration', system: 'PostgreSQL database and application', owner: 'database and release owner',
    fixture: 'a staging database with representative synthetic volume and distribution, active readers and writers, long transactions, constrained disk monitoring, saved plans, and a disposable index name',
    scenario: 'A concurrent index build reaches its validation phase while a long-running transaction remains open and application writes continue against skewed values.',
    baseline: 'Capture existing indexes, table size, write rate, representative query plans and timings, lock observations, disk headroom, and application error rate.',
    boundaries: 'Hold old transactions, increase write load, cancel during each phase, exhaust a bounded resource, create duplicate values where relevant, retry after failure, and drop the candidate.',
    evidence: 'PostgreSQL version, schema and table identifiers, migration revision, index definition, phase, progress view, locks, blocking sessions, disk change, query plans, application errors, validity, and cleanup',
    diagnosis: 'Review the entire lifecycle rather than only the SQL syntax. Concurrent creation reduces some blocking but uses multiple scans, interacts with old snapshots, and can leave an invalid artifact after failure.',
    correction: 'Use a unique durable migration step, preflight data and capacity, observe progress and blockers, define cancellation criteria, verify index validity and plans, and make retry and cleanup explicit.',
    handoff: 'Provide baseline and candidate plans, rehearsal timings, lock and disk evidence, invalid-index recovery, exact migration command, rollback limitations, and a release runbook owned by the database operator.',
    noteA: 'A faster plan in staging is not sufficient evidence when the sample lacks production-like selectivity. Build distributions that represent common and worst-case predicates, including nulls and heavily repeated values. Compare plans with the same parameters the application uses, not hand-picked literals alone. If prepared statements or generic plans matter, exercise them explicitly. This makes the index decision about actual workload shape rather than the existence of a new object.',
    noteB: 'Decide what happens if the build is cancelled near the maintenance-window boundary. The runbook should say how to detect an invalid index, whether it is safe to remove immediately, and what evidence is required before retry. Do not combine index creation and destructive removal of an old index into one irreversible step. A separate observation period lets the owner confirm query adoption, write overhead, replication behavior, and storage impact.',
    serviceUrl: '/services/database-engineering', serviceLabel: 'Database engineering',
    sources: [{ name: 'PostgreSQL CREATE INDEX', url: 'https://www.postgresql.org/docs/current/sql-createindex.html', note: 'Official concurrent-build behavior.' }, { name: 'PostgreSQL index build progress', url: 'https://www.postgresql.org/docs/current/progress-reporting.html#CREATE-INDEX-PROGRESS-REPORTING', note: 'Official progress fields.' }],
  },
  {
    slug: 'outsource-mobile-biometric-session-recovery-test',
    title: 'Test mobile biometric session recovery before outsourcing an authentication change',
    excerpt: 'Exercise enrollment changes, lockout, fallback, account switching, app restore, and protected local state.',
    focus: 'mobile biometric session recovery', system: 'mobile application', owner: 'mobile product and security owner',
    fixture: 'controlled iOS and Android devices or approved emulators, disposable accounts, enrolled and changed biometric states, expired sessions, protected local records, background and terminated app states, and masked logs',
    scenario: 'A user enables biometric unlock for Account A, the operating-system enrollment changes, the server session expires, and another person signs into Account B on the same device.',
    baseline: 'Complete initial sign-in, biometric opt-in, background lock, successful unlock, explicit sign-out, and credential fallback while recording local and server identity.',
    boundaries: 'Change biometric enrollment, trigger failure and lockout, reboot, restore app state, expire and revoke sessions, switch accounts, reinstall, and deny the biometric prompt.',
    evidence: 'platform and OS version, app build, device fixture, current account, enrollment state category, protected-key result, server session state, prompt outcome, fallback path, visible destination, local data, and audit event',
    diagnosis: 'Separate local user presence from server authentication. A successful biometric prompt may unlock a device-held key, but it does not refresh revoked authorization or choose the correct application account.',
    correction: 'Bind protected material to the intended account, validate the server session after local unlock, invalidate on relevant enrollment changes, provide secure fallback, and clear account-scoped data at sign-out.',
    handoff: 'Include the platform matrix, state-transition diagram, masked device logs, account-switch evidence, protected-storage behavior, excluded hardware cases, and policy choices requiring security-owner approval.',
    noteA: 'Avoid recording biometric details or treating simulator behavior as proof of hardware guarantees. The application generally receives an authentication result and key-access outcome, not a fingerprint or face record. Tests should use state labels such as enrolled, changed, unavailable, failed, and locked out. This preserves privacy and keeps the evidence focused on application behavior. Hardware-backed assertions that cannot be reproduced in the available environment must remain explicitly unverified.',
    noteB: 'Recovery deserves equal weight with successful unlock. A user who cannot satisfy the biometric prompt still needs a controlled path that does not weaken account protection or trap the session permanently. Test whether fallback accidentally reveals which account is present, whether repeated failures retain sensitive screens, and whether support instructions match the implemented policy. The product owner should decide reauthentication frequency and fallback eligibility rather than leaving those choices to a contractor.',
    serviceUrl: '/services/mobile-app-development', serviceLabel: 'Mobile app development',
    sources: [{ name: 'Android biometric authentication', url: 'https://developer.android.com/identity/sign-in/biometric-auth', note: 'Official Android guidance.' }, { name: 'Apple LocalAuthentication', url: 'https://developer.apple.com/documentation/localauthentication', note: 'Official Apple framework reference.' }],
  },
  {
    slug: 'outsource-legacy-csv-import-encoding-safety-test',
    title: 'Test a legacy CSV import for encoding, delimiter, and spreadsheet-formula hazards',
    excerpt: 'Exercise byte order marks, mixed encodings, quoted records, formulas, duplicate rows, and export round trips with synthetic files.',
    focus: 'legacy CSV import encoding and content safety', system: 'legacy data-import workflow', owner: 'data product and security owner',
    fixture: 'synthetic CSV files with UTF-8 and legacy encodings, byte order marks, several delimiters, embedded newlines, quoted separators, Unicode names, leading formula characters, duplicate business keys, controlled row errors, and a disposable import account',
    scenario: 'A file advertised as UTF-8 contains a legacy-encoded row, a quoted address spans two physical lines, and a customer label begins with an equals sign before the imported data is exported for spreadsheet review.',
    baseline: 'Import one minimal valid file and one representative valid file, recording detected format, logical records, normalized values, row decisions, database state, and a safe export round trip.',
    boundaries: 'Change encoding and delimiter, add or remove a byte order mark, truncate quoted records, include formula prefixes, repeat headers and keys, mix line endings, exceed field limits, and retry a partially rejected file.',
    evidence: 'application revision, file digest and declared format, detected encoding and delimiter, physical line and logical record, normalized field values, validation decision, business key, inserted or changed record, error report, retry result, and exported cell representation',
    diagnosis: 'Separate byte decoding, CSV parsing, field normalization, business validation, persistence, and export. An error reported on a physical line can point at the wrong logical record when quoted newlines are permitted.',
    correction: 'Require or reliably constrain supported encodings, use a maintained parser, preserve an explicit row identity, reject ambiguous decoding, make writes atomic or resumable, and neutralize formula-leading values when producing spreadsheet-bound exports.',
    handoff: 'Provide the fixture corpus, support matrix, file digests, row-level expected results, database reconciliation, safe export evidence, retry semantics, performance limits, and product-owner decisions for ambiguous input.',
    noteA: 'Do not “fix” undecodable bytes by silently replacing characters when those characters participate in names, identifiers, or duplicate detection. Replacement can merge distinct values or make later reconciliation impossible. Record the byte offset and logical record without reproducing sensitive content in logs. If the product permits several encodings, require a deterministic selection rule and include characters that differ across candidate code pages so the test can detect a confident but wrong guess.',
    noteB: 'Formula injection usually becomes visible after import, when stored text is exported and opened in a spreadsheet. Preserve the intended business text while ensuring the export consumer treats it as data rather than a formula. Test equals, plus, minus, at-sign, leading whitespace, tabs, and quotes according to the approved output format. This decision belongs to the data and security owners because indiscriminate prefixing can alter legitimate identifiers and break round trips.',
    serviceUrl: '/services/legacy-application-maintenance', serviceLabel: 'Legacy application maintenance',
    sources: [{ name: 'RFC 4180 CSV format', url: 'https://www.rfc-editor.org/rfc/rfc4180', note: 'Common CSV record and quoting rules.' }, { name: 'OWASP CSV Injection', url: 'https://owasp.org/www-community/attacks/CSV_Injection', note: 'Spreadsheet formula-injection risk and mitigations.' }],
  },
  {
    slug: 'outsource-graphql-persisted-query-cache-review',
    title: 'Review GraphQL persisted-query caches before outsourcing an API optimization',
    excerpt: 'Test hashes, variables, authorization, schema changes, eviction, negative entries, and mixed client versions.',
    focus: 'GraphQL persisted-query cache behavior', system: 'GraphQL client, gateway, and API', owner: 'GraphQL API and security owner',
    fixture: 'a sandbox schema, two disposable roles and tenants, approved query documents and hashes, changed documents, old and new clients, controlled gateway caches, schema versions, and saved request traces',
    scenario: 'An old client sends a known hash with Tenant A variables after a privileged user has warmed the gateway, while the schema has changed the queried field authorization.',
    baseline: 'Execute each approved document with and without its full text for every supported role, recording resolution, authorization, response, cache events, and upstream work.',
    boundaries: 'Change hashes and documents, reuse hashes across identities and tenants, alter variables, deploy a schema change, evict entries, send unknown hashes repeatedly, and mix client versions.',
    evidence: 'client, schema, gateway and server revisions, identity and tenant, document digest, operation name, variables classification, cache key and outcome, authorization decision, response fields, errors, and upstream execution',
    diagnosis: 'Determine what is actually cached. Resolving a hash to an approved document can be shared, but a response that depends on identity, tenant, variables, or authorization cannot inherit another caller’s scope.',
    correction: 'Verify document digests, allowlist where intended, keep authorization at execution, design complete cache keys, bound negative caching, version schema-dependent entries, and rate-limit abusive misses.',
    handoff: 'Attach the operation registry sample, cache-key specification, role and tenant matrix, mixed-version traces, miss-rate observations, invalidation behavior, and owner decisions about allowlisting and rollout.',
    noteA: 'Persisted queries reduce request size and can constrain operations, but they do not make variables safe. A permitted document may still ask for another tenant’s object through an identifier supplied at runtime. Test object-level authorization with the cached document already warm so a fast path cannot skip checks performed during registration or parsing. Compare selected fields too; schema directives and resolver rules may evolve independently of the stored document.',
    noteB: 'Unknown-hash behavior needs a resource budget. If every miss triggers database work, remote registration, or expensive parsing, an attacker can fill caches or amplify load with random values. Measure miss handling and eviction under a bounded sequence. Decide whether clients may register documents dynamically, which identity can do so, and how old entries retire. A clear policy prevents an outsourced performance change from quietly becoming a new API publishing mechanism.',
    serviceUrl: '/services/nodejs-api-development', serviceLabel: 'Node.js API development',
    sources: [{ name: 'GraphQL over HTTP', url: 'https://graphql.github.io/graphql-over-http/draft/', note: 'GraphQL HTTP request guidance.' }, { name: 'Apollo persisted queries', url: 'https://www.apollographql.com/docs/apollo-server/performance/apq', note: 'Persisted-query behavior and cache considerations.' }],
  },
  {
    slug: 'outsource-github-actions-concurrency-cancellation-test',
    title: 'Test GitHub Actions concurrency cancellation before changing a release workflow',
    excerpt: 'Exercise overlapping commits, environment waits, reusable workflows, cleanup, and stale deployment protection without releasing.',
    focus: 'GitHub Actions release concurrency and cancellation', system: 'GitHub Actions build and release workflow', owner: 'repository and release owner',
    fixture: 'a test workflow with harmless build artifacts, two rapidly updated branches, controlled job delays, a protected test environment, concurrency groups, reusable jobs, cancellation traps, immutable commit labels, and no production credentials',
    scenario: 'Commit A finishes its build and waits for environment approval while Commit B enters the same concurrency group, cancels A, and completes an artifact step before its own approval is reviewed.',
    baseline: 'Run one commit from start to finish without deployment, recording group expression, job ordering, artifact digest, environment wait, cancellation status, cleanup, and terminal workflow conclusion.',
    boundaries: 'Push two and three commits quickly, cancel during build and environment wait, rerun an old attempt, vary branch and case, call a reusable workflow, fail cleanup, and approve a superseded run.',
    evidence: 'repository and workflow revision, event, ref, immutable commit, run and attempt IDs, evaluated concurrency group, job state transitions, cancellation initiator and time, artifact digest, environment approval, cleanup result, and selected release candidate',
    diagnosis: 'Map concurrency at workflow, job, environment, and external release layers. Cancelling a runner does not automatically retract an artifact, approval, or side effect already handed to another system.',
    correction: 'Choose a stable group that matches the release lane, define intentional cancel-in-progress behavior, verify the current commit again at privileged boundaries, make cleanup idempotent, and reject approvals or artifacts from superseded runs.',
    handoff: 'Provide the concurrency expression, overlap timeline, run links and commit map, artifact digests, cancelled-step observations, environment cases, cleanup evidence, rerun behavior, and release-owner decisions about queueing versus replacement.',
    noteA: 'A concurrency group is text derived from context, so small expression choices can split what operators believe is one lane or combine unrelated lanes. Record evaluated group values for branches, tags, pull requests, and reusable callers. Normalize case assumptions and consider missing context values. The review should explain whether the business rule is “one build per branch,” “one candidate per environment,” or “one release for the whole service,” because those are different serialization problems.',
    noteB: 'Cancellation is cooperative. A shell command, remote build, uploaded artifact, or environment approval can survive after the job receives a cancellation signal. Insert controlled pauses around each handoff and inspect the state that remains. Before any privileged action, compare the intended commit with the repository’s current approved candidate rather than trusting that the workflow is still newest. This protects against stale reruns and delayed approvals without asking the automation to deploy during the review.',
    serviceUrl: '/services/devops-support', serviceLabel: 'DevOps support',
    sources: [{ name: 'GitHub Actions concurrency', url: 'https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/control-workflow-concurrency', note: 'Official group and cancellation semantics.' }, { name: 'GitHub deployment environments', url: 'https://docs.github.com/en/actions/reference/workflows-and-actions/deployments-and-environments', note: 'Official environment protection behavior.' }],
  },
];

const sharedSource: Source = { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/Projects/ssdf', note: 'NIST practices for scoped software changes and retained evidence.' };

function makeDetail(topic: Topic, index: number): BlogDetail {
  return {
    strictNoPricing: true,
    heroImage: index % 2 === 0 ? '/programmer-workbench.jpg' : '/illustrations/getillustrations/inkdex-saas/code-control.webp',
    takeaways: [
      `Scope one observable ${topic.focus} decision.`,
      `Use ${topic.fixture}.`,
      `Retain ${topic.evidence}.`,
      `Keep policy, merge, and release approval with the ${topic.owner}.`,
    ],
    readinessRows: [
      { area: 'Decision', ready: `One expected ${topic.focus} outcome`, notReady: 'A broad request to improve the whole system' },
      { area: 'Fixture', ready: topic.fixture, notReady: 'Live customer data or unrestricted credentials' },
      { area: 'Evidence', ready: topic.evidence, notReady: 'A pass label without inputs and observed state' },
      { area: 'Owner', ready: `The ${topic.owner} is named`, notReady: 'The contractor approves the production change' },
    ],
    sections: [
      { id: 'define-the-decision', title: `Define the ${topic.focus} decision`, paragraphs: [
        `Turn the request into a decision a company reviewer can make. For this assignment, ask whether the ${topic.system} behaves correctly at one ${topic.focus} boundary. Name the component, data path, expected result, and stopping condition. The outsourced programmer may prepare evidence and propose a correction; the ${topic.owner} retains decisions about policy, customer impact, privileged access, merge, and release.`,
        `Write the source revision, environment, allowed identities, prohibited actions, and cleanup rule into the ticket. Use ${topic.fixture}. A resettable synthetic fixture permits denied, expired, repeated, and malformed cases without exposing real records. Label every input and expected state so another reviewer can reproduce the same observation from a clean checkout.`,
      ] },
      { id: 'topic-specific-risk', title: `Understand the specific ${topic.focus} risk`, paragraphs: [topic.noteA, topic.noteB] },
      { id: 'baseline-and-boundaries', title: 'Compare the baseline with meaningful boundary cases', paragraphs: [
        `${topic.baseline} Save the current result before changing code. A baseline describes what the system does now; it does not declare that behavior correct. Separate known defects from the acceptance rule and record any missing setup that prevents a clean reproduction.`,
        `${topic.scenario} Use this concrete sequence as the first disagreement the software must resolve. Then expand deliberately: ${topic.boundaries} Change one important condition at a time and keep a control case beside it. That makes a failed run explainable instead of producing a pile of screenshots with several possible causes.`,
      ] },
      { id: 'diagnose-before-editing', title: 'Diagnose the boundary before editing implementation code', paragraphs: [
        `${topic.diagnosis} Trace input, identity, state, timing, ownership, and the final durable effect. Identify where the expected rule should be enforced and whether another layer can bypass it. Do not accept a client-side restriction, log message, or happy-path test as proof when a direct or reordered request can still reach the behavior.`,
        `Record ${topic.evidence}. Mask tokens, credentials, personal data, and full sensitive payloads while preserving identifiers needed to correlate events. Include the exact revision and commands. Evidence should let the named owner distinguish an implementation defect, a fixture defect, an environmental limit, and an unresolved product decision.`,
      ] },
      { id: 'correct-and-regress', title: 'Make the smallest correction and challenge it again', paragraphs: [
        `${topic.correction} Prefer a narrow change at the owning boundary over duplicated checks scattered through the interface. Add an automated regression for the original failure and at least one negative control that proves the test would notice a missing safeguard.`,
        `Repeat the baseline and boundary matrix after the change. Inspect both visible output and durable state; a friendly error can coexist with an unauthorized write or leaked resource. Run related existing tests, review the diff for widened access or hidden fallback behavior, and document conditions the available environment could not exercise. A result is ready for review only when it is reproducible, not merely when the newest run is green.`,
      ] },
      { id: 'handoff-and-estimate', title: 'Leave a decision-ready handoff and bounded next step', paragraphs: [
        `${topic.handoff} Link the ticket, branch or pull request, fixture, commands, observed results, code diff, risks, and decisions needed. State who cleans up accounts and artifacts. Keep production credentials and release controls outside the contractor’s default lane.`,
        `Estimate discovery, fixture work, reproduction, correction, regression, review, and documentation separately. If the boundary remains uncertain, stop with a paid diagnostic handoff rather than silently expanding into an architecture rewrite. The next ticket should name one observable outcome, its reviewer, and a rollback or stop-work condition. That structure makes outsourced programming useful without transferring accountability that belongs inside the company.`,
      ] },
    ],
    roleBrief: [
      { label: 'Assignment', text: `Review one bounded ${topic.focus} decision in the ${topic.system}.` },
      { label: 'Fixture', text: topic.fixture },
      { label: 'Evidence', text: `Retain ${topic.evidence}.` },
      { label: 'Owner decision', text: `The ${topic.owner} approves policy, merge, and release.` },
    ],
    faqs: [
      { question: 'What should the first run prove?', answer: topic.baseline },
      { question: 'What should the programmer change?', answer: topic.correction },
      { question: 'What belongs in the handoff?', answer: topic.handoff },
    ],
    sources: [...topic.sources, sharedSource],
    internalLinks: [
      { label: topic.serviceLabel, url: topic.serviceUrl, note: `Plan scoped ${topic.focus} support.` },
      { label: 'Build a technical handoff', url: '/blog/outsourced-programmer-technical-handoff', note: 'Give the reviewer reproducible evidence.' },
      { label: 'Set code review rules', url: '/blog/outsourced-programmer-code-review-rules', note: 'Keep approval and release authority clear.' },
    ],
  };
}

export const september28BlogBatch = topics.map((topic) => ({
  slug: topic.slug, title: topic.title, excerpt: topic.excerpt, minutes: 12, published: '2026-09-28',
}));

export const september28BlogDetails: Record<string, BlogDetail> = Object.fromEntries(
  topics.map((topic, index) => [topic.slug, makeDetail(topic, index)]),
);
