import type { BlogDetail } from "./data";

type Topic = { slug:string; title:string; excerpt:string; focus:string; failure:string; fixture:string; record:string; boundary:string };
const topics: readonly Topic[] = [
  {slug:"outsource-idempotency-key-retention-test",title:"Test idempotency keys after their retention window closes",excerpt:"Check duplicate requests just before and after a server forgets a key.",focus:"idempotency-key retention",failure:"A late retry can create a second resource after the original key expires.",fixture:"a sandbox endpoint with inert transactions and fixed request bodies",record:"key hash, request hash, response, retry time, resource ID, and expiry rule",boundary:"The API owner approves retention, conflict behavior, and production changes."},
  {slug:"outsource-kubernetes-termination-grace-period-drill",title:"Watch a Kubernetes workload run out of termination grace",excerpt:"Rehearse shutdown with active requests, slow cleanup, and a replacement pod.",focus:"pod termination",failure:"The platform can stop a pod before its active request or final write completes.",fixture:"an isolated namespace with a synthetic slow request and controlled deletion",record:"pod UID, endpoint removal, signal time, request count, exit code, and replacement readiness",boundary:"The platform owner sets grace periods, disruption rules, and rollout."},
  {slug:"outsource-email-suppression-list-sync-qa",title:"Trace an email address through suppression-list synchronization",excerpt:"Check bounces, complaints, local preferences, and delayed provider updates.",focus:"email suppression synchronization",failure:"A delayed sync can send another message to an address that should remain suppressed.",fixture:"provider sandbox events and owned test inboxes",record:"recipient hash, event ID, provider time, local state, sync attempt, and final decision",boundary:"Messaging and privacy owners approve resubscription policy and provider changes."},
  {slug:"outsource-redis-eviction-policy-rehearsal",title:"Rehearse Redis eviction with data that has different jobs",excerpt:"Find which cache, session, and queue-like keys disappear at the memory limit.",focus:"Redis eviction",failure:"A memory limit can evict data whose loss changes behavior instead of merely slowing a request.",fixture:"an isolated Redis instance with labelled disposable keys and known TTLs",record:"server version, policy, memory, key type, TTL, evicted key, and client result",boundary:"The service owner decides which data may be evicted and approves policy changes."},
  {slug:"outsource-cdn-cache-key-query-parameter-review",title:"Review which query parameters belong in a CDN cache key",excerpt:"Compare content variants, private responses, and ignored tracking parameters.",focus:"CDN cache keys",failure:"A missing parameter can serve the wrong variant while an unnecessary one splinters the cache.",fixture:"a test hostname with synthetic public responses and controlled parameters",record:"URL, normalized key, response marker, cache status, age, headers, and purge result",boundary:"Web and security owners approve cache rules and private-response handling."},
  {slug:"outsource-schema-registry-compatibility-check",title:"Put a schema registry compatibility rule against real change shapes",excerpt:"Test added, removed, renamed, and retyped fields with disposable schemas.",focus:"schema compatibility",failure:"A registry can accept a schema that still breaks an older consumer.",fixture:"a temporary subject with a baseline and one controlled change per version",record:"subject, mode, schema IDs, change, registry result, consumer result, and rollback",boundary:"The data-platform owner defines compatibility promises and approves schemas."},
  {slug:"outsource-browser-storage-migration-qa",title:"Test a browser storage migration with old tabs still open",excerpt:"Exercise upgrades, interrupted writes, quota errors, and mixed application versions.",focus:"browser storage migration",failure:"An old tab can write stale data after a new tab migrates the store.",fixture:"disposable profiles seeded with each supported schema version",record:"browser, tab build, schema version, migration step, error, counts, and reopened state",boundary:"The product owner approves data-loss behavior and release sequencing."},
  {slug:"outsource-webhook-destination-dns-change-test",title:"Test webhook delivery when a destination changes DNS answers",excerpt:"Observe connection reuse, retries, allow-list checks, and delivery evidence.",focus:"webhook DNS changes",failure:"A client can keep using an old address or follow a new answer outside the intended boundary.",fixture:"owned hostnames with controlled DNS and receivers for inert signed events",record:"event ID, lookup time, address, connection ID, attempt, response, and retry",boundary:"Network and security owners approve egress rules and production tests."},
  {slug:"outsource-clock-skew-token-validation-qa",title:"Move two clocks apart and inspect token validation",excerpt:"Check issued-at, not-before, expiry, refresh, and logs without weakening live authentication.",focus:"token clock-skew handling",failure:"Services with different clocks can reject a fresh token or accept an expired one too long.",fixture:"local issuer and verifier processes with controlled clocks and disposable keys",record:"issuer time, verifier time, claims, allowed skew, decision, error, and refresh result",boundary:"Identity and security owners approve tolerance and token lifetime."},
  {slug:"outsource-data-import-resume-checkpoint-test",title:"Interrupt a data import at every checkpoint that matters",excerpt:"Verify restart, duplicate handling, reconciliation, and operator visibility.",focus:"data-import checkpoints",failure:"A resumed import can skip rows, apply them twice, or report success too early.",fixture:"a synthetic file with stable row IDs and controlled process stops",record:"file hash, row range, checkpoint, stop time, applied IDs, rejected IDs, and final counts",boundary:"The data owner approves mapping, rollback, and every live import."},
  {slug:"outsource-service-worker-update-race-qa",title:"Catch a service worker update between two page loads",excerpt:"Test waiting workers, mixed asset versions, cache cleanup, and recovery.",focus:"service-worker updates",failure:"A page can run new code against old cached assets or retain a broken worker.",fixture:"a test origin with two labelled builds and clean browser profiles",record:"page build, worker state, cache names, asset response, reload path, and recovery",boundary:"The web owner approves activation policy and production release."},
  {slug:"outsource-audit-log-pagination-integrity-review",title:"Check an audit log for gaps across pagination boundaries",excerpt:"Use known events to test ordering, cursors, filters, exports, and access.",focus:"audit-log pagination",failure:"Tied timestamps or changing records can hide or repeat events during review.",fixture:"a synthetic tenant with sequenced events, tied timestamps, and page mutations",record:"event IDs, sort fields, cursor, filters, order, duplicates, omissions, and export count",boundary:"Security and compliance owners decide retention and evidentiary requirements."},
];
const sources = [{name:"NIST Secure Software Development Framework",url:"https://csrc.nist.gov/Projects/ssdf",note:"NIST guidance for managing software development risk."},{name:"GitHub pull request reviews",url:"https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews",note:"First-party documentation for review and approval."}];
function makeDetail(t:Topic,i:number):BlogDetail{return {strictNoPricing:true,heroImage:i%2?"/illustrations/getillustrations/inkdex-saas/code-control.webp":"/programmer-workbench.jpg",takeaways:[`Write the expected ${t.focus} behavior before the test.`,`Use ${t.fixture}.`,`Keep ${t.record} in the handoff.`,t.boundary],readinessRows:[{area:"Question",ready:`One observable ${t.focus} outcome`,notReady:"A request to inspect the whole system"},{area:"Fixture",ready:t.fixture,notReady:"Customer data or shared credentials"},{area:"Evidence",ready:t.record,notReady:"A pass label without observed values"},{area:"Approval",ready:t.boundary,notReady:"The contractor changes production alone"}],sections:[{id:"reproduce-the-failure",title:`Reproduce the ${t.focus} failure safely`,paragraphs:[`${t.failure} Start with one case that can fail without touching customer records or production infrastructure. Write the expected result, stop condition, and reviewer beside the fixture.`,`Use ${t.fixture}. Label every identity and artifact so a reviewer can distinguish test evidence from a live record.`]},{id:"leave-a-reviewable-record",title:"Leave enough evidence for a second person",paragraphs:[`Capture ${t.record}. Include the source revision and test time. If behavior changes between runs, retain both results.`,`${t.boundary} A remote programmer can prepare the fixture, run bounded checks, and explain the result. New policy, privileged access, and release approval stay with the named owner.`]}],roleBrief:[{label:"Assignment",text:`Test one bounded ${t.focus} case against written acceptance rules.`},{label:"Fixture",text:t.fixture},{label:"Evidence",text:`Record ${t.record}.`},{label:"Owner decision",text:t.boundary}],faqs:[{question:"What should the first run prove?",answer:`It should show the expected ${t.focus} result for one controlled fixture.`},{question:"What belongs in the handoff?",answer:`Include ${t.record}, the source revision, and any untested condition.`},{question:"Who approves a production change?",answer:t.boundary}],sources,internalLinks:[{label:"Plan an outsourced programmer role",url:"/blog/outsourced-programmers-planning",note:"Turn recurring work into a bounded assignment."},{label:"Use a technical handoff",url:"/blog/outsourced-programmer-technical-handoff",note:"Give the reviewer reproducible evidence."}]};}
export const september10BlogBatch=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:8,published:"2026-09-10"}));
export const september10BlogDetails:Record<string,BlogDetail>=Object.fromEntries(topics.map((t,i)=>[t.slug,makeDetail(t,i)]));
